### PR TITLE
Refactored hook handlers in mod_keystore

### PR DESCRIPTION
**Pull request by pawlooss1**
This PR changes all hook handlers in `mod_keystore` module to `gen_hook` format.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/150480) / small_tests / 1ee3502c09d6a558026214af470f00ce92e6253a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3849/150480/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3849/150480/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-09_12.00.43/lib.mongooseim.logs/run.2022-11-09_12.00.43/suite.log.html)

**Review by NelsonVides — COMMENTED** [review]
Just one small note.

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/150922) / small_tests / ed7f122af05d82b5d60f13a15bb079a8f5c3f163
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3849/150922/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3849/150922/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_09.15.47/lib.mongooseim.logs/run.2022-11-10_09.15.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/150955) / small_tests / f43f1e540f508f197ec18362c489d98c483dae7c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3849/150955/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3849/150955/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_09.18.10/lib.mongooseim.logs/run.2022-11-10_09.18.10/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM

**Pull request merged**
