### PR TITLE
Graphql use annotation

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
In this PR I have added "@use" directive to all schemas where it was needed. Moreover, I have deleted any unnecessary checks in API modules. The problems occurred with 3 modules:
- mod_muc
- mod_muc_light
- mod_vcard

---

In mod_muc there are 4 commands that are currently not using @use directive:
- ADMIN createInstantRoom -> it is currently impossible to get HostType from mucDomain variable
- ADMIN listRooms -> it is currently impossible to get HostType from mucDomain variable 
- USER createInstantRoom -> it is currently impossible to get HostType from mucDomain variable
- USER listRooms -> it is currently impossible to get HostType from mucDomain variable

In mod_muc_light there are 2 commands that are currently not using @use directive:
- ADMIN createInstantRoom -> it is currently impossible to get HostType from mucDomain variable
- USER createInstantRoom -> it is currently impossible to get HostType from mucDomain variable

In mod_vcard there is 1 command that currently not fully supports @use directive:
- USER getVcard -> the HostType needed for @use directive is taken from "user" variable. When it's not passed(when user takes they own VCard) its not possible to get HostType. Therefore the check if mod_vcard is loaded has been added.

---

When @use directive was added for the module or was already added, the tests were added to ensure that @use directive is working properly.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138087) / small_tests / d68f386555fa7c33b195d1ad20aaa28027cfd49f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/138087/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/138087/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-21_07.45.24/lib.mongooseim.logs/run.2022-09-21_07.45.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138112) / small_tests / 133cd8693a638b3a707bbd31abd65aa8bf1602db
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/138112/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/138112/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-21_08.14.52/lib.mongooseim.logs/run.2022-09-21_08.14.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139434) / small_tests / 71500e82e97092897112331222b9b84d8a10b301
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/139434/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/139434/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-26_14.06.47/lib.mongooseim.logs/run.2022-09-26_14.06.48/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139644) / small_tests / 07ff0d7f389bdc6245da1202ff64f60164d1da37
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/139644/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/139644/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-27_07.45.34/lib.mongooseim.logs/run.2022-09-27_07.45.34/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139807) / small_tests / 2b468cf0fd48156531c968ef25e7fb73b6c032d9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/139807/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/139807/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-28_08.19.43/lib.mongooseim.logs/run.2022-09-28_08.19.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140646) / small_tests / 2cbdc229c99e857aa60ed39cb57857144babfdd3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/140646/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/140646/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-30_10.43.49/lib.mongooseim.logs/run.2022-09-30_10.43.49/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140671) / small_tests / a2ce0d66bb562250b0e47069146aec5c6eed560f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/140671/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/140671/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-30_10.47.53/lib.mongooseim.logs/run.2022-09-30_10.47.54/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140695) / small_tests / 6c6ee3603a95b18ce04a6366176f28f58c4a7081
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/140695/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/140695/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-30_13.56.53/lib.mongooseim.logs/run.2022-09-30_13.56.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142131) / small_tests / 898f663a954d8ba26df4ce8f97a378bed7be21a1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/142131/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/142131/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_07.00.13/lib.mongooseim.logs/run.2022-10-05_07.00.13/suite.log.html)

**Comment by mongoose-im** [comment]
[pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/142207) / pgsql_mnesia / 8410861437160b1465ec355c752d3c4d112c42f6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/142207/pgsql_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142257) / small_tests / 3f6a9309ac004c9bf0319841c769e86dffda61bd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/142257/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/142257/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_08.25.23/lib.mongooseim.logs/run.2022-10-05_08.25.24/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good :+1:

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142468) / small_tests / 180c86dc1c4cf36651a0cc6eb1af0a1c27b5a779
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3767/142468/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3767/142468/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-06_05.59.17/lib.mongooseim.logs/run.2022-10-06_05.59.17/suite.log.html)

**Pull request merged**
