### PR TITLE
Remove config reload

### PR DESCRIPTION
**Pull request by chrzaszcz**
Remove the already deprecated config reload functionality with the flat config format.

In the future we might:
- Add an option to print the current TOML config.
- Bring back some reload functionality in a new way if there is demand, after improving the internal config structure.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9079.1](https://travis-ci.org/esl/MongooseIM/jobs/758343605) / Erlang 23.0.3 / small_tests / c773a12f7bbd1d1ed60d0b348fa675f920143268
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3030/9079/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3030/9079/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-10_08.40.59/lib.mongooseim.logs/run.2021-02-10_08.40.59/suite.log.html)

**Comment by mongoose-im** [comment]
[9081.1](https://travis-ci.org/esl/MongooseIM/jobs/758351593) / Erlang 23.0.3 / small_tests / f071552d48ed16b19731f1726fc4d29308448c39
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3030/9081/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3030/9081/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-10_10.18.07/lib.mongooseim.logs/run.2021-02-10_10.18.07/suite.log.html)

**Comment by mongoose-im** [comment]
[9083.1](https://travis-ci.org/esl/MongooseIM/jobs/758360518) / Erlang 23.0.3 / small_tests / 615467a84eb92933257e334f4a38e76d7d90a69d
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3030/9083/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3030/9083/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-10_11.49.01/lib.mongooseim.logs/run.2021-02-10_11.49.01/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
looks much smaller now, thanks :)

**Pull request merged**
