### PR TITLE
Fix function call

### PR DESCRIPTION
**Pull request by NelsonVides**
This function with arity 3 was not actually defined :)

### CODE REVIEW

**Comment by vkatsuba** [comment]
@gustawlippa before merge something, need wait for finishing CI... even if these are obvious changes ...

**Comment by NelsonVides** [comment]
> @gustawlippa before merge something, need wait for finishing CI... even if these are obvious changes ...

By fault as well, I suggested to merge promptly. We just waited for xref and dialyzer to be green.

**Comment by vkatsuba** [comment]
> By fault as well, I suggested to merge promptly. We just waited for xref and dialyzer to be green.

Clear.

**Comment by vkatsuba** [comment]
> feature branch with incorrect code and search for bugs in their changes

If developer didn't change code from where provided error in `xref` - he don't need find any issue in his code.

> Sure we would not do that normally, but keep in mind this is all WIP.

Following this logic - it no make sense also to create PR's at all then for current branch till time when this branch will finished and ready for PR, but this is wrong approach.

**Pull request merged**
