### PR TITLE
Access commands in maps

### PR DESCRIPTION
**Pull request by chrzaszcz**
Convert the configuration of command access rules to use maps with defaults.

This allows to remove the temporary `prepend_key` wrapper.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/124308) / small_tests / 6a224e307e83862380a263d21a6ac39299a3402a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3656/124308/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3656/124308/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-05-26_11.08.23/lib.mongooseim.logs/run.2022-05-26_11.08.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/124337) / small_tests / 4f53d012924de8638046dee763fd721ff4062ffc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3656/124337/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3656/124337/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-05-26_13.26.16/lib.mongooseim.logs/run.2022-05-26_13.26.17/suite.log.html)

**Review by Premwoik — APPROVED** [review]
Looks good

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
