### PR TITLE
Fix undefined functions

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses #1648 #1646

Proposed changes include:
* New function mongoose_helper:successful_rpc/3
* Calls fixed

### CODE REVIEW

**Comment by kzemek** [comment]
Wouldn't this be a good occasion to unify RPC methods in tests? In tests, we use `rpc:call` (e.g. `ct_mongoose_log_hook.erl`), `escalus_ct:rpc` (e.g. `component_SUITE.erl`), `escalus_ejabberd:rpc` (e.g. `acc_e2e_SUITE.erl`), `ct_rpc:call`. Then on top of that we have `distributed_helper:rpc`,`mam_helper:rpc_apply`, multiple module-local rpc wrappers (e.g. `push_SUITE.erl`, `muc_light_SUITE.erl`, `reload_helper.erl`, `s2s_SUITE.erl`, ...), and now `mongoose_helper:successful_rpc`.

Ideally (in my opinion), I'd see this trimmed down to a single RPC method that has the "successful rpc" semantics by default, with an argument to explicitly turn off these semantics (because how often do we make an rpc call in tests that we expect to be able to fail?). And maybe leave some module-local wrappers that simplify test logic.

@fenek I invite you to comment ;)

**Comment by arcusfelis** [comment]
I mean these, it's just a random piece of logs

```
2018-01-18 15:53:33.865
issue=rpc_call_failed node=mongooseim@localhost function=mnesia:table_info reason={'EXIT',
                                                                                   {aborted,
                                                                                    {no_exists,
                                                                                     roster,
                                                                                     wild_pattern}}}
----------------------------------------------------
2018-01-18 15:53:33.865
issue=rpc_call_failed node=mongooseim@localhost function=mnesia:dirty_match_object reason={'EXIT',
                                                                                           {aborted,
                                                                                            {bad_type,
                                                                                             {badrpc,
                                                                                              {'EXIT',
                                                                                               {aborted,
                                                                                                {no_exists,
                                                                                                 roster,
                                                                                                 wild_pattern}}}}}}}
----------------------------------------------------
warning 2018-01-18 15:53:33.866
Suite: cluster_commands_SUITE finished dirty. Other suites may fail because of that. Details:
{'EXIT',
 {badarg,
  [{erlang,length,
    [{badrpc,
      {'EXIT',
       {aborted,
        {bad_type,
         {badrpc,{'EXIT',{aborted,{no_exists,roster,wild_pattern}}}}}}}}],
    []},
   {mongoose_helper,count_wildpattern,1,
    [{file,"mongoose_helper.erl"},{line,159}]},
   {ct_mongoose_hook,generic_via_mongoose_helper,1,
    [{file,"src/ct_mongoose_hook.erl"},{line,191}]},
   {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
   {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
   {ct_mongoose_hook,check_server_purity,2,
    [{file,"src/ct_mongoose_hook.erl"},{line,120}]},
   {ct_mongoose_hook,post_end_per_suite,4,
    [{file,"src/ct_mongoose_hook.erl"},{line,66}]},
   {ct_hooks,catch_apply,3,[{file,"ct_hooks.erl"},{line,424}]}]}}
Testing ejabberd_tests.tests.cluster_commands_SUITE: TEST COMPLETE, 14 ok, 0 failed of 14 test cases
Testing ejabberd_tests.tests.conf_reload_SUITE: Starting test, 4 test cases
----------------------------------------------------
2018-01-18 15:54:08.059
issue=rpc_call_failed node=mongooseim@localhost function=mnesia:table_info reason={'EXIT',
                                                                                   {aborted,
                                                                                    {no_exists,
                                                                                     roster,
                                                                                     wild_pattern}}}
----------------------------------------------------
2018-01-18 15:54:08.060
issue=rpc_call_failed node=mongooseim@localhost function=mnesia:dirty_match_object reason={'EXIT',
                                                                                           {aborted,
                                                                                            {bad_type,
                                                                                             {badrpc,
                                                                                              {'EXIT',
                                                                                               {aborted,
                                                                                                {no_exists,
                                                                                                 roster,
                                                                                                 wild_pattern}}}}}}}
----------------------------------------------------
warning 2018-01-18 15:54:08.060
Suite: conf_reload_SUITE finished dirty. Other suites may fail because of that. Details:
{'EXIT',
 {badarg,
  [{erlang,length,
    [{badrpc,
      {'EXIT',
       {aborted,
        {bad_type,
         {badrpc,{'EXIT',{aborted,{no_exists,roster,wild_pattern}}}}}}}}],
    []},
   {mongoose_helper,count_wildpattern,1,
    [{file,"mongoose_helper.erl"},{line,159}]},
   {ct_mongoose_hook,generic_via_mongoose_helper,1,
    [{file,"src/ct_mongoose_hook.erl"},{line,191}]},
   {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
   {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
   {ct_mongoose_hook,check_server_purity,2,
    [{file,"src/ct_mongoose_hook.erl"},{line,120}]},
   {ct_mongoose_hook,post_end_per_suite,4,
    [{file,"src/ct_mongoose_hook.erl"},{line,66}]},
   {ct_hooks,catch_apply,3,[{file,"ct_hooks.erl"},{line,424}]}]}}
Testing ejabberd_tests.tests.conf_reload_SUITE: TEST COMPLETE, 4 ok, 0 failed of 4 test cases
```

please, don't force me to fix all of this in one PR, it will be a monster thing.

**Comment by arcusfelis** [comment]
Ah, another thing, why this function is not in escalus: once something gets into escalus, it stays there.
Because it's used by our clients.
But mongoose_helper is very easy to refactor.

**Comment by fenek** [comment]
I think that RPC usage deserves a separate discussion. The scope of this PR is to fix the problem with calls to undefined functions.

**Comment by arcusfelis** [comment]
mam_helper:rpc_apply/3 has the same semantics.
But I don't want to call mam_helper from non-mam code :D

**Pull request merged**
