### PR TITLE
Fix flaky sm tests by making sid's unique

### PR DESCRIPTION
**Pull request by chrzaszcz**
Sid's should be created for different Pids - otherwise the timestamp alone does not guarantee uniqueness.

The sm tests started failing on fast machines, which could generate a lot of sid's in a single microsecond. On Apple M1 the small tests were failing all the time.

To fix this, spawn a new process when generating a sid in the tests. Forward incoming messages to the test process, because some tests need to check them.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/188016) / elasticsearch_and_cassandra_mnesia / 9120f138de38d0fbcf4fdee00144a7733333e658
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4103/188016/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4103/188016/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4085d385f7550f.2023-08-16_17.27.36/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/188036) / elasticsearch_and_cassandra_mnesia / ffa62128e9dae51494c2e57c09d2c90e36f42f41
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4103/188036/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4103/188036/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%405ff22883dd7b.2023-08-16_17.28.49/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/188137) / elasticsearch_and_cassandra_mnesia / 8b6f4943e47c44fcf51a1a98ea6da87a6bb55b54
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4103/188137/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4103/188137/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4004ec8eaa87cd.2023-08-17_07.42.09/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
I just checked that `erlang:monotonic_time/X` doesn't have a _strictly_ increasing mode, so it can still generate repeated values ☹️ So yeah, there's no simpler way. This fix is cool, actually a very smart move with the `start_link` 👌🏽

**Pull request merged**
