### PR TITLE
Release MongooseIM 6.3.1

### PR DESCRIPTION
**Pull request by jacekwegr**
## Highlights
- Better certificate validation
- Improved CockroachDB support
- Removed unnecessary components
- Multiple owner support in MUC Light
- Packages are now published on GitHub
- Various improvements and fixes

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252786) / elasticsearch_and_cassandra_mnesia / c74177a18cc50b813289476e33c7ff3706a4beec
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4448/252786/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4448/252786/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40da5348bdcef0.2024-12-24_11.02.33/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/253298) / elasticsearch_and_cassandra_mnesia / dec35dde84f7d78839a8095ac4b9cf655d54a0a8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4448/253298/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4448/253298/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4049db41b4a748.2024-12-30_10.53.05/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/253371) / elasticsearch_and_cassandra_mnesia / 8ee27ad74249d884934d48bddf7d61e6bd569fdd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4448/253371/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4448/253371/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%409098ac5099dc.2024-12-30_11.51.17/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
looks good

**Pull request merged**
