### PR TITLE
Upgrade test dependencies

### PR DESCRIPTION
**Pull request by NelsonVides**
Just upgrading test dependencies

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218013) / elasticsearch_and_cassandra_mnesia / 696e70bd5b9700bf2a03318259804817c640e0fa
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4275/218013/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4275/218013/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40df2f4b0fd870.2024-05-06_08.17.43/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218044) / elasticsearch_and_cassandra_mnesia / ed45504c1889739a3e73bae8f77df58cbf6aa30c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4275/218044/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4275/218044/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%407a4407cbfda8.2024-05-06_11.29.18/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218077) / elasticsearch_and_cassandra_mnesia / a3887615daa13cc3ed14bc1234bd6d1bcc656c0b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4275/218077/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4275/218077/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40acb24c1ecdf5.2024-05-06_15.09.59/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by gustawlippa — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
