### PR TITLE
c2s/features optimisations

### PR DESCRIPTION
**Pull request by NelsonVides**
A couple of small code shuffles, to make parameters simpler and having the c2s_data state in the features hook.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/186714) / elasticsearch_and_cassandra_mnesia / 913e3b2bc03783f514a44fa612dbb40898b238c2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4094/186714/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4094/186714/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40bcfc5993df4b.2023-08-11_09.46.50/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186744) / small_tests / 0c0ab938a40cc509370be29e51c1c396d3c85d58
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4094/186744/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4094/186744/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-11_10.14.58/lib.mongooseim.logs/run.2023-08-11_10.14.58/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/187269) / small_tests / 0799c1460fabe1e8ead3784e20fc59cb072d4f19
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4094/187269/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4094/187269/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-14_07.27.43/lib.mongooseim.logs/run.2023-08-14_07.27.43/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187373) / elasticsearch_and_cassandra_mnesia / c8a770359d4eda77a160eb087b320c15e975a693
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4094/187373/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4094/187373/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40639365c0ef4b.2023-08-14_08.26.38/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/187438) / small_tests / 73bda741ce1661d334067a971f47fb64f32fd848
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4094/187438/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4094/187438/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-14_10.15.15/lib.mongooseim.logs/run.2023-08-14_10.15.16/suite.log.html)

**Review by arcusfelis — COMMENTED** [review]
ok

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
