### PR TITLE
Rename MAM modules

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to make MAM module naming more intuitive.

- `mod_mam` is renamed to `mod_mam_pm`, because it is a PM-specific module, just as `mod_mam_muc` is a MUC-specific one.
- `mod_mam_meta` is renamed to `mod_mam`, because no other modules have this unexpected suffix, and it is more intuitive when the main module is just named after the functionality.

GitHub does not recognize the renaming because types were left in `mod_mam` (they affect PM and MUC), but you can look at the individual commits, and see that the changes were quite mechanical - the diff is very straightforward for the first two commits. 

There are no functional changes in this PR.

The `mod_mam_*` backends are **not** renamed to `mod_mam_pm_*` in this PR - if needed, we can do it in a separate task.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127035) / small_tests / 3facead2ddb21e15df6eb5bc0f174758556f87a9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127035/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127035/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-14_13.54.31/lib.mongooseim.logs/run.2022-06-14_13.54.31/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127060) / small_tests / ae1e8808755e72ca118eb49f3fa15e7d7884bb07
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127060/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127060/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-14_13.56.51/lib.mongooseim.logs/run.2022-06-14_13.56.52/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127189) / small_tests / c5604ab3b98659a3f4bdb120202a317c911e95c5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127189/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127189/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_07.47.04/lib.mongooseim.logs/run.2022-06-15_07.47.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127288) / small_tests / a3cba8bcf19969a00a453608ba6a4a4fc799cf6a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127288/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127288/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_12.07.55/lib.mongooseim.logs/run.2022-06-15_12.07.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127312) / small_tests / b4411394944cc31ec6c1ed013f27b7bd5239757a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127312/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127312/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_12.14.19/lib.mongooseim.logs/run.2022-06-15_12.14.19/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127340) / small_tests / 66efc03e28c41b385c32f737f8095660783ff8ee
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127340/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127340/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_12.18.52/lib.mongooseim.logs/run.2022-06-15_12.18.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127367) / small_tests / 91a3ac5505f31576e8e16ff51cd73b67503858df
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127367/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127367/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_12.41.24/lib.mongooseim.logs/run.2022-06-15_12.41.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127391) / small_tests / edae314e896a2e60827840d77deddc7efa91ca39
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127391/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127391/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_13.09.39/lib.mongooseim.logs/run.2022-06-15_13.09.39/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127419) / small_tests / 0b8923a9698fcc605e1aab74085eb42908165e1d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127419/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127419/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_13.27.18/lib.mongooseim.logs/run.2022-06-15_13.27.19/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127444) / small_tests / e389d71b3a1c1640e31a95b410ef401ab34f8801
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127444/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127444/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_13.59.27/lib.mongooseim.logs/run.2022-06-15_13.59.28/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/127466) / small_tests / 70796b88107750eb67601f4d0540995fd721760e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3684/127466/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3684/127466/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-15_14.18.17/lib.mongooseim.logs/run.2022-06-15_14.18.17/suite.log.html)

**Review by Premwoik — APPROVED** [review]
Looks good to me :)

**Pull request merged**
