### PR TITLE
Adding support for http calling of the graphql_server commands

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
Adding the method(HTTP or CLI) to graphQL context is being passed to the execute function.
Based on this added variable in context, the execution of server commands is different for HTTP calls and CLI calls.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142088) / small_tests / 8d1d3032a35e40284800d807dc69e883ed752561
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/142088/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/142088/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_06.42.25/lib.mongooseim.logs/run.2022-10-05_06.42.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142735) / small_tests / 297677f200a12c4d8f3df86dfb7f787b498aa90c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/142735/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/142735/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_07.01.27/lib.mongooseim.logs/run.2022-10-07_07.01.27/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142762) / small_tests / 30b1ee6e7086680d8639950762d174016dee3e5c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/142762/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/142762/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_07.48.10/lib.mongooseim.logs/run.2022-10-07_07.48.10/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142814) / small_tests / daa4ca68475b492dcf383f6a2ececbd95e48e11e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/142814/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/142814/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_08.22.30/lib.mongooseim.logs/run.2022-10-07_08.22.30/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142871) / small_tests / 782edc31cc591fa6fe484e2c9928841d9cf5abbf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/142871/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/142871/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_08.57.22/lib.mongooseim.logs/run.2022-10-07_08.57.23/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/143107) / small_tests / 0707398200023a4713ba927db8a7e4cb6510ae76
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/143107/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/143107/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-10_07.24.17/lib.mongooseim.logs/run.2022-10-10_07.24.18/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/143456) / small_tests / b950a86a4d643c7bf5c4ad178581ce2d32e77d2a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/143456/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/143456/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-11_10.14.26/lib.mongooseim.logs/run.2022-10-11_10.14.27/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/143748) / small_tests / f0ee4f0c47ed13c8c0c311553ed50d2ab5d43e3a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3793/143748/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3793/143748/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-12_07.14.51/lib.mongooseim.logs/run.2022-10-12_07.14.52/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good :+1:

**Pull request merged**
