### PR TITLE
Fix the issue with max_stanza_size

### PR DESCRIPTION
**Pull request by chrzaszcz**
The limit worked partially - only if the input was chunked, and not working properly for small limits. For websockets it wasn't working at all as reported in https://github.com/esl/MongooseIM/issues/4193.

The main fix is in the C++ code in `exml`: https://github.com/esl/exml/pull/68
This PR also uses a fix for `escalus` - I discovered an issue when adding a new test: https://github.com/esl/escalus/pull/261

These two PR's should be merged first. Then we could release them in hex, and update this PR.

**Note:** Latest escalus does not work with big tests anymore after merging https://github.com/esl/escalus/pull/259, and this needs a fix before releasing the hex package.

---

Recommended to do in the future:
- Add tests for the opening `stream` tag name verification in both regular C2S and websockets.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/204248) / elasticsearch_and_cassandra_mnesia / ba8a7a33b5e364b74623b633ffaabbf15e2581a4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4197/204248/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4197/204248/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4010f714834b87.2023-12-21_20.43.42/index.html)
**OK: 370** / Failed: 0 / **User-skipped: 40** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/204289) / elasticsearch_and_cassandra_mnesia / 486f6045f63d427ae7de12b47b304d4576feb930
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4197/204289/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4197/204289/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40551d4bf7f4a7.2023-12-21_21.26.29/index.html)
**OK: 370** / Failed: 0 / **User-skipped: 40** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
Pushed the latest escalus and exml packages together with fixes to the jid record problem. Now it looks perfect to me 👌🏽

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/204426) / elasticsearch_and_cassandra_mnesia / 309fb47eb01ecd1134a74f15884848de232022c2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4197/204426/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4197/204426/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%405d8c16aaec24.2023-12-22_16.35.12/index.html)
**OK: 370** / Failed: 0 / **User-skipped: 40** / Auto-skipped: 0

**Review by chrzaszcz — COMMENTED** [review]
Looks all good to me, nice to see the includes fixed, it was easier than I thought. I saw two test suites, but it turned out these were the only two :wink:
From my side it can be merged :+1:

**Pull request merged**
