### PR TITLE
[skip ci] Reference about store_groupchat_messages option in mod_offline added

### PR DESCRIPTION
**Pull request by antivista**
This PR adds documentation for mod_offline, regarding the option store_groupchat_messages. [#2879](https://github.com/esl/MongooseIM/issues/2879)

### CODE REVIEW

**Review by DenysGonchar — CHANGES_REQUESTED** [review]
Thanks for PR. historically there are several reasons why `store_groupchat_messages` option is not documented:

1. XEP-0160 doesn't specify this functionality,  because the classic MUC even doesn't send the messages to offline users. 
2. As this will not work as expected with the classic MUC, the option makes sense only with MUC-light.
3. XEP-0160 is not recommended way of storing offline messages (especially group-chat messages), better use message archive with [MUC storage enabled](https://esl.github.io/MongooseDocs/latest/modules/mod_mam/#enable-muc-message-archive).

So this option is rather confusing than brings any benefit, it's kept for compatibility reasons.

So let's either keep it not documented or fully document it.

**Comment by antivista** [comment]
Although the use of `mod_mam` is the better approach in most of the cases, client side requires more effort (compared with XEP-0160) to implement XEP-0313, so I have thought that to document this option could be good in these scenarios:
- As a momentary alternative waiting the XEP-0313 implementation client side; 
- If it is expected the use of just one client per user and when a message is delivered (for some reason) we do not want allow the rescue of that message again, to do this with `mod_mam` should require more work because XEP-0313 does not foresee a mechanism of message deletion except for the older messages in the archive.

If these scenarios are considered of interest, I can try to fully document, referring to explicitly to MUC-light case as DenysGonchar rightly pointed out to me.

**Review by antivista — COMMENTED** [review]
I hope that it is adequately documented now.

**Review by NelsonVides — APPROVED** [review]
Fine by me 👍🏽

**Review by DenysGonchar — APPROVED** [review]
👍

**Pull request merged**
