### PR TITLE
shotgun 0.5.0

### PR DESCRIPTION
**Pull request by vkatsuba**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/66110) / small_tests / 6760ae5e78de3bde63e8f6b95cb1d89d8f81e075
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3206/66110/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3206/66110/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-02_19.33.00/lib.mongooseim.logs/run.2021-08-02_19.33.01/suite.log.html)

**Comment by vkatsuba** [comment]
[GHA](https://github.com/esl/MongooseIM/actions/runs/1091470870)

**Review by NelsonVides — APPROVED** [review]
Perfect 👍🏽

**Review by arcusfelis — COMMENTED** [review]
good

**Pull request merged**
