### PR TITLE
Move the docker repo to the 'erlangsolutions' organization

### PR DESCRIPTION
**Pull request by chrzaszcz**
We are moving the docker image from [mongooseim/mongooseim](https://hub.docker.com/repository/docker/mongooseim/mongooseim/general) (free tier) to [erlangsolutions/mongooseim](https://hub.docker.com/repository/docker/erlangsolutions/mongooseim/general) (paid tier).

`DOCKERHUB_REPO` was used to name the organization. `DOCKERHUB_ORG` is now used instead, which is already set in CircleCI to `erlangsolutions`.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/237294) / elasticsearch_and_cassandra_mnesia / 0a4d5e65dcb4e78fb020b84132af5132d2922dc3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/237294/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4372/237294/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big/ct_run.test%4024e73961b566.2024-09-06_14.20.21/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/237375) / elasticsearch_and_cassandra_mnesia / 8e7d622f7ed72b596f49e5dc74857326c1f40a18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/237375/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4372/237375/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big/ct_run.test%402178b4247d85.2024-09-06_15.15.36/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/237848) / elasticsearch_and_cassandra_mnesia / ebb1eb4791766c34908c04806b598829fe56b484
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/237848/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/237848/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%40084198db989e.2024-09-12_14.49.58/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238136) / elasticsearch_and_cassandra_mnesia / 61956bfe7f4e547cfcc0a1b9abe6de46bb8b3a3a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238136/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238136/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%40b0388f84aa90.2024-09-17_07.25.06/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238253) / elasticsearch_and_cassandra_mnesia / afa9177e97905c02a592cd5dcabf15191ae77ac0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238253/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238253/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%40f7edaeab423e.2024-09-18_07.17.27/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238275) / elasticsearch_and_cassandra_mnesia / 15643e7fc13e80013060e8ac875270b54527e16f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238275/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238275/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%4023cb3485138b.2024-09-18_08.28.07/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238393) / elasticsearch_and_cassandra_mnesia / c7b5bf1554de0cd500945e464870882849c34c21
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238393/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238393/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%40a0c9fc60c443.2024-09-18_12.26.02/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238427) / elasticsearch_and_cassandra_mnesia / 1463d379a07e8b755e81431b4f9c2b6317f40b6c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238427/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238427/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%4061e60a276dcc.2024-09-18_12.32.32/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/238593) / elasticsearch_and_cassandra_mnesia / 168e2f2c3eeee4b3391be13ea6c21080212a810f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4372/238593/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4372/238593/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%4055a88bb35c59.2024-09-19_06.48.23/index.html)
**OK: 461** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
