### PR TITLE
Fix mam flaky tests

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
Fixing mam flaky tests

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_25](https://circleci.com/gh/esl/MongooseIM/227527) / small_tests / 715e1afe3ee1e3926b38b3718e9bc49b17b0acea
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4321/227527/small_tests.25.3.2.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4321/227527/small_tests.25.3.2.9-amd64/small/ct_run.mongooseim@localhost.2024-07-11_06.27.38/lib.mongooseim.logs/run.2024-07-11_06.27.38/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/227570) / elasticsearch_and_cassandra_mnesia / f079d7ad8107fe21a4d906c2c8a9d194033c5a3e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4321/227570/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4321/227570/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%403173a5d2b8b9.2024-07-11_07.02.17/index.html)
**OK: 583** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_25](https://circleci.com/gh/esl/MongooseIM/227596) / small_tests / 4b887df90839bc9ff02a039014d38f427b3bc412
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4321/227596/small_tests.25.3.2.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4321/227596/small_tests.25.3.2.9-amd64/small/ct_run.mongooseim@localhost.2024-07-11_07.42.24/lib.mongooseim.logs/run.2024-07-11_07.42.25/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/227676) / elasticsearch_and_cassandra_mnesia / cc58dfc125811d36dd3c60bd1df74b1e0692df8e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4321/227676/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4321/227676/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4014d831bd24be.2024-07-11_09.45.59/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
Looks good 👌

**Pull request merged**
