### PR TITLE
Add package signing script to the CI pipeline

### PR DESCRIPTION
**Pull request by jacekwegr**
### Summary  
This PR adds package signing to the CI pipeline within the Docker containers used for building. It also updates the previously used signing tool for `.deb` packages.

---

### Key Changes  

1. **Package Signing**  
   - Adds a script to sign packages immediately after they are built in Docker, but before running smoke tests, to confirm that the packages remain functional after signing.
   - The script adapts to the package type, using appropriate signing tools.

2. **Switch to `debsigs` for `.deb` Package Signing**  
   - Replaces `dpkg-sig` with `debsigs` as the signing tool for `.deb` packages.  
   - **Why the change?**
     - `dpkg-sig` does not support the `zstd` compression standard, is unavailable on Debian >= 12 and Ubuntu >= 23.10 and appears to be no longer maintained.  
     - `debsigs` supports `zstd`, is actively maintained and is compatible with newer Ubuntu/Debian versions.  
   - **Compatibility Workaround:**  
     - `debsigs` requires a workaround for older Ubuntu/Debian versions (we need version >0.2 to use `--gpgopts` option). A similar workaround would also be required for `dpkg-sig` to work with newer versions, making `debsigs` the better long-term choice.

3. **Environment Variables**  
   - Adds the following environment variables in CircleCI to handle GPG keys:  
     - `GPG_PUBLIC_KEY`  
     - `GPG_PRIVATE_KEY`  
     - `GPG_PASS`  
   - Both public and private keys are base64-encoded, allowing them to be stored and passed as single-line values. This avoids issues with multi-line keys.  
   - These variables are passed to Docker via secret mounts. To enable this feature, the line `# syntax=docker/dockerfile:1` was added to the Dockerfile to use the latest Dockerfile syntax.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/241875) / elasticsearch_and_cassandra_mnesia / f7e1e5aad2e654bfbfd1450c7aff047abedb603d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/241875/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/241875/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%405483b5d0f0d4.2024-11-15_09.15.01/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/241950) / elasticsearch_and_cassandra_mnesia / 505f3446194eb60b1ee4af32bf9409564d6994b5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/241950/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/241950/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%408379514b5249.2024-11-15_14.20.14/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242001) / elasticsearch_and_cassandra_mnesia / 261c98527c38519b4983b59af75ce89b522ca54a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242001/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242001/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%403eff63ff9104.2024-11-15_15.22.10/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242270) / elasticsearch_and_cassandra_mnesia / ccd45c00896af0772847d89648a03c2e95e4b730
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242270/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242270/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%405ee33c9dfc4d.2024-11-20_08.30.18/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242429) / elasticsearch_and_cassandra_mnesia / cf287d7c96f387c730b2bd6c48263e45957ce479
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242429/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242429/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40cf134182e8eb.2024-11-20_09.31.40/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242514) / elasticsearch_and_cassandra_mnesia / edcf6aaccae9fb9fcaaef3294f9fd9c6725fef29
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242514/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242514/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%402e85491c6e1e.2024-11-20_13.31.23/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242587) / elasticsearch_and_cassandra_mnesia / 8a63e0bdafc370d2d22d75d3f40bc88bd81886dc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242587/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242587/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4013342ca5d0fe.2024-11-21_12.11.10/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242622) / elasticsearch_and_cassandra_mnesia / b62815a7723c00707e2ceecf9d582fd4ba9069eb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242622/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242622/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40e0bf39f1a0cc.2024-11-21_12.30.43/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242658) / elasticsearch_and_cassandra_mnesia / c4c541a8e70e15d09fd0b597e810f81326339151
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242658/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242658/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4042b9a3ff3133.2024-11-21_12.53.35/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242701) / elasticsearch_and_cassandra_mnesia / 0a1aa084e361dce5249206071369d9b896a58fa1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242701/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242701/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40a163abd194b8.2024-11-21_14.04.52/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242818) / elasticsearch_and_cassandra_mnesia / 06a1b70c1cab149c0a1258aa0e6448b277fcfc27
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/242818/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/242818/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%407ecd7e7e6b7f.2024-11-21_15.32.56/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/243349) / elasticsearch_and_cassandra_mnesia / 29a7cdb4fcee0ee5b55c2aa1967149846f671608
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/243349/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/243349/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40a00e101ef829.2024-11-28_10.01.39/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/243470) / elasticsearch_and_cassandra_mnesia / 290aaec1aa68e310d1e873c1a16a81195c9f22ed
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4399/243470/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4399/243470/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40d32a799669e3.2024-11-28_11.22.23/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
Looks good, I like the usage of secrets 👍

**Pull request merged**
