### PR TITLE
Instrument/test prometheus endpoint

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to add tests for the metrics exposed using the Prometheus endpoint with [prometheus-cowboy](https://github.com/deadtrickster/prometheus-cowboy).

Make sure that the metric doc is well-formed, and that the expected metrics are exposed in the correct format.

**Also:** fix an issue with unexpected implicit conversion of time units when a metric name ends with a suffix like `_seconds`. This case is covered by the newly added tests.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/231688) / elasticsearch_and_cassandra_mnesia / 50e90dde2a9222402bd1b8e8abe593c4fbac3cd0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/231688/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/231688/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%401bb7155bcc29.2024-07-25_13.15.37/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232037) / elasticsearch_and_cassandra_mnesia / bd3d1cf4774c0d0a9d4a2daacd2da271bb3f4c96
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232037/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232037/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4019e1c698e7dc.2024-07-25_14.38.43/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232060) / elasticsearch_and_cassandra_mnesia / 93c485ead2d16dc00bece504c9c0ea24b49092b6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232060/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232060/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40a7aadc840ff2.2024-07-25_14.40.46/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232539) / elasticsearch_and_cassandra_mnesia / 8d79b83506a113ea6454e619e98e9a30e5624d0d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232539/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232539/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%406bd5578b1eed.2024-07-26_10.22.49/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232614) / elasticsearch_and_cassandra_mnesia / 76f6a55270586a64771dd188b70fc0db34f66586
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232614/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232614/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40542ef611996b.2024-07-26_11.06.28/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232754) / elasticsearch_and_cassandra_mnesia / 97a053ef061f2eebf7744925f6d3ecf2963080b6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232754/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232754/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40a40a38410ece.2024-07-26_12.12.54/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/232840) / elasticsearch_and_cassandra_mnesia / 86efd89039a847161efdddc07d63a1d6374ab19a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4335/232840/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4335/232840/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4072623d86095f.2024-07-26_12.37.33/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 45** / Auto-skipped: 0

**Review by jacekwegr — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
