### PR TITLE
fix crash on bad xml input

### LINKED ISSUE #564: crash on bad XML input
When sending bad data (non XML) on the stream we see a crash now instead of returning a stream error:

```
2015-10-28 15:32:51.771 [error] <0.677.0> gen_server <0.677.0> terminated with reason: no match of right hand value {error,{"syntax error",<<"asdfasdf\r\n">>}} in ejabberd_receiver:process_data/2 line 328
2015-10-28 15:32:51.771 [error] <0.677.0> CRASH REPORT Process <0.677.0> with 0 neighbours exited with reason: no match of right hand value {error,{"syntax error",<<"asdfasdf\r\n">>}} in ejabberd_receiver:process_data/2 line 328 in gen_server:terminate/7 line 804
2015-10-28 15:32:51.771 [error] <0.293.0> Supervisor ejabberd_receiver_sup had child undefined started with {ejabberd_receiver,start_link,undefined} at <0.677.0> exit with reason no match of right hand value {error,{"syntax error",<<"asdfasdf\r\n">>}} in ejabberd_receiver:process_data/2 line 328 in context child_terminated
```

Expected behaviour: Return stream error, then close connection.
```
<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='1609254289' from='chat.sqor.com' version='1.0'><stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error></stream:stream>
```

Actual behaviour: Connection is being closed.

Probably bug got introduced when switching to exml.
https://github.com/esl/MongooseIM/blame/master/apps/ejabberd/src/ejabberd_receiver.erl#L328

### PR DESCRIPTION
**Pull request by sstrigler**
fixes #564

### CODE REVIEW

**Comment by michalwski** [comment]
Thanks for the change. Would perfect if you could write a test case showing there was a problem before and now it's fixed.

**Comment by sstrigler** [comment]
Oh, lol, of course. Not my day. I knew I had forgotten sth. Would have been too easy :p

**Comment by sstrigler** [comment]
And suddenly a rogue testcase appeared.
[ ] continue
[ ] integration

**Comment by michalwski** [comment]
Hmm, still the error case is not covered somehow. Take a look here: https://coveralls.io/builds/3999189/source?filename=apps%2Fejabberd%2Fsrc%2Fejabberd_receiver.erl#L336

**Comment by sstrigler** [comment]
*facepalm*

**Comment by michalwski** [comment]
Thanks @sstrigler :)

**Pull request merged**
