### PR TITLE
Added image about accumulator's lifecycle

### PR DESCRIPTION
**Pull request by bartekgorny**
Only some visual documentation, hopefully makes clear what the accumulator actually carries.

### CODE REVIEW

**Comment by fenek** [comment]
Won't updating it be a real hell? I think it's better to embed a PNG image. And attach some source file, editable with a free/open tool.

**Comment by fenek** [comment]
Is it a Monodraw file? If so, then it's not free for sure. :)

**Comment by fenek** [comment]
To update after acc refactor, with different (free) diagram tool.

**Comment by michalwski** [comment]
I'm closing this one since it's too old and out of date.

**Pull request closed without merging**
