### PR TITLE
Ensure that check_for_updates_tref is set

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses MIM-1472

Proposed changes include:
* Typo in check_for_updates_tref

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/68017) / small_tests / a548249e1ae8cb9b7cd03f41c82151796c226c12
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3225/68017/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3225/68017/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-20_08.58.18/lib.mongooseim.logs/run.2021-08-20_08.58.19/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/68107) / small_tests / 5dd2c6ee4dac7efc127d1d4fbfb533d633811fc6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3225/68107/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3225/68107/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-20_10.29.52/lib.mongooseim.logs/run.2021-08-20_10.29.53/suite.log.html)

**Review by vkatsuba — APPROVED** [review]

**Review by chrzaszcz — APPROVED** [review]
Load tested, it works correctly.

**Pull request merged**
