### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by gustawlippa**
This is a follow up for #3259. The links to images in the index.md file got broken while moving files around, but worked locally for me for some reason, so I didn't notice. This fixes the issue.

### CODE REVIEW

**Review by vkatsuba — COMMENTED** [review]
Do you check also:
* `doc/migrations/3.6.0_3.7.0.md`
* `doc/migrations/3.7.0_4.0.0.md`
* `doc/migrations/4.0.0_4.0.1.md`
* `doc/migrations/4.0.1_4.1.0.md`
* `doc/migrations/4.1.0_4.2.0.md`

to similar problems with links?

**Comment by gustawlippa** [comment]
I didn't move the Migrations folder, but you are right - I see there are problems with links there, so why not fix them by the way. I will push a fix in a few minutes after I review them.

**Review by vkatsuba — COMMENTED** [review]
Do you check also other documentation places where `../../` is used in links?

**Comment by gustawlippa** [comment]
Which places do you have in mind? From searching for `../../` I think this is only used in the MongoosePush tutorials, and these links are not broken.

**Comment by vkatsuba** [comment]
> Which places do you have in mind? From searching for `../../` I think this is only used in the MongoosePush tutorials, and these links are not broken.

I mean, do you check also those pages?
* `doc/tutorials/push-notifications/MongoosePush-setup.md`
* `doc/tutorials/push-notifications/Push-notifications.md`

**Comment by gustawlippa** [comment]
Yeah, sure, these were and are correct (they are a directory deeper - grouped in `tutorials/push-notifications/`).

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/74711) / small_tests / dd158cc48e116780c823ae84070b238132bab76d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3288/74711/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3288/74711/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-09-21_09.07.33/lib.mongooseim.logs/run.2021-09-21_09.07.34/suite.log.html)

**Review by vkatsuba — APPROVED** [review]

**Pull request merged**
