### PR TITLE
Put hooks into persistent_term using iterations

### PR DESCRIPTION
**Pull request by NelsonVides**
Idea about hooks and persistent term: having no batching, that is, always writing to persistent terms on every insert. This means that as adding handlers triggers replaces, startup times can potentially go more expensive (measurements in my computer):
* In master for this PR `ejabberd_app:do_startup/0` currently takes `600-650ms`.
* Using a single big persistent_term entry it takes `800-850ms`.
* Using a persistent_term entry per hook tag takes `700-750ms`.

What would you say about that? We preserve all current properties except that inserting hooks becomes linearly slower, but that anyway should only happen at startup.

Perhaps https://github.com/esl/MongooseIM/pull/3878 is preferred, needs to be discussed.

### CODE REVIEW

**Comment by NelsonVides** [comment]
To choose between this one and https://github.com/esl/MongooseIM/pull/3878

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/183520) / small_tests / 32b346879e795119bacaf8191f113b3f39617c97
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/183520/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/183520/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-01_13.22.43/lib.mongooseim.logs/run.2023-08-01_13.22.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186487) / small_tests / 449fe117a198eb0bb94ebee48b8cfb994a213c50
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/186487/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/186487/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-10_19.15.32/lib.mongooseim.logs/run.2023-08-10_19.15.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186519) / small_tests / ab30ff71abc8521e0b6ee710d449aa037a015d30
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/186519/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/186519/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-10_21.20.40/lib.mongooseim.logs/run.2023-08-10_21.20.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186561) / small_tests / ec9780b9fbf5bfa9302bbd9c14a9b5a5959fbdd2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/186561/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/186561/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-11_08.11.11/lib.mongooseim.logs/run.2023-08-11_08.11.12/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/186642) / elasticsearch_and_cassandra_mnesia / 5e36c215be27a54c20485b776846b038858d6426
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/186642/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/186642/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4016bb719b8e26.2023-08-11_09.16.59/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187335) / elasticsearch_and_cassandra_mnesia / 75729bd59f5c2f5f6e42baa3407b6f224ec8a3f9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4074/187335/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4074/187335/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4082de0236f32c.2023-08-14_07.55.22/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Pull request closed without merging**
