### PR TITLE
Refactored hook handlers in ejabberd_router module

### PR DESCRIPTION
**Pull request by pawlooss1**
This PR changes all hook handlers in `ejabberd_router` module to `gen_hook` format.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136875) / small_tests / bbb4d0930efa3555aaa1e66e6aede51d3bdeff80
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3760/136875/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3760/136875/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_09.13.58/lib.mongooseim.logs/run.2022-09-15_09.13.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136973) / small_tests / 024fe418d46f9ae64eeaf20137224c544cae056a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3760/136973/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3760/136973/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_10.43.49/lib.mongooseim.logs/run.2022-09-15_10.43.50/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Straightforward, lgtm 👌🏽

**Review by chrzaszcz — APPROVED** [review]
Looks good

**Pull request merged**
