### PR TITLE
Fix race condition when inserting into domain_event table

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses MIM-1459 "Inconsistent values in mongoose_domain_core".

Proposed changes include:
* Fix for a race condition in PgSQL when allocating IDs.

# Example

Node mim:

```erlang
f().
recon_trace:calls({mongoose_domain_sql, select_updates_from, fun(_) -> return_trace() end}, 5000, [{scope, local}]).
From = 20000.
timer:sleep(6000).
[spawn(fun() -> mongoose_domain_api:insert_domain(<<"test", (integer_to_binary(N))/binary>>, <<"test type">>) end) || N <- lists:seq(From, From + 2000, 2)].
```

Node mim2:
```erlang
f().
recon_trace:calls({mongoose_domain_sql, select_updates_from, fun(_) -> return_trace() end}, 5000, [{scope, local}]).
From = 20000.
timer:sleep(4000).
[spawn(fun() -> mongoose_domain_api:insert_domain(<<"test", (integer_to_binary(N))/binary>>, <<"test type">>) end) || N <- lists:seq(From + 1, From + 2001, 2)].
```

Do the check:

```
Nodes = [node()|nodes()].
List = [rpc:call(Node, mongoose_domain_api, get_domains_by_host_type, [<<"test type">>]) || Node <- Nodes].
[A,B|_] = List.
rp(lists:sort(A -- B)).
rp(lists:sort(B -- A)).
```

Not empty lists of difference in domains from two nodes.

# Why does it happen?

PG assigns auto increment ids outside of a transaction. So, we could have to wait for records to be committed sometimes (rarely, usually 1 second waiting would be enough, once a missing event is detected).

# What is the fix?

We check that ids we get from DB are incrementing without any gaps 1,2,3,4,5...
If a gap is detected (i.e. something like 1,2,4,5), we just wait and retry.

Domain_settings table has the same issue, but it would be triggered only at the load time, which is rare.
But what we can do is to maybe start rolling event updates not from the last event at the moment, but from an event, which is at least 10 (or 30?) seconds old.

# Alternative fix

Don't use auto-increments. Always do in a transaction:

```
SELECT max(id) + 1 FROM domain_events;
```

to get an ID for a new event. If a transaction fails - just restart it.
This could be a bit slower on insertion, but could be a cleaner solution ;) 

The alt fix would not work under intensive domain insertion rate though.

# Logging

Will print

```
when=2021-08-11T15:54:49.286084+00:00 level=warning what=wait_for_gaps pid=<0.3267.0> at=mongoose_domain_gaps:handle_gaps/1:20 gaps=[1981]
```

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/66714) / small_tests / 9bbd884faff487bf3b10660360ccc496a8af05a7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3212/66714/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3212/66714/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-10_13.38.45/lib.mongooseim.logs/run.2021-08-10_13.38.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/67043) / small_tests / f216930c7bf2235aa7337d779b8834d72604089c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3212/67043/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3212/67043/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-11_16.04.57/lib.mongooseim.logs/run.2021-08-11_16.04.57/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/67068) / small_tests / b4df6329331ea7b6ab91cf4aad571171baf178f8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3212/67068/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3212/67068/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-11_16.15.14/lib.mongooseim.logs/run.2021-08-11_16.15.14/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
The load test was successful with 100k domains which failed before, good work! However, we need to unit-test this module (without DB) and add type specs before merging to master.

Example logs from one node are shown below. The messages about user archive are unrelated. It looks reasonable to me.

`when=2021-08-12T09:15:48.565512+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[6]
when=2021-08-12T09:15:55.104485+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[2632]
when=2021-08-12T09:16:00.016613+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[4594]
when=2021-08-12T09:16:00.104778+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[4632]
when=2021-08-12T09:16:45.131800+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[22643]
when=2021-08-12T09:16:45.231552+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[22683]
when=2021-08-12T09:16:50.982405+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[24983]
when=2021-08-12T09:16:52.036602+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[25403]
when=2021-08-12T09:16:52.241614+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[25487]
when=2021-08-12T09:17:07.994298+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[31765]
when=2021-08-12T09:17:25.569511+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[38813]
when=2021-08-12T09:17:30.761902+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[40894]
when=2021-08-12T09:17:30.763536+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[40894]
when=2021-08-12T09:17:45.051502+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[46611]
when=2021-08-12T09:17:49.926691+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.927353+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.927931+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.928512+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.929109+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.929660+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.930659+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.932509+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.933515+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:49.934107+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[48559]
when=2021-08-12T09:17:53.385862+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[49945]
when=2021-08-12T09:18:04.049672+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.051057+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.051721+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.052390+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.053766+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.054951+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.056353+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:04.057098+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54210]
when=2021-08-12T09:18:05.127778+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[54641]
when=2021-08-12T09:18:19.681662+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[60463]
when=2021-08-12T09:18:20.151288+00:00 level=warning what=create_user_archive_failed reason={error,duplicate_key} pid=<0.1206.1> at=mod_mam_rdbms_user:create_user_archive/3:127 user=user_5781 server=test-domain-5781 host=localhost
when=2021-08-12T09:18:30.013969+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[64595]
when=2021-08-12T09:18:30.127042+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[64640]
when=2021-08-12T09:18:34.887982+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[66545]
when=2021-08-12T09:18:39.227392+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[68281]
when=2021-08-12T09:18:39.341420+00:00 level=error pid=<0.13928.2> at=: unstructured_log="Error in process <0.13928.2> on node 'mongooseim@ip-10-2-0-172' with exit value:\
{badarg,\
    [{erlang,length,[undefined],[{error_info,#{module => erl_erts_errors}}]},\
     {mongoose_system_metrics_collector,get_hosts_count,0,\
         [{file,\
              \"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl\"},\
          {line,42}]},\
     {mongoose_system_metrics_collector,'-collect/1-lc$^0/1-0-',1,\
         [{file,\
              \"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl\"},\
          {line,15}]},\
     {mongoose_system_metrics_collector,collect,1,\
         [{file,\
              \"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl\"},\
          {line,15}]},\
     {service_mongoose_system_metrics,'-handle_info/2-fun-0-',3,\
         [{file,\
              \"/home/circleci/app/src/system_metrics/service_mongoose_system_metrics.erl\"},\
          {line,105}]}]}\
"
09:18:39.341 [error] Error in process <0.13928.2> on node 'mongooseim@ip-10-2-0-172' with exit value:
{badarg,[{erlang,length,[undefined],[{error_info,#{module => erl_erts_errors}}]},{mongoose_system_metrics_collector,get_hosts_count,0,[{file,"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl"},{line,42}]},{mongoose_system_metrics_collector,'-collect/1-lc$^0/1-0-',1,[{file,"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl"},{line,15}]},{mongoose_system_metrics_collector,collect,1,[{file,"/home/circleci/app/src/system_metrics/mongoose_system_metrics_collector.erl"},{line,15}]},{service_mongoose_system_metrics,'-handle_info/2-fun-0-',3,[{file,"/home/circleci/app/src/system_metrics/service_mongoose_system_metrics.erl"},{line,105}]}]}
when=2021-08-12T09:18:40.032768+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[68602]
when=2021-08-12T09:18:40.076382+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[68619]
when=2021-08-12T09:18:45.228678+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[70682]
when=2021-08-12T09:18:50.105807+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[72632]
when=2021-08-12T09:18:50.107790+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[72632]
when=2021-08-12T09:18:50.109237+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[72632]
when=2021-08-12T09:18:50.274037+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[72699]
when=2021-08-12T09:19:00.057373+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[76613]
when=2021-08-12T09:19:01.226865+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[77081]
when=2021-08-12T09:19:01.227575+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[77081]
when=2021-08-12T09:19:09.339931+00:00 level=warning what=create_user_archive_failed reason={error,duplicate_key} pid=<0.28665.1> at=mod_mam_rdbms_user:create_user_archive/3:127 user=user_15931 server=test-domain-15931 host=localhost
when=2021-08-12T09:19:10.026771+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[80599]
when=2021-08-12T09:19:10.028833+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[80599]
when=2021-08-12T09:19:10.232510+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[80683]
when=2021-08-12T09:19:10.244825+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[80688]
when=2021-08-12T09:19:12.074516+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[81420]
when=2021-08-12T09:19:16.084784+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83023,83022]
when=2021-08-12T09:19:16.095064+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83028]
when=2021-08-12T09:19:16.096280+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83028]
when=2021-08-12T09:19:16.139034+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83045]
when=2021-08-12T09:19:16.139733+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83045]
when=2021-08-12T09:19:16.140299+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83045]
when=2021-08-12T09:19:16.141660+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83045]
when=2021-08-12T09:19:16.321630+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:16.322432+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:16.324286+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:16.327071+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:16.328987+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:16.329738+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83119]
when=2021-08-12T09:19:17.610767+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[83630]
when=2021-08-12T09:19:20.202380+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[84669]
when=2021-08-12T09:19:27.749079+00:00 level=warning what=create_user_archive_failed reason={error,duplicate_key} pid=<0.6233.2> at=mod_mam_rdbms_user:create_user_archive/3:127 user=user_69561 server=test-domain-69561 host=localhost
when=2021-08-12T09:19:30.149928+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[88649]
when=2021-08-12T09:19:30.151266+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[88649]
when=2021-08-12T09:19:30.159851+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[88653]
when=2021-08-12T09:19:32.769193+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[89698]
when=2021-08-12T09:19:36.742335+00:00 level=warning what=create_user_archive_failed reason={error,duplicate_key} pid=<0.11987.2> at=mod_mam_rdbms_user:create_user_archive/3:127 user=user_21491 server=test-domain-21491 host=localhost
when=2021-08-12T09:19:40.035952+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[92598]
when=2021-08-12T09:19:42.277611+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93489]
when=2021-08-12T09:19:42.280978+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93494]
when=2021-08-12T09:19:42.282318+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93494]
when=2021-08-12T09:19:42.283089+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93494]
when=2021-08-12T09:19:42.284025+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93494]
when=2021-08-12T09:19:42.296254+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93502]
when=2021-08-12T09:19:42.405836+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.406768+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.408323+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.409691+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.411037+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.412896+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93547]
when=2021-08-12T09:19:42.433825+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93558]
when=2021-08-12T09:19:42.464812+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93562]
when=2021-08-12T09:19:42.876197+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93739]
when=2021-08-12T09:19:42.877071+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93739]
when=2021-08-12T09:19:42.879029+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93739]
when=2021-08-12T09:19:42.879990+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93739]
when=2021-08-12T09:19:42.880692+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[93739]
when=2021-08-12T09:19:43.657200+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.658585+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.659359+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.659968+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.660706+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.661961+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.665718+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.673055+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94049]
when=2021-08-12T09:19:43.868299+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.875378+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.877256+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.879683+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.882345+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.884262+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94134]
when=2021-08-12T09:19:43.935938+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94162]
when=2021-08-12T09:19:43.940787+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94162]
when=2021-08-12T09:19:43.943470+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94162]
when=2021-08-12T09:19:44.120599+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94236]
when=2021-08-12T09:19:45.053571+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94611]
when=2021-08-12T09:19:45.887068+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94945]
when=2021-08-12T09:19:45.975333+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[94980]
when=2021-08-12T09:19:46.033131+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[95003]
when=2021-08-12T09:19:46.033863+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[95003]
when=2021-08-12T09:19:46.034437+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[95003]
when=2021-08-12T09:19:46.035555+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[95003]
when=2021-08-12T09:19:50.365553+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.369000+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.369943+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.370752+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.373338+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.377331+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96736]
when=2021-08-12T09:19:50.440528+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96766]
when=2021-08-12T09:19:50.443672+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96766]
when=2021-08-12T09:19:50.991951+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[96987]
when=2021-08-12T09:19:52.819048+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[97717]
when=2021-08-12T09:19:56.548660+00:00 level=warning what=wait_for_gaps pid=<0.653.0> at=mongoose_domain_gaps:handle_gaps/1:56 gaps=[99210]`

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/67245) / small_tests / dd8815b18771906bf0e1ec02237e71c81f413a68
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3212/67245/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3212/67245/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-12_12.49.24/lib.mongooseim.logs/run.2021-08-12_12.49.24/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
The code looks good and I load-tested it again, everything works.

**Pull request merged**
