### PR TITLE
Improve error handling in vcard

### PR DESCRIPTION
**Pull request by kamilwaz**
Improve error handling in vcard

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/156164) / small_tests / f6346b2e1da3a2c097431df46f60462f14c5ab56
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3890/156164/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3890/156164/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-06_09.33.24/lib.mongooseim.logs/run.2022-12-06_09.33.25/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
It looks good in general, I just found the following minor issues.


JID is not converted to binary in error messages:
```
$ _build/mim1/rel/mongooseim/bin/mongooseimctl vcard getVcard --user alic@localhosta
{
  "errors" : [
    {
      "path" : [
        "vcard",
        "getVcard"
      ],
      "message" : "User's domain does not exist",
      "extensions" : {
        "user" : "{jid,<<\"alic\">>,<<\"localhosta\">>,<<>>}",
        "code" : "user_not_found"
      }
    }
  ],
  "data" : {
    "vcard" : {
      "getVcard" : null
    }
  }
}

```

Passing a list instead of a map results in a crash:
```
$ _build/mim1/rel/mongooseim/bin/mongooseimctl vcard setVcard --user alice@localhost --vcard '{"formattedName":"Alice", "nameComponents":[]}'
Failed RPC connection to the node mongooseim@localhost: {'EXIT',
                                                         {function_clause,
                                                          [{graphql_err,
                                                            type_check_err_msg,
                                                            [{type_mismatch,
                                                              #{document => [],
                                                                schmema =>
                                                                 {input_object_type,
                                                                  <<"NameComponentsInput">>,
                                                                  <<"No description provided">>,
                                                                  [],
                                                                  #{<<"family">> =>
                                                                     {schema_arg,
                                                                      <<"String">>,
                                                                      undefined,
                                                                      <<"User's family name">>,
                                                                      []},
                                                                    <<"givenName">> =>
                                                                     {schema_arg,
                                                                      <<"String">>,
                                                                      undefined,
                                                                      <<"User's name">>,
                                                                      []},
                                                                    <<"middleName">> =>
                                                                     {schema_arg,
                                                                      <<"String">>,
                                                                      undefined,
                                                                      <<"User's middle name">>,
                                                                      []},
                                                                    <<"prefix">> =>
                                                                     {schema_arg,
                                                                      <<"String">>,
                                                                      undefined,
                                                                      <<"Prefix to the name">>,
                                                                      []},
                                                                    <<"suffix">> =>
                                                                     {schema_arg,
                                                                      <<"String">>,
                                                                      undefined,
                                                                      <<"Suffix to the name">>,
                                                                      []}}}}}],
                                                            [{file,
                                                              "/home/lth/dev/mongoose/_build/default/lib/graphql/src/graphql_err.erl"},
                                                             {line,231}]},
                                                           {graphql_err,
                                                            format_errors_,2,
                                                            [{file,
                                                              "/home/lth/dev/mongoose/_build/default/lib/graphql/src/graphql_err.erl"},
                                                             {line,74}]},
                                                           {mongoose_graphql_errors,
                                                            format_error,1,
                                                            [{file,
                                                              "/home/lth/dev/mongoose/src/graphql/mongoose_graphql_errors.erl"},
                                                             {line,45}]},
                                                           {ejabberd_ctl,
                                                            handle_graphql_result,
                                                            1,
                                                            [{file,
                                                              "/home/lth/dev/mongoose/src/ejabberd_ctl.erl"},
                                                             {line,253}]},
                                                           {ejabberd_ctl,
                                                            process,1,[]}]}}
```

**Comment by kamilwaz** [comment]
The second error will be fixed here: esl/graphql-erlang#3.

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/156302) / small_tests / f1fdc675225444e0c2078c05b79d7efaa7603462
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3890/156302/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3890/156302/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-07_08.54.24/lib.mongooseim.logs/run.2022-12-07_08.54.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/156409) / small_tests / 69a7261a0d97900c5d7cdc3c6f271999a82f32b9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3890/156409/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3890/156409/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-07_09.53.20/lib.mongooseim.logs/run.2022-12-07_09.53.21/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
All good :ok_hand:

**Pull request merged**
