### PR TITLE
GDPR retrieve roster (clean)

### PR DESCRIPTION
**Pull request by fenek**
This PR supersedes #2281

It adds roster retrieval for GDPR.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[6367.1](https://travis-ci.org/esl/MongooseIM/jobs/524636503) / Erlang 19.3 / small_tests / 0d0721eed2663cd6d97054b849aec27124fdcc0e
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6367/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6367/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-04-25_20.02.36/lib.mongooseim.logs/run.2019-04-25_20.02.37/suite.log.html)

**Comment by mongoose-im** [comment]
[6374.1](https://travis-ci.org/esl/MongooseIM/jobs/524811768) / Erlang 19.3 / small_tests / 2b7e6e7e9fb96f653340e715793f2edf5a1ba3f1
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6374/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6374/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-04-26_08.57.16/lib.mongooseim.logs/run.2019-04-26_08.57.17/suite.log.html)

**Comment by mongoose-im** [comment]
[6396.1](https://travis-ci.org/esl/MongooseIM/jobs/528848742) / Erlang 19.3 / small_tests / 0bf9f32482b4b0246d2d17daec975b52d265ea1a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6396/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6396/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-05-06_16.27.02/lib.mongooseim.logs/run.2019-05-06_16.27.03/suite.log.html)

**Comment by ludwikbukowski** [comment]
Looks good to me. However Im concerned how deep should we go with testing.
Is just the simplest scenario enough? 
Can we assume, that because we call roster's backend, it will just work for more complex cases, e.g different types of subscriptions and we do not check other fields than jid ?

**Comment by mongoose-im** [comment]
[6408.1](https://travis-ci.org/esl/MongooseIM/jobs/529209238) / Erlang 19.3 / small_tests / 95585cf08a8ff2d8e2534c256d36bd56899afd9f
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6408/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6408/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-05-07_11.44.17/lib.mongooseim.logs/run.2019-05-07_11.44.18/suite.log.html)

**Comment by mongoose-im** [comment]
[6417.1](https://travis-ci.org/esl/MongooseIM/jobs/529633268) / Erlang 19.3 / small_tests / bf1ed5277331dd214fa14695605593f9430b465b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6417/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6417/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-05-08_06.26.21/lib.mongooseim.logs/run.2019-05-08_06.26.22/suite.log.html)

**Comment by mongoose-im** [comment]
[6450.1](https://travis-ci.org/esl/MongooseIM/jobs/530354276) / Erlang 19.3 / small_tests / f155d8a4c7ffb5f3ec45f9e36447aa6d9cb8139a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2286/6450/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2286/6450/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-05-09_16.19.37/lib.mongooseim.logs/run.2019-05-09_16.19.38/suite.log.html)

**Pull request merged**
