### PR TITLE
Disable mnesia [wip]

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses #

Proposed changes include:
* describe the functionality changes
* describe new or updated tests
* describe changes to the documentation

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_25_arm64](https://circleci.com/gh/esl/MongooseIM/177139) / small_tests / 8813e3482cc3bbdea4f328f71cabc1a0d8c96447
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/177139/small_tests.25.3-arm64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4033/177139/small_tests.25.3-arm64/small/ct_run.mongooseim@localhost.2023-06-08_19.14.55/lib.mongooseim.logs/run.2023-06-08_19.14.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/177165) / small_tests / 9ee7ef2e118343540ef2f542d0e297b30bb090c5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/177165/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4033/177165/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-06-08_23.51.11/lib.mongooseim.logs/run.2023-06-08_23.51.12/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/177424) / small_tests / 390c25e04c954f1f572a19e485297d372665f5cd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/177424/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4033/177424/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-06-12_22.31.28/lib.mongooseim.logs/run.2023-06-12_22.31.28/suite.log.html)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_25](https://circleci.com/gh/esl/MongooseIM/178159) / odbc_mssql_mnesia / 741dfe9fdf32cb9d98941f13cdd9ff36de6eec36
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/178159/odbc_mssql_mnesia.25.3-amd64)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_25](https://circleci.com/gh/esl/MongooseIM/178341) / odbc_mssql_mnesia / b1d7fb2636151ba157207742f333ce9876284710
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/178341/odbc_mssql_mnesia.25.3-amd64)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_25](https://circleci.com/gh/esl/MongooseIM/179103) / odbc_mssql_mnesia / 3823481b19cc91ce4dd4bf0f1e9feb4a98af5db7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4033/179103/odbc_mssql_mnesia.25.3-amd64)

**Comment by arcusfelis** [comment]
We are doing it in separate smaller PRs now.

**Pull request closed without merging**
