### PR TITLE
Remove dead tools

### PR DESCRIPTION
**Pull request by NelsonVides**
This PR removes a ton of old and dead tools and code.

And also updates the rebar3 binary.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/244774) / elasticsearch_and_cassandra_mnesia / 31d8d79d54101278fb75181322b059f32fbaeaea
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4411/244774/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4411/244774/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%407f9ef03607d7.2024-12-03_14.04.19/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/245944) / elasticsearch_and_cassandra_mnesia / cd5e55f66a15be2bb5c0807c85b706d0a001479b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4411/245944/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4411/245944/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%408bbf24b321b3.2024-12-04_10.26.48/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/246061) / elasticsearch_and_cassandra_mnesia / 33fe8d6c62af6a89db03dd789e98d776ea8dff3d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4411/246061/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4411/246061/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%401c72c6ec8534.2024-12-04_11.52.42/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
looks ok

**Pull request merged**
