### PR TITLE
Update MySQL version

### PR DESCRIPTION
**Pull request by chrzaszcz**
This PR allows testing with MySQL on the Apple M1 chip.

8.0.20 does not work on arm64, while 8.0.30 does.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139969) / small_tests / 03043cbe42a361ff7410dd0755f23ba001dd848a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3779/139969/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3779/139969/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-28_10.29.02/lib.mongooseim.logs/run.2022-09-28_10.29.03/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Brilliant 👌🏽

**Comment by NelsonVides** [comment]
For the record, https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html says it's here where they added M1 support

**Comment by NelsonVides** [comment]
For the record, https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html says it's here where they added M1 support

**Pull request merged**
