### PR TITLE
Use transactions for mongoose_cluster operations

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses some errors in cluster command tests.

Proposed changes include:
* we use global transaction for node clustering operations, to ensure that the operations would be serialized (i.e. no two running at the same time).

### CODE REVIEW

**Comment by mongoose-im** [comment]
[7221.1](https://travis-ci.org/esl/MongooseIM/jobs/587597998) / Erlang 22.0 / small_tests / a96679b31b4bdc129e688b2b58c2f58027ddc038
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2470/7221/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2470/7221/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-09-20_20.12.15/lib.mongooseim.logs/run.2019-09-20_20.12.16/suite.log.html)

**Comment by arcusfelis** [comment]
Example:
```
Testing big_tests.tests.push_integration_SUITE: TEST COMPLETE, 14 ok, 0 failed, 8 skipped of 22 test cases

Testing big_tests.tests.push_pubsub_SUITE: Starting test (with repeated test cases)

Testing big_tests.tests.connect_SUITE: Stopping repeat operation {repeat_until_all_ok,3}

Testing big_tests.tests.push_pubsub_SUITE: Stopping repeat operation {repeat_until_all_ok,3}

Testing big_tests.tests.push_pubsub_SUITE: Stopping repeat operation {repeat_until_all_ok,3}

Testing big_tests.tests.push_pubsub_SUITE: Stopping repeat operation {repeat_until_all_ok,3}

distributed_helper:verify_result/2 returns a lot of:

ng3mim2@localhost has [ng3mim1@localhost,ng3mim2@localhost]

ng3mim1@localhost has [ng3mim2@localhost,ng3mim1@localhost]

```

https://travis-ci.org/arcusfelis/MongooseIM/jobs/576742654

**Comment by mongoose-im** [comment]
[7228.1](https://travis-ci.org/esl/MongooseIM/jobs/588461667) / Erlang 22.0 / small_tests / db00dc05c4efa3b88a391247bb09f6331d94b66b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2470/7228/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2470/7228/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-09-23_14.04.11/lib.mongooseim.logs/run.2019-09-23_14.04.11/suite.log.html)

**Comment by mongoose-im** [comment]
[7237.1](https://travis-ci.org/esl/MongooseIM/jobs/588682709) / Erlang 22.0 / small_tests / 7a54d4633b5a058f7a309b186e3c55f773ccb1fd
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2470/7237/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2470/7237/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-09-23_22.36.29/lib.mongooseim.logs/run.2019-09-23_22.36.30/suite.log.html)

**Comment by arcusfelis** [comment]
Added a test

**Pull request merged**
