### PR TITLE
Erlang 27.0.1 update on Circle CI

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "Update Erlang versions MIM-2251".

Proposed changes include:
* Adapt circleci config to run on Erlang 26.2.5.2 and 27.0.1
* Just replaced version numbers here
* Not replaced for packages (because esl-packages are lagging to compile).
* Main work is done in https://github.com/esl/MongooseIM/pull/4345 (merged) and https://github.com/esl/MongooseIM/pull/4338 (merged).

* Original PR was https://github.com/esl/MongooseIM/pull/4320 , but we decided to split it into smaller PRs.
Worker_pool update https://github.com/esl/escalus/pull/269 for escalus - merged.
* we mock inet in global_distrib tests (because we have to do it on all nodes).

# Tutorial for updates

How to update for the future? In vim replace strings:

```
:%s/_26/_27/g
:%s/_25/_26/g
```

Update references:

```
  - &OTP26 mongooseim/cimg-erlang:26.2.5.2
  - &OTP27 mongooseim/cimg-erlang:27.0.1
```

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_26](https://circleci.com/gh/esl/MongooseIM/233923) / small_tests / e2c2681d54a76208bba077888239d969a08198b5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4348/233923/small_tests.26.2.5.2-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4348/233923/small_tests.26.2.5.2-amd64/small/ct_run.mongooseim@localhost.2024-07-30_13.28.10/lib.mongooseim.logs/run.2024-07-30_13.28.11/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/233941) / elasticsearch_and_cassandra_mnesia / 4bf512d0b5bea6962eece653750f785079533820
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4348/233941/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4348/233941/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big/ct_run.test%40ddccb07d146c.2024-07-30_14.39.01/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/233973) / elasticsearch_and_cassandra_mnesia / 709bc4f9b6fe69b1e4b9fd07f13dc34d4fc8f6f0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4348/233973/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4348/233973/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big/ct_run.test%40d6be0f95dc46.2024-07-30_15.41.53/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/234006) / elasticsearch_and_cassandra_mnesia / 6b022bf005d19c1c79985beb238f9a7d98e89016
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4348/234006/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4348/234006/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big/ct_run.test%40c96aaf5bbd11.2024-07-30_17.29.45/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Review by jacekwegr — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
