### PR TITLE
Rdbms casts

### PR DESCRIPTION
**Pull request by NelsonVides**
Sometimes we might want to throw inserts without caring about the return value, so we don't need to block the c2s process for the DB worker to return. To be used carefully, it can overload the DB workers as the c2s process might then, unblocked, generate load faster than the DB workers might clear it.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/98202) / small_tests / 3793f3789e0611a4bc232213820df7408a3aa954
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3485/98202/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3485/98202/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-31_17.43.31/lib.mongooseim.logs/run.2021-12-31_17.43.31/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/98893) / small_tests / 89ab676140c94ed949138a39e55edd93b8f3a52c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3485/98893/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3485/98893/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-04_10.13.11/lib.mongooseim.logs/run.2022-01-04_10.13.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/98950) / small_tests / 73e02d9d5725ecbc155e6f96c203566c99208a18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3485/98950/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3485/98950/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-04_10.58.21/lib.mongooseim.logs/run.2022-01-04_10.58.22/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
sure

**Pull request merged**
