### PR TITLE
Replace local_config records with key-value pairs

### PR DESCRIPTION
**Pull request by chrzaszcz**
This PR replaces the `local_config` records with key-value tuples.

- The is no reason to keep the `local_config` record and `ejabberd_config.hrl` anymore, as there are no `config` and `local_config` tables.
- KV tuples are one step closer to maps.

Config spec format for the top-level options was renamed to keep the notion of `global` vs `host`, see commit messages for details. Although there are no config records anymore, the format is still needed to process the keys.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/89654) / small_tests / d538b312d33925104c10a02661d326a0d84e5f84
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3410/89654/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3410/89654/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-22_15.19.36/lib.mongooseim.logs/run.2021-11-22_15.19.37/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/89663) / small_tests / 370871058f1eb16104e049735c6b62cbbabba436
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3410/89663/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3410/89663/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-22_15.24.03/lib.mongooseim.logs/run.2021-11-22_15.24.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/89755) / small_tests / 9ab53b26f60e38786bccf190ce5a71db409885bc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3410/89755/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3410/89755/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-22_16.40.07/lib.mongooseim.logs/run.2021-11-22_16.40.07/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/89963) / small_tests / 06286fa4c708dd17d7eb0d052b871e9bd70985d8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3410/89963/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3410/89963/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-23_08.06.14/lib.mongooseim.logs/run.2021-11-23_08.06.15/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Excellent 👍🏽

**Review by Premwoik — APPROVED** [review]
Looks good to me :)

**Pull request merged**
