### PR TITLE
Make enforcing simple queries configurable

### PR DESCRIPTION
**Pull request by NelsonVides**
This might be useful when we just don't want to offer clients the possibility of making very expensive queries. A conversation with over 10k messages is not uncommon, and when there are many of them and that many are fetched, it can put the DB at DDoS risk.
So if the operator desires so, all counting operations can be removed to begin with.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132652) / small_tests / dae16f54c2a9042501833f45fe81c4b425216933
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3733/132652/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3733/132652/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_14.44.00/lib.mongooseim.logs/run.2022-08-12_14.44.00/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132678) / small_tests / 607a3251d380bca86271be6261018deb70414a96
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3733/132678/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3733/132678/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_18.22.51/lib.mongooseim.logs/run.2022-08-12_18.22.52/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132708) / small_tests / 28cb7a1943d117eb134f6fb0cbf552221889d552
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3733/132708/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3733/132708/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_18.34.02/lib.mongooseim.logs/run.2022-08-12_18.34.02/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
