### PR TITLE
MAM documentation fixes

### PR DESCRIPTION
**Pull request by arkgil**
The main change of this PR is a removal of `mnesia_dirty` prefs store from documentation **and** `mod_mam_meta` module. I've also fixed the link to MAM XEP (it points to 0.6 though) and took a chance to improve rendering of bullet points (4 spaces make a nested bullet point! 👍 )

### CODE REVIEW

**Comment by fenek** [comment]
There are still some leftovers. :)

```
MongooseIM $ grep -nr "mnesia_dirty" .
./apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyhttp.cfg:650:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyhttp.cfg:718:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyws.cfg:650:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/cowboy_SUITE_data/ejabberd.onlyws.cfg:718:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.default.cfg:630:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.default.cfg:693:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.split.cfg:647:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.split.cfg:710:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.cfg:631:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.cfg:694:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.different_opts.cfg:631:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/ejabberd_config_SUITE_data/ejabberd.with_mod_offline.different_opts.cfg:694:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/revproxy_SUITE_data/ejabberd.norules.cfg:650:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/revproxy_SUITE_data/ejabberd.norules.cfg:718:% {mod_mam_mnesia_dirty_prefs, [pm]},
./apps/ejabberd/test/revproxy_SUITE_data/ejabberd.onerule.cfg:653:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./apps/ejabberd/test/revproxy_SUITE_data/ejabberd.onerule.cfg:721:% {mod_mam_mnesia_dirty_prefs, [pm]},
./doc/user-guide/ICE_tutorial/ejabberd.cfg:837:%   {user_prefs_store, mnesia_dirty},
./doc/user-guide/ICE_tutorial/ejabberd.cfg:880:%     {user_prefs_store, mnesia_dirty}
./rel/files/ejabberd.cfg.token-support:690:% {mod_mam_mnesia_dirty_prefs, [pm, muc]},
./rel/files/ejabberd.cfg.token-support:753:% {mod_mam_mnesia_dirty_prefs, [pm]},
```

**Comment by arkgil** [comment]
Hm, but of all those files only one uses the new MAM config format. What should I do with the other ones? Is the old format valid anymore?

**Comment by fenek** [comment]
Old format can still be used. Just remove/update the examples with `mnesia_dirty` without analysis if all of these files are still used in project.

**Comment by arkgil** [comment]
@fenek I've deleted the leftovers.

**Pull request merged**
