### PR TITLE
Add GraphQL handler for CETS info

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses MIM-1881

Proposed changes include:
* Graphql handler
* Tests

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173770) / small_tests / a2647f3aee9574e09d810a6129f1dfc7edabc375
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4015/173770/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4015/173770/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-25_07.16.57/lib.mongooseim.logs/run.2023-04-25_07.16.57/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173798) / small_tests / 55f3e9dd85307218e5cdeb2b34eae163405a769f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4015/173798/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4015/173798/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-25_08.39.58/lib.mongooseim.logs/run.2023-04-25_08.39.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173908) / small_tests / d9db7461d882c53096cad3b91f2ee3524e5b4174
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4015/173908/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4015/173908/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-26_08.46.20/lib.mongooseim.logs/run.2023-04-26_08.46.21/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173937) / small_tests / 9e84be42cb12977b78a33d9bd070727845de85a2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4015/173937/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4015/173937/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-26_09.01.03/lib.mongooseim.logs/run.2023-04-26_09.01.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/174136) / small_tests / f34c7341b7208cd3ee8920af721482a201b3702e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4015/174136/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4015/174136/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-28_07.22.35/lib.mongooseim.logs/run.2023-04-28_07.22.36/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
