### PR TITLE
C2s/merge master

### PR DESCRIPTION
**Pull request by NelsonVides**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141675) / small_tests / c835c9f7003e0158251ac9a0f8ea02e393bf4d9c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/141675/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/141675/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_12.18.04/lib.mongooseim.logs/run.2022-10-04_12.18.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141724) / small_tests / bb3dd5ce142e6c75700ef241c927bcff3e5aa403
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/141724/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/141724/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_12.36.48/lib.mongooseim.logs/run.2022-10-04_12.36.49/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141959) / small_tests / 3c52641da1ca5ad6b698a093491e760ed88f8133
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/141959/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/141959/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_15.37.25/lib.mongooseim.logs/run.2022-10-04_15.37.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141989) / small_tests / f316e249387d7e8329e67b9fe60ff69b95f51dba
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/141989/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/141989/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_16.08.56/lib.mongooseim.logs/run.2022-10-04_16.08.57/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142010) / small_tests / 23f9a3db5db76208cfdb49ad34f35ea3ea044070
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/142010/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/142010/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_16.21.07/lib.mongooseim.logs/run.2022-10-04_16.21.07/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142290) / small_tests / c9e8cb08428c4f9d69de601aa68726be5be068df
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/142290/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/142290/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_11.14.42/lib.mongooseim.logs/run.2022-10-05_11.14.43/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142336) / small_tests / f902f3faed46d413b40bf0e229eaed2e88d7d064
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/142336/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/142336/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_11.37.40/lib.mongooseim.logs/run.2022-10-05_11.37.40/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142388) / small_tests / cdb15bf6735a5ef93fe4092eff85722b57932e4e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/142388/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/142388/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_12.23.46/lib.mongooseim.logs/run.2022-10-05_12.23.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142944) / small_tests / 01bc4801641195481cfcc98dc3d0c4ce394562c1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3790/142944/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3790/142944/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_10.00.40/lib.mongooseim.logs/run.2022-10-07_10.00.41/suite.log.html)

**Review by kamilwaz — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
