### PR TITLE
Publish packages on GitHub

### PR DESCRIPTION
**Pull request by jacekwegr**
This pull request updates the script to also publish built packages as release assets for tags.

The changes were tested with a test release and confirmed to work as expected.

CircleCI workflow: [here](https://app.circleci.com/pipelines/github/esl/MongooseIM/13533/workflows/715c75df-2400-46d6-b9f8-807573f367c2)

Test release on GH:
test_release

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252833) / elasticsearch_and_cassandra_mnesia / 4fd7cac1fadd1e0fbadcacd68a6e43f53fd4d310
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4449/252833/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4449/252833/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%404410a24d834e.2024-12-24_13.01.35/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252882) / elasticsearch_and_cassandra_mnesia / c90c65b3fff351e3a413a2485ee3cd7feff0da8d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4449/252882/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4449/252882/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%401acd48672b8b.2024-12-24_13.39.39/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252961) / elasticsearch_and_cassandra_mnesia / bbcfaf0ca17141e35c3978cb03bb2ef282d7f99d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4449/252961/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4449/252961/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%400c9c63020835.2024-12-27_14.31.36/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/253048) / elasticsearch_and_cassandra_mnesia / 81ed99240c8bbf86c602abd787fc5ee6b3a53f0a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4449/253048/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4449/253048/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40316b0199f3f2.2024-12-27_15.49.49/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/253075) / elasticsearch_and_cassandra_mnesia / e09501a094bf96926e2b4fe6975b02e688b7fcc8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4449/253075/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4449/253075/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4007b17853dc64.2024-12-27_16.08.28/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
LGTM 👌

**Pull request merged**
