### PR TITLE
Use Erlang/OTP 22.1.8 on CircleCI

### PR DESCRIPTION
**Pull request by michalwski**

### CODE REVIEW

**Comment by NelsonVides** [comment]
Just so next time we need to upgrade OTP, the diff is smaller, what do you think of adding it as a default value on the yaml description around here:
https://github.com/esl/MongooseIM/pull/2559/files#diff-1d37e48f9ceff6d8030570cd36286a61L38 ?

**Comment by mongoose-im** [comment]
[7552.1](https://travis-ci.org/esl/MongooseIM/jobs/623107624) / Erlang 22.0 / small_tests / ac54c95e1ddcfb956d025f4fa02427f92ef7646f
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2559/7552/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2559/7552/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-12-10_12.28.27/lib.mongooseim.logs/run.2019-12-10_12.28.27/suite.log.html)

**Comment by michalwski** [comment]
@NelsonVides here it's https://github.com/esl/MongooseIM/pull/2559/commits/203eb9487c3c0f262770d3e19daf8c491a8e5365 we need to specify the default value in 6 other places than the original 10 places :) I don't know what's clearer.

**Comment by mongoose-im** [comment]
[7558.1](https://travis-ci.org/esl/MongooseIM/jobs/623204431) / Erlang 22.0 / small_tests / 47595a29a849e841e118549eec4481623a4866d0
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2559/7558/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2559/7558/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-12-10_16.35.06/lib.mongooseim.logs/run.2019-12-10_16.35.06/suite.log.html)

**Pull request merged**
