### PR TITLE
Arm update

### PR DESCRIPTION
**Pull request by NelsonVides**
The old version of re2 won't compile under the newer ARM M1 macs, this fixes it. Tested on an ARM AWS machine, and also, we got a PR to cqerl from a guy who precisely had an M1 testing.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/103544) / small_tests / 4cbf8845a5be25fd88a22a6677dcabb2b27a9c17
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3520/103544/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3520/103544/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-28_15.57.24/lib.mongooseim.logs/run.2022-01-28_15.57.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/103583) / small_tests / b88a6f5a858e5cd9fb151656f47b77ff18ea1c29
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3520/103583/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3520/103583/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-28_16.13.03/lib.mongooseim.logs/run.2022-01-28_16.13.04/suite.log.html)

**Comment by arcusfelis** [comment]
https://github.com/esl/cqerl/pull/9

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
