### PR TITLE
Refactor pubsub

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "some code moving around".

Moved pure stuff in the bottom of the file, moving it in a separate file sometime in future.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[5406.1](https://travis-ci.org/esl/MongooseIM/jobs/419071845) / Erlang 19.3 / small_tests / 2d180cc61f3d3e8a5c182d03387847dee0a71014
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2035/5406/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2035/5406/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-22_09.01.01/lib.mongooseim.logs/run.2018-08-22_09.01.02/suite.log.html)

**Comment by mongoose-im** [comment]
[5439.1](https://travis-ci.org/esl/MongooseIM/jobs/420175383) / Erlang 19.3 / small_tests / d6619aa9a9e584328e5d9dfbc2a08a167c9a502c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2035/5439/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2035/5439/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-24_15.45.06/lib.mongooseim.logs/run.2018-08-24_15.45.07/suite.log.html)

**Comment by mongoose-im** [comment]
[5440.1](https://travis-ci.org/esl/MongooseIM/jobs/420179306) / Erlang 19.3 / small_tests / dcd8c3b2b9c2de9fa1e8c061d85f79782419337f
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2035/5440/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2035/5440/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-24_16.34.28/lib.mongooseim.logs/run.2018-08-24_16.34.28/suite.log.html)

**Comment by mongoose-im** [comment]
[5441.1](https://travis-ci.org/esl/MongooseIM/jobs/420201970) / Erlang 19.3 / small_tests / 87bc6eb977f4cc6deefde1be09227d1dd3016eb0
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2035/5441/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2035/5441/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-24_17.21.01/lib.mongooseim.logs/run.2018-08-24_17.21.02/suite.log.html)

**Comment by mongoose-im** [comment]
[5544.1](https://travis-ci.org/esl/MongooseIM/jobs/425212383) / Erlang 19.3 / small_tests / 07a5a3689368555d57b0bd5544355c7f24c03e4a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2035/5544/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2035/5544/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-09-06_11.32.36/lib.mongooseim.logs/run.2018-09-06_11.32.37/suite.log.html)

**Comment by michalwski** [comment]
I think this PR conflicts a lot with the recent work done in #2113 
@arcusfelis are you open to fix the conflicts or we close the PR and continue refactoring in other PRs?

**Comment by michalwski** [comment]
Many of the changes form this PR where done in a series of PRs adding RDBMS backend for pubsub.

**Pull request closed without merging**
