### PR TITLE
Split listeners documentation into multiple files

### PR DESCRIPTION
**Pull request by gustawlippa**
This PR splits the ` Options: Listen ` section of the documentation into multiple files, one for each of: general options, C2S, S2S, XMPP Components and HTTP listeners.

It also fixes small issues I found when reviewing the docs, like typos, warnings, missing links.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/230540) / elasticsearch_and_cassandra_mnesia / 2434ee080e5ccbbb7eb2db32237f88b3d6181708
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/230540/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4327/230540/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%403a12c64669e2.2024-07-23_14.51.05/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/231078) / odbc_mssql_mnesia / 6716874a27787c5dcfafc5712206f16776ac1595
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/231078/odbc_mssql_mnesia.26.2.2-amd64)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/231415) / odbc_mssql_mnesia / bc1e232c522e3155d8073517761e96beb230730a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/231415/odbc_mssql_mnesia.26.2.2-amd64)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/231510) / odbc_mssql_mnesia / c742a5c07187731a7b90515aac73e17c8e6695fd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/231510/odbc_mssql_mnesia.26.2.2-amd64)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/231788) / elasticsearch_and_cassandra_mnesia / d6347f1e130e106125f564943db16ee2faa46261
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/231788/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4327/231788/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40240a90aff505.2024-07-25_13.35.49/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
Looks good. I added one minor comment - not necessary to address.

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/231957) / elasticsearch_and_cassandra_mnesia / e6d3c4de72a04c9a4b53fcf27c7db341bb16b5bc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4327/231957/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4327/231957/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40c18cc2a47fb1.2024-07-25_14.23.12/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Pull request merged**
