### PR TITLE
Update GraphQL docs and history

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses MIM-1711

Proposed changes include:
* Update revokeToken command
* Use a direct link to docss to avoid redirect
* Update history with Graphql and API info

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157451) / small_tests / 481522dd75255a8de8d84f44eb520bd2a7c5eaea
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3900/157451/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3900/157451/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-12_23.30.50/lib.mongooseim.logs/run.2022-12-12_23.30.50/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
One typo to fix

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157879) / small_tests / 92e0dd91350de740c7df94b8e56c9adb58d7e769
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3900/157879/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3900/157879/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-15_08.07.50/lib.mongooseim.logs/run.2022-12-15_08.07.51/suite.log.html)

**Review by jacekwegr — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
