### PR TITLE
Use OTP 25 on circle ci

### PR DESCRIPTION
**Pull request by arcusfelis**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/125187) / small_tests / 2c05eb636a755f1b1f3c58a28f0697593ce081e7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3667/125187/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3667/125187/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-02_14.17.32/lib.mongooseim.logs/run.2022-06-02_14.17.33/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/125494) / small_tests / 857a3e395a7d1c395e5dd212f6eaf3db271e468b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3667/125494/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3667/125494/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-03_14.58.36/lib.mongooseim.logs/run.2022-06-03_14.58.37/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/125624) / small_tests / 7044cd9efd3da4dde737b7b741f470cef2dff04e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3667/125624/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3667/125624/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-06_12.26.26/lib.mongooseim.logs/run.2022-06-06_12.26.26/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/125669) / small_tests / d360fd0d7bb047137cbbd627d2b743606debf924
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3667/125669/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3667/125669/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-06_14.18.43/lib.mongooseim.logs/run.2022-06-06_14.18.43/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/125717) / small_tests / 62875c284ef0f30cbbd24ac23012582f0f60a35f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3667/125717/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3667/125717/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-06_17.25.48/lib.mongooseim.logs/run.2022-06-06_17.25.49/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM! 👌🏽

**Review by chrzaszcz — COMMENTED** [review]
Looks good in general, I added a few comments.

**Review by chrzaszcz — APPROVED** [review]
Looks good 👍

**Pull request merged**
