### PR TITLE
MongooseIM 2.0.1

### PR DESCRIPTION
**Pull request by michalwski**
This release includes:
- extended REST API for [clients](http://mongooseim.readthedocs.io/en/2.0.1/swagger/index.html?client=true)
    - support for SSE: #1043, #1131
- improvements to [XEP-0016: Privacy Lists](http://xmpp.org/extensions/xep-0016.html): #1084
- improvements to [XEP-0191: Blocking Command](http://xmpp.org/extensions/xep-0191.html): #1122
- [XEP-0045: Multi-User Chat](http://xmpp.org/extensions/xep-0045.html) optimisations:
    - Erlang process hibernation: #1086
    - Stopping room's process if not actively used #1095
- support for [XEP-363: HTTP File Upload](http://xmpp.org/extensions/xep-0363.html): #1139
- ODBC backend for MUC Light #1093
- Cassandra backend for MAM:
    - restored Cassandra backend: #1117
    - migration to cqerl: #1147
    - performance improvements: #1133
    - migration tool for Cassandra backends in MongooseIM 1.6.2 #1159
- other improvements:
    - simplified MAM configuration #1112
    - fix for race condition in session manager #1141
    - migration to p1_mysql #1067
    - migration to p1_pgsql #1074
    - migration to fast_tls #1078
    - improved subdomain handling #1116
    - [complete list of merged PRs](https://github.com/esl/MongooseIM/pulls?utf8=%E2%9C%93&q=is%3Apr%20base%3Amaster%20merged%3A%222016-11-09..2017-01-24%22%20sort%3Acreated-asc%20)
    - [complete list of closed issues](https://github.com/esl/MongooseIM/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20closed%3A%222016-11-09..2017-01-24%22%20)

Special thanks to our contributors: @kenstir, @sstrigler, @igors, @bernardd, @msantos

This release repo [history](https://github.com/esl/MongooseIM/graphs/contributors?from=2016-11-09&to=2017-01-24&type=c)

### CODE REVIEW

**Comment by jonathanve** [comment]
Hi @michalwski 

Regarding REST API Docs and MUC Light for 2.0.1 version, I see REST API endpoints to create a room, invite someone and send messages. Is there any other endpoint(s) not documented for instance to delete a group, update room details, etc.. or is all this functionality available just by raw xmpp; if this is the case, does the new changes for android/ios libs include high level functions for this? Thanks!

**Comment by michalwski** [comment]
Hi @jonathanve,

Thanks for contacting us. To be on the same page I need to be sure if you are asking about REST API for clients [1] or for backend services [2]. In case of [1] it is possible to remove room with HTTP's DELETE method, see [3]. The same is not possible (yet) with the REST API for backend services as described in [2].

Other then REST APIs, full MUC light support is possible via XMPP as described in [4].

[1]. http://mongooseim.readthedocs.io/en/2.0.1/REST-API/
[2]. http://mongooseim.readthedocs.io/en/2.0.1/http-api/http-administration-api-documentation/
[3]. http://mongooseim.readthedocs.io/en/2.0.1/swagger/index.html?client=true#/Rooms
[4]. http://mongooseim.readthedocs.io/en/2.0.1/open-extensions/muc_light/

**Comment by jonathanve** [comment]
Thanks @michalslaski

**Comment by jonathanve** [comment]
Hi @michalslaski Testing Client API and MUC Light works perfect when users are stored in mnesia. I have enabled an external service for authentication and configured mongooseim properly since clients connect without problems. However, when calling the new Client API I got 401s . Is there any configuration parameter missing for MUC Light to validate users using a external auth service ?

**Comment by jonathanve** [comment]
HI @michalslaski Setting up a custom schema for MUC Light is quite straightforward with config_schema and default_config. However, when using the API, the new values do not get stored and the values returned by the API do not contain the new values.

https://github.com/esl/MongooseIM/blob/2.0.1/apps/ejabberd/src/mongoose_client_api_rooms.erl#L96
https://github.com/esl/MongooseIM/blob/2.0.1/apps/ejabberd/src/mongoose_client_api_rooms.erl#L115

I can change the code and create a custom one to do it, I just want to know if there is another way to accomplish the functionality without changing the code in the new releases.

**Comment by michalwski** [comment]
Hi @jonathanve,

I'm really glad to see you are using MongooseIM and its REST API. The first version of the API is very basic. We want to improve and extend it based on customer needs. Your use case is one of the examples we are waiting for!

If this is possible please send a PR with the changes you need. If not I'll make sure this functionality gets into `2.1.0beta1` which we are going to release later this month.

**Comment by jonathanve** [comment]
Hi @michalslaski,

Is there any friendly way to get how many offline messages are stored in the queues, by user, when using mod_offline module? We are trying to define a good max_user_offline_messages value and get to know which clients are most often offline :)

Thanks for your help!

Sorry for posting the question here, I do not know where else to ask it.

**Comment by fenek** [comment]
Hi @jonathanve 

The best place is here: https://github.com/esl/MongooseIM/issues :) Can you please create a new issue there?

**Comment by jonathanve** [comment]
Thanks @fenek Done

https://github.com/esl/MongooseIM/issues/1369

**Pull request merged**
