### PR TITLE
rebar3.15.2

### PR DESCRIPTION
**Pull request by vkatsuba**
* Related to https://github.com/esl/MongooseIM/issues/3177.
* Updated `rebar3` to version `3.15.2` for support OTP 21 also
* Updated `rebar.lock`'s with new `rebar3`

### CODE REVIEW

**Review by NelsonVides — COMMENTED** [review]
Seems great, but have you tried recompiling also big_tests? There's another `rebar.lock` there that might as well change. You can run `./tools/build-tests.sh` for that.

**Comment by vkatsuba** [comment]
> have you tried recompiling also big_tests?

Good point, updated, thanks.

**Comment by mongoose-im** [comment]
[pgsql_mnesia](https://circleci.com/gh/esl/MongooseIM/62373) / pgsql_mnesia / 047fb614ac31a0c01263bb0b36ba1c0a6550fd84
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62373/pgsql_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[dynamic_domains](https://circleci.com/gh/esl/MongooseIM/62390) / pgsql_mnesia / 4d6378414b4f4dce4b8ebd2b35b5713755dcfdfb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62390/pgsql_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[internal_mnesia](https://circleci.com/gh/esl/MongooseIM/62474) / internal_mnesia / b9ceab10c83a0fc6c59d16243fdc2e4f83984c25
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62474/internal_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[pgsql_mnesia](https://circleci.com/gh/esl/MongooseIM/62491) / pgsql_mnesia / 3d26b019a2ed129755aa2e329c39a11b52b7ec18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62491/pgsql_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[pgsql_mnesia](https://circleci.com/gh/esl/MongooseIM/62509) / pgsql_mnesia / 472398423c5cd3a948e266a1d0effb613549cddb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62509/pgsql_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[internal_mnesia](https://circleci.com/gh/esl/MongooseIM/62531) / internal_mnesia / d245cc10a6b765e456cd02942c52a5e9148f2d29
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62531/internal_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[pgsql_mnesia](https://circleci.com/gh/esl/MongooseIM/62552) / pgsql_mnesia / 9b8f88aa386ed991d1339dfcada0773d948b10d0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62552/pgsql_mnesia.23.0.3-1)

**Comment by mongoose-im** [comment]
[dynamic_domains](https://circleci.com/gh/esl/MongooseIM/62550) / pgsql_mnesia / 9b8f88aa386ed991d1339dfcada0773d948b10d0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62550/pgsql_mnesia.23.0.3-1)

**Comment by vkatsuba** [comment]
CT crash is related to `rebar3` issue https://github.com/erlang/rebar3/issues/2526

**Comment by mongoose-im** [comment]
[small_tests_21_3](https://circleci.com/gh/esl/MongooseIM/62582) / small_tests / 9047427e153dcc4d18dab23bf64b1815dd896481
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3185/62582/small_tests.21.3.8.17-1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3185/62582/small_tests.21.3.8.17-1/small/ct_run.mongooseim@localhost.2021-07-14_16.00.35/lib.mongooseim.logs/run.2021-07-14_16.00.36/suite.log.html)

**Comment by vkatsuba** [comment]
[GitHub Actions Result](https://github.com/esl/MongooseIM/actions/runs/1030914267)

**Comment by vkatsuba** [comment]
This PR should be closed due to https://github.com/esl/MongooseIM/pull/3186. In `master` `rebar3` has version `3.16.1` which supports OTP 24.

**Pull request closed without merging**
