### PR TITLE
Instrument/hook handlers - session

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to use `mongoose_instrument` rather than hook handlers and `mongoose_metrics` for session-related events.

- Set up and execute `c2s_auth_failed` in `mongoose_c2s`.
- Create an `sm_session` event with `logins`, `logouts` and `count` metrics. I decided to keep it as one event to be able to increment and decrement the session count.
    - Session count is not a probe, because as a probe it would need to be calculated per host type, and this could be a substantial work. Making it a probe could be a separate task.
- Change subscription events to include the host type, because it is known and other events in the sm module have the host type.
- Add support for a `counter` metric. In Prometheus, it is a gauge.
- Remove metric definitions, including the ones already taken care of in the previous PR's.
- Disable the `sessions_cleanup` test in `last_SUITE`, because it was creating sessions with processes from another node, causing confusion and inconsistent metrics. As agreed with @arcusfelis, this test could be reworked and re-enabled later.
- Update metrics descriptions in docs (should have been already done for some of the metrics).
 Notes:
- `auth_failed` hook has no handlers now, but I thought it might still be useful.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223017) / elasticsearch_and_cassandra_mnesia / d844d0c805269fd4425de4ccdb9c38430bb229f5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223017/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223017/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4080dbe4dfacbb.2024-06-17_09.46.17/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223124) / elasticsearch_and_cassandra_mnesia / 10bbb5f8a5e01528cb354786d4ba959805d44482
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223124/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223124/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40f8bd4edb0928.2024-06-17_14.27.28/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223139) / elasticsearch_and_cassandra_mnesia / 326c6a4eed3e8548346620aeef2e6bd35ad5e8d3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223139/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223139/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%404bbdf41a293c.2024-06-17_14.28.10/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223311) / elasticsearch_and_cassandra_mnesia / 1b5489ea424d269f015e8d73b03792d92ca12abd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223311/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223311/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40d60f07045205.2024-06-18_14.40.01/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223385) / elasticsearch_and_cassandra_mnesia / f4bb23a76818df44e492a8c582df611215aacc7d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223385/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223385/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%403b4d39efcf2a.2024-06-19_07.45.45/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223432) / elasticsearch_and_cassandra_mnesia / 9abfcc24b0d56d93d6847da51af730bdf81d5adb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223432/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223432/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%409822e4e2a4c4.2024-06-19_07.52.42/index.html)
**OK: 456** / Failed: 0 / **User-skipped: 41** / **Auto-skipped: 1** 
<details><summary>mam_SUITE:elasticsearch_muc_all:muc_prefs_cases:muc_messages_filtered_when_prefs_default_policy_is_always</summary>


```erlang
{skip,
  {failed,
    {mam_SUITE,init_per_testcase,
      {{badrpc,
         {'EXIT',
           {#{module => mod_mam_mnesia_prefs,
            text => <<"Module missing from mongoose_config">>,
            host_type => <<"localhost">>,
            what => module_not_loaded},
            [{gen_mod,assert_loaded,2,
               [{file,"/home/circleci/project/src/gen_mod.erl"},
              {line,346}]},
             {gen_mod,start_module,3,
               [{file,"/home/circleci/project/src/gen_mod.erl"},
              {line,96}]},
             {mongoose_modules,start_module,4,
               [{file,
                "/home/circleci/project/src/mongoose_modules.erl"},
              {line,90}]},
             {mongoose_modules,ensure_started,3,
               [{file,
                "/home/circleci/project/src/mongoose_modules.erl"},
              {line,80}]},
             {mongoose_modules,'-replace_modules/3-lc$^1/1-1-',2,
               [{file,
                "/home/circleci/project/src/mongoose_modules.erl"},
              {line,50}]},
             {mongoose_modules,replace_modules,3,
               [{file,
                "/home/circleci/project/src/mongoose_modules.erl"},
              {line,51}]}]}}},
       [{distributed_helper,rpc,
          [#{node => mongooseim@localhost},
           mongoose_modules,replace_modules,
           [<<"localhost">>,[],
          #{mod_mam =>
              #{cache =>
                #{module => internal,strategy => fifo,
                ...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223432/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%409822e4e2a4c4.2024-06-19_07.52.42/big_tests.tests.mam_SUITE.logs/run.2024-06-19_07.52.43/mam_suite.muc_messages_filtered_when_prefs_default_policy_is_always.10244.html)
</details>

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223489) / elasticsearch_and_cassandra_mnesia / 4d171792d5903211dd312c9267b4deb01d38394c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223489/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223489/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40d66b06662b4b.2024-06-19_08.04.20/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223640) / elasticsearch_and_cassandra_mnesia / 7baafa90beb533bbff64f7ea8ed06727a28f866e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223640/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223640/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4066e2bcee35fd.2024-06-19_11.56.39/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/223716) / elasticsearch_and_cassandra_mnesia / ccb47ee623aab4b431cea263ed32f1e21602cf51
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4305/223716/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4305/223716/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40df1d9bf4631c.2024-06-19_13.29.26/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
