### PR TITLE
Pass empty map to node_cleanup hook

### PR DESCRIPTION
**Pull request by michalwski**
This PR fixes node_cleanup hook handlers crashes.

### CODE REVIEW

**Comment by fenek** [comment]
Are these crashes observable in Travis logs (before this fix)? So we could check if it actually works fine.

**Comment by michalwski** [comment]
I think they should be in the logs.

**Comment by mongoose-im** [comment]
[5884.1](https://travis-ci.org/esl/MongooseIM/jobs/456994581) / Erlang 19.3 / small_tests / af13a09a97d6d27fc0ec4ce0ca2fc8968c330c67
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2135/5884/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2135/5884/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-11-19_14.54.09/lib.mongooseim.logs/run.2018-11-19_14.54.10/suite.log.html)

**Comment by fenek** [comment]
I can't find them after a quick search. :(

**Comment by michalwski** [comment]
Right, our tests don't stop nodes during the test. In some cases the config is reloaded and the app is restarted. The node cleanup is not triggered, because the node is not going down.

**Comment by mongoose-im** [comment]
[5885.1](https://travis-ci.org/esl/MongooseIM/jobs/457114717) / Erlang 19.3 / small_tests / 3436711766930de18221f54bcf936e4917236e03
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2135/5885/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2135/5885/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-11-19_19.07.01/lib.mongooseim.logs/run.2018-11-19_19.07.02/suite.log.html)

**Comment by mongoose-im** [comment]
[5890.1](https://travis-ci.org/esl/MongooseIM/jobs/457434774) / Erlang 19.3 / small_tests / b296b2e57c764b0b9eeff41ff8826dd69d8dd7c1
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2135/5890/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2135/5890/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-11-20_12.55.23/lib.mongooseim.logs/run.2018-11-20_12.55.24/suite.log.html)

**Comment by mongoose-im** [comment]
[5893.1](https://travis-ci.org/esl/MongooseIM/jobs/457461251) / Erlang 19.3 / small_tests / 9e0b39530bc2dcb54f1dcd9ebf45ef32b7b8da2b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2135/5893/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2135/5893/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-11-20_14.29.19/lib.mongooseim.logs/run.2018-11-20_14.29.20/suite.log.html)

**Pull request merged**
