### PR TITLE
Busy wait on ejabberd_app:prep_stop/1 instead of plain sleep

### PR DESCRIPTION
**Pull request by NelsonVides**
Just, busy_wait instead of naive sleep when shutting down MIM.

### CODE REVIEW

**Comment by ludwikbukowski** [comment]
It could be even extracted to some shared helper/utils module

**Comment by mongoose-im** [comment]
[7808.1](https://travis-ci.org/esl/MongooseIM/jobs/640024202) / Erlang 22.0 / small_tests / 7e00368a0f427c3121bd3833e580e4e3c71c2cb2
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2602/7808/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2602/7808/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-01-21_18.28.22/lib.mongooseim.logs/run.2020-01-21_18.28.23/suite.log.html)

**Comment by NelsonVides** [comment]
> It could be even extracted to some shared helper/utils module

@ludwikbukowski dunno, which modules we already have as helpers, I don't want to create another one just for this, but indeed we have a lot of functionality that is pretty much generic and could be just shared :thinking:

**Comment by mongoose-im** [comment]
[7811.1](https://travis-ci.org/esl/MongooseIM/jobs/640329951) / Erlang 22.0 / small_tests / 82b02a33b865e7bc34baad5dc35701722b37a338
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2602/7811/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2602/7811/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-01-22_08.47.08/lib.mongooseim.logs/run.2020-01-22_08.47.08/suite.log.html)

**Comment by erszcz** [comment]
@NelsonVides CircleCI is failing for `riak_mnesia` :/ Can we rerun it?

**Comment by NelsonVides** [comment]
> @NelsonVides CircleCI is failing for `riak_mnesia` :/ Can we rerun it?
@erszcz I have rerun it, it is an unrelated failure introduced in https://github.com/esl/MongooseIM/pull/2578 and Jan is working on it on https://github.com/esl/MongooseIM/pull/2603

**Comment by mongoose-im** [comment]
[7821.1](https://travis-ci.org/esl/MongooseIM/jobs/640653923) / Erlang 22.0 / small_tests / df97b392da15f2b85643a21a3563d09eb7319ca6
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2602/7821/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2602/7821/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-01-23_01.15.50/lib.mongooseim.logs/run.2020-01-23_01.15.51/suite.log.html)

**Comment by michalwski** [comment]
I'm closing this one since it's part of #2621

**Pull request closed without merging**
