### PR TITLE
Add remove_domain for internal auth

### PR DESCRIPTION
**Pull request by jacekwegr**
This PR adds a function for removing the domain for `auth.internal`. It also clears the users at the end of the `muc_light_legacy_SUITE` so that it doesn't finish dirty.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173171) / small_tests / 8990777e1d283e5b518af95887b680ed88b45ba7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4010/173171/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4010/173171/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-17_06.36.20/lib.mongooseim.logs/run.2023-04-17_06.36.20/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/173509) / small_tests / dd1948d33ec4a811452ae57d168fca33f933f251
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4010/173509/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4010/173509/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-19_07.11.55/lib.mongooseim.logs/run.2023-04-19_07.11.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_25_arm64](https://circleci.com/gh/esl/MongooseIM/173650) / small_tests / 159713b8d86736334a7d5e00232328b788948ada
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4010/173650/small_tests.25.3-arm64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4010/173650/small_tests.25.3-arm64/small/ct_run.mongooseim@localhost.2023-04-21_07.29.29/lib.mongooseim.logs/run.2023-04-21_07.29.29/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good

**Pull request merged**
