### PR TITLE
Get rid of mongoose_commands

### PR DESCRIPTION
**Pull request by chrzaszcz**
The new `mongoose_admin_api` module covers the functionality that `mongoose_api_admin`, `mongoose_commands`, `mod_commands`, `mod_muc_commands` and `mod_muc_light_commands` used to provide. This means that all the unused code can be now removed, resulting in a significant code reduction.

Also: log level for HTTP errors for the Admin REST API was reduced. Now it is:
- `error` for internal server errors.
- `warning` for other errors.

TO DO after this PR:
- Rework `mongoose_api` and `mongoose_domain_handler` to use `mongoose_admin_api`.
- Document the new REST API.
- Update migration guide.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136693) / small_tests / dbd74b5e759e2c760e3ac3c266e7b121d54321b0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/136693/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/136693/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-14_14.00.46/lib.mongooseim.logs/run.2022-09-14_14.00.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136715) / small_tests / c8c8355e60d9a584394422b15efce3ab445505a9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/136715/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/136715/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-14_14.26.56/lib.mongooseim.logs/run.2022-09-14_14.26.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136741) / small_tests / 038fd1f988a80285e68f97a3c943c3068bc62566
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/136741/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/136741/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_07.04.56/lib.mongooseim.logs/run.2022-09-15_07.04.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136773) / small_tests / fff16724e843e4bf9bc8e24e14a291ceea12d38b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/136773/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/136773/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_07.36.54/lib.mongooseim.logs/run.2022-09-15_07.36.55/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136820) / small_tests / 999cb6890743a85461036617d2a9f32e369e7daf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/136820/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/136820/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_08.23.02/lib.mongooseim.logs/run.2022-09-15_08.23.02/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/137002) / small_tests / 27e048627dbdaceaee92e9afa17a205c9658a481
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3759/137002/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3759/137002/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_12.43.45/lib.mongooseim.logs/run.2022-09-15_12.43.46/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
