### PR TITLE
Fix modMucMamFlushed metric

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "modMucMamFlushed is updated but not created".

Proposed changes include:
* modMucMamFlushed is created now

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9070.1](https://travis-ci.org/esl/MongooseIM/jobs/757543651) / Erlang 23.0.3 / small_tests / 7e2374106805afc0d9f43d553efd95a11947aea4
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3023/9070/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3023/9070/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-04_12.59.28/lib.mongooseim.logs/run.2021-02-04_12.59.29/suite.log.html)

**Comment by chrzaszcz** [comment]
This cannot work because the hook is not added anywhere in the code, see `mongoose_metrics_mam_hooks:get_hooks/1`

Could you:
- Make the code actually update the metric :-)
- Make the 1-to-1 and MUC versions consistent. One is using a hook and one is not, I think hooks are just not necessary here. Let the MUC version just update the metric directly like 1-to-1.
- Add a test for the metric - maybe we already have an async writer test and we could just check the metric there?

**Review by chrzaszcz — CHANGES_REQUESTED** [review]
The comment above explains it.

**Comment by mongoose-im** [comment]
[9074.1](https://travis-ci.org/esl/MongooseIM/jobs/757675782) / Erlang 23.0.3 / small_tests / 34eb8969da43c84f745a923118e4952be1a200f9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3023/9074/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3023/9074/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-05_10.41.02/lib.mongooseim.logs/run.2021-02-05_10.41.02/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
It works now, confirmed by a load test, good!

**Pull request merged**
