### PR TITLE
Improve SSL tests and docs

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "some SSL options are not tested or documented".

WIP

### CODE REVIEW

**Comment by mongoose-im** [comment]
[5389.1](https://travis-ci.org/esl/MongooseIM/jobs/418241409) / Erlang 19.3 / small_tests / 136dd059862c4183f5be976f135298013201da57
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2033/5389/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2033/5389/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-20_13.59.33/lib.mongooseim.logs/run.2018-08-20_13.59.34/suite.log.html)

**Comment by mongoose-im** [comment]
[5394.1](https://travis-ci.org/esl/MongooseIM/jobs/418253575) / Erlang 19.3 / small_tests / 0b4a2325a58b7d82a5f4098996df402ae029ccf5
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2033/5394/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2033/5394/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-20_15.23.22/lib.mongooseim.logs/run.2018-08-20_15.23.23/suite.log.html)

**Comment by mongoose-im** [comment]
[5399.1](https://travis-ci.org/esl/MongooseIM/jobs/418330757) / Erlang 19.3 / small_tests / 6370a4e46178eaa9b865420238431da54c5fd372
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2033/5399/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2033/5399/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-20_17.51.34/lib.mongooseim.logs/run.2018-08-20_17.51.35/suite.log.html)

**Comment by mongoose-im** [comment]
[5400.1](https://travis-ci.org/esl/MongooseIM/jobs/418360965) / Erlang 19.3 / small_tests / 1208e0f798c508aac00950992850f6f05f052599
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2033/5400/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2033/5400/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-08-20_18.40.53/lib.mongooseim.logs/run.2018-08-20_18.40.54/suite.log.html)

**Comment by michalwski** [comment]
This has been covered by #2085, #2093 and #2102

**Pull request closed without merging**
