### PR TITLE
Pass args as one parameter to runuser command

### PR DESCRIPTION
**Pull request by sebb7**
Bug found and fixed by @DenysGonchar

### CODE REVIEW

**Comment by mongoose-im** [comment]
[7928.1](https://travis-ci.org/esl/MongooseIM/jobs/649035709) / Erlang 22.0 / small_tests / 14c6a274811f66edde84e7cdad8b64cb00c68d7c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2631/7928/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2631/7928/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-02-11_17.49.40/lib.mongooseim.logs/run.2020-02-11_17.49.41/suite.log.html)

**Comment by sebb7** [comment]
@michalwski maybe we can add some sample additional commands [here](https://github.com/esl/MongooseIM/blob/master/tools/pkg/Dockerfile_rpm#L45)?

**Comment by michalwski** [comment]
Oh yes. For instance a command registering a user or several users. As far as I understand the issue was that no all arguments were passed to the script, right?

**Comment by sebb7** [comment]
Yes. The arguments were passed as `"$@"`  what caused that the next `mongooseimctl` script call contained only first argument from `"$@"` .

**Comment by michalwski** [comment]
I'm working on the tests in a separate PR.

**Pull request merged**
