### PR TITLE
MIM-2310 Update dependencies

### PR DESCRIPTION
**Pull request by telezynski**
- Update jiffy-1.1.2, jid-2.2.0, erl_csv-0.3.2
- Update telemetry-1.3.0, fast_tls-1.1.22
- Update fast_scram-0.6.0, fast_pbkdf2-1.0.5
- Update uuid-2.0.7, quickrand-2.0.7
- Update cache_tab-1.0.31, p1_utils-1.0.26
- Update segmented_cache-0.4.0
- Update worker_pool-6.4.0
- Update cets-0.3.0
- Update cowboy-2.12.0, cowlib-2.13.0
- Update hackney-1.20.1, certifi-2.12.0, mimerl-1.3.0, ssl_verify_fun-1.1.7
- Update cowboy_swagger-2.7.0, trails-2.3.1
- Update eredis-1.7.1, erlcloud-3.8.1, lhttpc-1.7.1
- Update recon-2.5.6, observer_cli-1.8.0, erlang_doctor-0.2.7
- Override config of `cpool` to upgrade `backoff` to version 1.1.6
- Override configs to remove rebar3_archive_plugin, rebar3_elvis_plugin from `prometheus_cowboy`, `prometheus_httpd` and `accept`
- Update erl_csv-0.3.3
- Update gun-2.1.0
- Update amqp_client-4.0.3, rabbit_common-4.0.3
- Add rabbit_common to `plt_extra_apps`, so that dialyzer will recognize extra types
- Update deps for big_tests

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/248758) / elasticsearch_and_cassandra_mnesia / c4f35e8962b1ed26691dcb95525641649f8111d4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/248758/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/248758/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%409cbd655f4806.2024-12-10_21.54.38/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/248858) / elasticsearch_and_cassandra_mnesia / 411cd0b4875711b6363b304886af89129a562315
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/248858/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/248858/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4040cbb7a72832.2024-12-11_09.20.24/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/249133) / elasticsearch_and_cassandra_mnesia / 26ebd0d4bdd5ee2ccd9b06cc9214116511b1f7d2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/249133/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/249133/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%402c13243f3e3d.2024-12-11_12.42.18/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/249220) / elasticsearch_and_cassandra_mnesia / 64d62023ef0c8cae93e83f01890da990f67a1f88
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/249220/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/249220/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40ba4a8a4e32ad.2024-12-11_13.47.56/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/249249) / elasticsearch_and_cassandra_mnesia / 6071cd5dcbde2db6c8c181449af8433899ea8085
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/249249/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/249249/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40e72f5837439c.2024-12-11_14.42.11/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by NelsonVides** [comment]
Btw, what about `big_tests/rebar.config` and `big_tests/rebar.lock`? Don't we want to update those too maybe? :)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/249750) / elasticsearch_and_cassandra_mnesia / 315bed3d51f13c2fb5a6be3e99b2d979fcea0f25
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/249750/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/249750/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4049c3a8859a10.2024-12-12_16.04.53/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/249844) / elasticsearch_and_cassandra_mnesia / 977aaa2416de874cc1e71be37dbf29fb127582d6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/249844/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/249844/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%406422de0015e8.2024-12-12_16.12.55/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/250582) / elasticsearch_and_cassandra_mnesia / 1a8c35b7464b2c4c53b18de2e626ae162763e85d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/250582/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/250582/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4051811d20c9a6.2024-12-13_10.40.59/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[internal_mnesia_27](https://circleci.com/gh/esl/MongooseIM/250608) / internal_mnesia / 1a8c35b7464b2c4c53b18de2e626ae162763e85d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4428/250608/internal_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4428/250608/internal_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%402a9cc0856a4b.2024-12-13_11.19.23/index.html)
**OK: 117** / Failed: 0 / **User-skipped: 2** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
okk

**Comment by arcusfelis** [comment]
I will rerun tests to see that mongoose-im comment contains info from all jobs.
And will merge after.

**Comment by telezynski** [comment]
I have deleted CircleCI reports because there were too many of them:
```
tools/circle-publish-github-comment.sh: line 204: /usr/bin/curl: Argument list too long

Exited with code exit status 126
```

**Pull request merged**
