### PR TITLE
Don't create /usr/lib/mongooseim, because it already exists

### PR DESCRIPTION
**Pull request by chrzaszcz**
This issue affected Debian/Ubuntu, resulting in warnings being printed out on installation.

- Don't create `/usr/lib/mongooseim`, because it already exists
- Don't truncate Docker logs - to be able to check the output.

I verified manually, that the issue was present for Debian/Ubuntu before the fix, and that it is gone after the fix (see the [CI workflow](https://app.circleci.com/pipelines/github/esl/MongooseIM/13363/workflows/e60f0474-90b9-4aac-9d8d-7209fed8650d) with packages enabled).

**Note:** I decided not to add automatic tests. We could add a condition to fail if anything is printed to `stderr`, but for me it might be too restrictive, i.e. there might be some unrelated output. I think we could add an automatic check later if we find any similar issue.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/244742) / elasticsearch_and_cassandra_mnesia / 2142c2a6d40aad109a4918a493ab165a41b7ad11
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4410/244742/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4410/244742/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4027810f907798.2024-12-03_13.38.00/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/247941) / elasticsearch_and_cassandra_mnesia / a93c3369a670bc5f376f0706eb687d4a4e04ed55
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4410/247941/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4410/247941/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40091afd87ebf9.2024-12-06_12.51.44/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/248184) / elasticsearch_and_cassandra_mnesia / 6e5bbfc6b6429bf4f40a366a314ec0fd834f5e9a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4410/248184/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4410/248184/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40425f1b5f4bc6.2024-12-06_16.20.41/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/248227) / elasticsearch_and_cassandra_mnesia / 6ed31092c4ecc28706674a7acc3f763fa028872a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4410/248227/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4410/248227/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%404525ad403caf.2024-12-09_07.56.19/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by jacekwegr — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
