### PR TITLE
Remove pull-db.sh

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses #

Proposed changes include:
* describe the functionality changes
* describe new or updated tests
* describe changes to the documentation

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/66256) / small_tests / f57f01a7b0d2ab3bab6926988ad9ed6bfd5eb85d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3207/66256/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3207/66256/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-04_07.14.04/lib.mongooseim.logs/run.2021-08-04_07.14.05/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
👌🏽

**Review by NelsonVides — APPROVED** [review]
Riiiiiight... 😆

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/66300) / small_tests / 91f42c86c652229d2c3baa06f310f271ffeaf5ed
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3207/66300/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3207/66300/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-04_15.05.29/lib.mongooseim.logs/run.2021-08-04_15.05.30/suite.log.html)

**Review by vkatsuba — APPROVED** [review]

**Pull request merged**
