### PR TITLE
Docker stages build

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "the current process of working with docker build script is very time consuming".

Proposed changes include:
* You can now test it locally easily
* No need to use two git repositories
* Very reproducable results

Based partcially on @NelsonVides code.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163031) / small_tests / 9126a222aa7246210b7f771947760655c0602e54
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3945/163031/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3945/163031/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-26_11.25.41/lib.mongooseim.logs/run.2023-01-26_11.25.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163081) / small_tests / 60ae4d3c624cc6ff785c42ee31f86c355b200b3a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3945/163081/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3945/163081/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-26_12.02.09/lib.mongooseim.logs/run.2023-01-26_12.02.09/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163111) / small_tests / f790844b83b667b5e9b29442924d8edeed6ca596
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3945/163111/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3945/163111/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-26_12.11.54/lib.mongooseim.logs/run.2023-01-26_12.11.55/suite.log.html)

**Comment by arcusfelis** [comment]
Cool prototype, but it runs 4 minutes instead of 40 seconds now.
Even with official erlang image (which avoids setting up ESL package which depends on a lot of xorg stuff).

So, closing for now.

**Pull request closed without merging**
