### PR TITLE
Fix external component disconnect over websocket

### PR DESCRIPTION
**Pull request by igors**
This PR addresses #1104

Proposed changes include:
* ejabberd_service now monitors the (cowboy web)socket process and terminates itself when the monitor is triggered. This causes the route to be unregistered so the external component will be accepted without conflict when it connects again.

This is effectively equivalent to ejabberd_c2s behavior - it also uses the monitor to detect that web socket is closed.

### CODE REVIEW

**Comment by michalwski** [comment]
Thanks for your contribution. It's very valuable. Any chance you can add a test case for this somewhere in [component_SUITE](https://github.com/esl/MongooseIM/blob/3ebec10b62e3b845e27da49a0f57d70447865d3d/test/ejabberd_tests/tests/component_SUITE.erl)?

A generic test case for TCP (group xep0114_tcp) and WS (group xep0014_ws) connections would be perfect. In this test case you could close the connection abnormally (by f.e killing relevant escalus process)  and reconnecting again. With your fix the reconnection should work.

**Comment by igors** [comment]
So I tried to add a test case as you suggested. Unfortunately, escalus_ws:kill is not implemented (or, rather, implemented to call error/2) so calling it triggers a test failure; I tried just calling exit(SocketPid, kill) on websocket process but that's somehow caught by the test framework and reported as a test failure with "testcase_aborted_or_killed" reason.

**Comment by igors** [comment]
I also tried changing implementation of `escalus_ws:kill` to just return `{stop, normal, ok, S}` - that seems to work but
a) I'm not entirely sure if this is the best way to kill an escalus websocket connection; e.g., this still sends a websocket close, which is fine for this test case but you might want `kill` to just blindly close the socket
b) you'd need to pull that change into escalus and repoint rebar.config to use the version with that fix.

**Comment by igors** [comment]
Just to give you an idea of what I had in mind:

The change to escalus_ws: https://github.com/igors/escalus/commit/bd06c03402328fafe87dd22ab32e25bfeb95f580
The change to component_SUITE: https://github.com/igors/MongooseIM/commit/b3371ab64a7dc214ad8ed5deac307398f70192ca

Let me know if I am completely off the track or there is a better way to do that.

**Comment by michalwski** [comment]
Thanks for the update @igors. The change in the `component_SUITE` is exactly what I meant. Regarding `escalus_ws` - I didn't remember the `kill` function is not implemented. You are right saying that it'd be better to blindly close the connection without sending `close`. This would required changing the websocket library - `wsecli`. I think we can live with this for now.

Could you open a PR to escalus? after I merge it you can add your test cases and change the reference to escalus.

**Comment by igors** [comment]
Done - travis will probably keep failing until https://github.com/esl/escalus/pull/131 is pulled in. Should I just point to that particular commit in rebar.config or wait until there is a new escalus release?

**Comment by michalwski** [comment]
You can point to the merge commit esl/escalus@e1eca08218c21f1ac9d45431194e4463119efff6 in rebar.config

**Comment by igors** [comment]
Done - rebased the last commit to include the change to escalus version in rebar.config.

**Comment by michalwski** [comment]
Thanks a lot @igors!

**Pull request merged**
