### PR TITLE
Use dynamic_modules in big tests

### PR DESCRIPTION
**Pull request by chrzaszcz**
Do not use `gen_mod` directly to start and stop modules in tests.
Use the `dynamic_modules` API instead.

These changes make it possible to modify the module management logic without any changes in the test suites - only the `dynamic_domains` helper will be modified.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97345) / small_tests / 28d820cfffc11b2e055ae36e5652788ce042e582
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97345/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97345/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-28_09.03.13/lib.mongooseim.logs/run.2021-12-28_09.03.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97375) / small_tests / f0ace65f4021389313dc0d578670d96e6c8c9407
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97375/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97375/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-28_09.13.30/lib.mongooseim.logs/run.2021-12-28_09.13.30/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97495) / small_tests / 856b659dc92eb9bf9d50df6c7c725e18c0217193
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97495/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97495/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-28_16.06.50/lib.mongooseim.logs/run.2021-12-28_16.06.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97520) / small_tests / f84c4b377ee3c756eaa194bb7a148104df27d499
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97520/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97520/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-28_17.08.29/lib.mongooseim.logs/run.2021-12-28_17.08.30/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97544) / small_tests / 2c18e076fd27432436a6b3510ebf7bc8091f36a6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97544/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97544/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_07.09.19/lib.mongooseim.logs/run.2021-12-29_07.09.19/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97563) / small_tests / 6b56becc0cc43985c943e7934c46d57c05ba497f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97563/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97563/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_07.21.42/lib.mongooseim.logs/run.2021-12-29_07.21.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97600) / small_tests / 6ddf958109a08a74f8e876f6d470d1b9a6711019
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97600/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97600/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_07.51.41/lib.mongooseim.logs/run.2021-12-29_07.51.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97624) / small_tests / e6f493443f647920ce4ed00dee77c4d12642c9a8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97624/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97624/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_08.53.20/lib.mongooseim.logs/run.2021-12-29_08.53.21/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97649) / small_tests / 08d60aba72afa4d9b032a568b46ed66802e79ce9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97649/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97649/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_08.59.00/lib.mongooseim.logs/run.2021-12-29_08.59.01/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97658) / small_tests / 41085f16661e55391945da24e1f1787ed91fdd96
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97658/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97658/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_09.24.37/lib.mongooseim.logs/run.2021-12-29_09.24.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/97686) / small_tests / 8c490cd2f6619dba015632404d292c8f8bb4e179
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3481/97686/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3481/97686/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-29_10.34.23/lib.mongooseim.logs/run.2021-12-29_10.34.24/suite.log.html)

**Review by arcusfelis — APPROVED** [review]

**Pull request merged**
