### PR TITLE
Ci/docker

### PR DESCRIPTION
**Pull request by NelsonVides**
In this PR I'm going to try to migrate at least some jobs to docker runners in CircleCI, like dialyzer, small_tests, and packages.

* Some unused files were deleted, travis relics (cache-[build|tests|certs].sh)
* awscli is not installed by default in the docker containers, so selectively install it
* `certs` preset in the main makefile now detects if the certificates are about to expire in the next hour, if so, they're deleted and recreated automatically.
* Plenty of changes to `.circleci/config.yml`
  * Orb was removed, that was totally unnecessary for us. This unfortunately means a huge diff because of indentation. But this change is applied only on the first commit.
  * More commands were added, to improve repeating code.

Note that many jobs still run the old way, so this doesn't reduce the overall duration of CI. [But some jobs are much faster](https://app.circleci.com/pipelines/github/esl/MongooseIM/4978/workflows/7863de53-6a74-4a8c-9924-bf5e661f112c): `otp_23` build job usually takes around 10min, while `otp_23_docker` takes 5-6min. On top of the later, `small_tests_23` takes 8min and `dialyzer` <2min, compared to the previous 11min and 13min [on master](https://app.circleci.com/pipelines/github/esl/MongooseIM/4950/workflows/b258f878-ea4c-4258-b9bf-effee66af83b)

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_21_3](https://circleci.com/gh/esl/MongooseIM/61802) / small_tests / 5b6ee312c69bc2ebf343811c17a560ec52660fca
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/61802/small_tests.21.3.8.17-1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/61802/small_tests.21.3.8.17-1/small/ct_run.mongooseim@localhost.2021-07-13_11.58.21/lib.mongooseim.logs/run.2021-07-13_11.58.21/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/61843) / small_tests / 1cda5012d97b67789a6e538a9d6c011d6803a791
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/61843/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/61843/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-13_12.41.08/lib.mongooseim.logs/run.2021-07-13_12.41.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/61873) / small_tests / c6423f8843e5dda532f5274e1fb2578299238d63
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/61873/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/61873/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-13_13.02.25/lib.mongooseim.logs/run.2021-07-13_13.02.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/61898) / small_tests / 5d24d066df3a995b7e474857ce9c45c3001788b2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/61898/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/61898/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-13_13.16.00/lib.mongooseim.logs/run.2021-07-13_13.16.00/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/61952) / small_tests / c654515d200be37893524a351120a90a59e6c619
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/61952/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/61952/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-13_15.44.29/lib.mongooseim.logs/run.2021-07-13_15.44.29/suite.log.html)

**Comment by mongoose-im** [comment]
[ldap_mnesia_22](https://circleci.com/gh/esl/MongooseIM/62037) / ldap_mnesia / cd73b160eb726d7b2bdf59cd6cddfb68219226f1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62037/ldap_mnesia.22.3.4.9-1)

**Comment by mongoose-im** [comment]
[ldap_mnesia_21](https://circleci.com/gh/esl/MongooseIM/62067) / ldap_mnesia / 24093d48d437e3f6b096645b837cddf6771941dd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62067/ldap_mnesia.21.3.8.17-1)

**Comment by mongoose-im** [comment]
[ldap_mnesia_21](https://circleci.com/gh/esl/MongooseIM/62078) / ldap_mnesia / ae1fa695e74a33e815e74098cdbf9c0fcefa191d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62078/ldap_mnesia.21.3.8.17-1)

**Comment by mongoose-im** [comment]
[ldap_mnesia_21](https://circleci.com/gh/esl/MongooseIM/62100) / ldap_mnesia / 07df7ca5303741cc3436dc8ef0029aa347f8796d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62100/ldap_mnesia.21.3.8.17-1)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62147) / small_tests / 90da35f92887b9cf144be8f78eb606ae49c569c7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62147/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/62147/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-13_22.33.05/lib.mongooseim.logs/run.2021-07-13_22.33.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62289) / small_tests / ef22b7af6b1a002480cf12eb94546e0731d1ba57
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62289/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/62289/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-14_07.36.53/lib.mongooseim.logs/run.2021-07-14_07.36.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62421) / small_tests / 7f9855091fe53b4c889c1b96e04345e1a2ab0efe
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62421/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/62421/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-14_09.51.29/lib.mongooseim.logs/run.2021-07-14_09.51.29/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62435) / small_tests / 6748350b40a33aa7b7acce2c12f372ab85291015
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3183/62435/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3183/62435/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-14_09.55.02/lib.mongooseim.logs/run.2021-07-14_09.55.03/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Great work, I like the cert check and removing unused files.
Do you think that the remaining jobs can be converted to use Docker as well?

**Comment by NelsonVides** [comment]
> Great work, I like the cert check and removing unused files.
> Do you think that the remaining jobs can be converted to use Docker as well?

All the others, totally, but they'll need to rework the whole ssl configuration and scripts with the pools, and that'll get quite more complex, so maybe for the future.

**Pull request merged**
