### PR TITLE
Do not recreate accumulator when sending out a stanza

### PR DESCRIPTION
**Pull request by bartekgorny**
In current implementation, `ejabberd_c2s:send_element/3` receives an accumulator, but it never is the original one. The old one is dropped in `ejabberd_c2s:send_and_maybe_buffer_stanza/3`, and a while later a new one is created in `ejabberd_c2s:send_element_from_server_jid/2`. Trying to trace or profile from `ejabberd_c2s:send_element/3` gives rather unexpected results. This PR fixed the issue by passing the original accumulator on.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[5985.1](https://travis-ci.org/esl/MongooseIM/jobs/464495792) / Erlang 19.3 / small_tests / 72646f17e69830432f8b98cb7f10770db0fbd36b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2158/5985/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2158/5985/small_tests.19.3/small/ct_run.mongooseim@localhost.2018-12-06_17.23.09/lib.mongooseim.logs/run.2018-12-06_17.23.10/suite.log.html)

**Comment by mongoose-im** [comment]
[7424.1](https://travis-ci.org/esl/MongooseIM/jobs/607161742) / Erlang 22.0 / small_tests / 08a94ef109b6e69eb0f3c6e49fdf395e3f6be419
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2158/7424/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2158/7424/small_tests.22.0/small/ct_run.mongooseim@localhost.2019-11-04_14.24.57/lib.mongooseim.logs/run.2019-11-04_14.24.57/suite.log.html)

**Comment by bartekgorny** [comment]
There are still some failures but they seem to be random, if I'm not mistaken.

**Comment by NelsonVides** [comment]
> There are still some failures but they seem to be random, if I'm not mistaken.

@michalwski @bartekgorny But why random failures are now an acceptable thing? 😢

**Comment by michalwski** [comment]
@NelsonVides that's my bad. I didn't notice the random failures before merge. I give @bartekgorny a chance to fix them tomorrow. If not I revert the changes.

**Comment by bartekgorny** [comment]
> > There are still some failures but they seem to be random, if I'm not mistaken.
> 
> @michalwski @bartekgorny But why random failures are now an acceptable thing? 😢

Why do we have `repeat_until_all_ok` if they are not? Perhaps we should remove it from tests, then.

**Comment by bartekgorny** [comment]
> @NelsonVides that's my bad. I didn't notice the random failures before merge. I give @bartekgorny a chance to fix them tomorrow. If not I revert the changes.

 I'm on it, but it is a tricky beast.

**Comment by bartekgorny** [comment]
> > > There are still some failures but they seem to be random, if I'm not mistaken.
> > 
> > 
> > @michalwski @bartekgorny But why random failures are now an acceptable thing? 😢
> 
> Why do we have `repeat_until_all_ok` if they are not? Perhaps we should remove it from tests, then.

I think we should. There is an outright bug, which breaks tests only randomly...

**Comment by NelsonVides** [comment]
> > > > There are still some failures but they seem to be random, if I'm not mistaken.
> > > 
> > > 
> > > @michalwski @bartekgorny But why random failures are now an acceptable thing? 😢
> > 
> > 
> > Why do we have `repeat_until_all_ok` if they are not? Perhaps we should remove it from tests, then.
> 
> I think we should. There is an outright bug, which breaks tests only randomly...

I absolutely agree, I never liked to mask failures by repeating them. These tests should be deterministic.

**Pull request merged**
