### PR TITLE
Fast and unsafe db backends for CI

### PR DESCRIPTION
**Pull request by arcusfelis**
Proposed changes include:
* some optimizations

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/91588) / small_tests / b422cf0a6f00c5590ffe203de6aa65fdca2482b6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3427/91588/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3427/91588/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-01_15.05.44/lib.mongooseim.logs/run.2021-12-01_15.05.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/91691) / small_tests / a905800e72e669338d5039b5a9a57442a7c4ce45
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3427/91691/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3427/91691/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-01_16.29.25/lib.mongooseim.logs/run.2021-12-01_16.29.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/91728) / small_tests / 336548053de869d5854934347649d807a3358f24
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3427/91728/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3427/91728/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-01_16.54.02/lib.mongooseim.logs/run.2021-12-01_16.54.02/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
Please, give some information - why is this needed, what's the benefit, is this also recommended for production setups? Is it connected to any issue?

**Pull request closed without merging**
