### PR TITLE
eunit execution in CI tests

### PR DESCRIPTION
**Pull request by DenysGonchar**
This PR is done in a context of this issue https://github.com/esl/MongooseIM/issues/2844

There is no integration of eunit execution into `test-runner.sh` script (no dedicated options to control it).  to run eunit tests you can use `make eunit` or `./rebar3 eunit` command

However, `test-runner.sh` can be used for quick manual testing of the changes in `travis-test.sh`. For that you have set  `EUNIT_TESTS` env variable. 
```
EUNIT_TESTS=true test-runner.sh --skip-big-tests --skip-small-tests --skip-build-mim --skip-build-tests
```

eunit tests are triggered for `small_tests` CI jobs on Travis and CircrleCI. the summary of execution is printed in the console.

the full log is uploaded to AWS in the `logs` directory (e.g. see `eunit.log` file [here](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8528/small_tests.23.0.3/logs/2020-09-04_18.07.34/)). no changes were required for log uploading, it's done automatically for all `*.log` files in the git repo root directory (see `travis-prepare-log-dir.sh` & `circleci-prepare-log-dir.sh` and scripts).

### CODE REVIEW

**Comment by mongoose-im** [comment]
[8525.1](https://travis-ci.org/esl/MongooseIM/jobs/724209905) / Erlang 23.0.3 / small_tests / 76329e3bf05594f50b85e85284dd7f61466c21b9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8525/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8525/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_15.31.57/lib.mongooseim.logs/run.2020-09-04_15.31.58/suite.log.html)

**Comment by mongoose-im** [comment]
[8526.1](https://travis-ci.org/esl/MongooseIM/jobs/724232389) / Erlang 23.0.3 / small_tests / 4b322266c9289393d800d117bb22fb6873ce0666
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8526/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8526/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_16.42.26/lib.mongooseim.logs/run.2020-09-04_16.42.26/suite.log.html)

**Comment by mongoose-im** [comment]
[8526.9](https://travis-ci.org/esl/MongooseIM/jobs/724232397) / Erlang 22.3 / pgsql_mnesia / 4b322266c9289393d800d117bb22fb6873ce0666
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8526/pgsql_mnesia.22.3)/ [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8526/pgsql_mnesia.22.3/big/ct_run.test%40travis-job-c9109b76-ed2f-46f3-97e9-9c5994a44bcd.2020-09-04_17.14.55/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8526/pgsql_mnesia.22.3/small/ct_run.mongooseim@localhost.2020-09-04_17.08.34/lib.mongooseim.logs/run.2020-09-04_17.08.34/suite.log.html)
**OK: 2754** / Failed: 0 / **User-skipped: 215** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[8527.1](https://travis-ci.org/esl/MongooseIM/jobs/724245555) / Erlang 23.0.3 / small_tests / 0112b858fc1932775b9759b42be0e9db6e5733f9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8527/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8527/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_17.26.45/lib.mongooseim.logs/run.2020-09-04_17.26.45/suite.log.html)

**Comment by mongoose-im** [comment]
[8528.1](https://travis-ci.org/esl/MongooseIM/jobs/724250170) / Erlang 23.0.3 / small_tests / 527f5c0df183c2dc9e71b31e5df2205831e1ef38
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8528/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8528/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_18.01.17/lib.mongooseim.logs/run.2020-09-04_18.01.18/suite.log.html)

**Comment by mongoose-im** [comment]
[8529.1](https://travis-ci.org/esl/MongooseIM/jobs/724285031) / Erlang 23.0.3 / small_tests / 3ccbc10705418bd4a48d42b9de89b5f8e3adf436
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8529/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8529/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_19.56.11/lib.mongooseim.logs/run.2020-09-04_19.56.11/suite.log.html)

**Comment by mongoose-im** [comment]
[8530.1](https://travis-ci.org/esl/MongooseIM/jobs/724301521) / Erlang 23.0.3 / small_tests / a885f8f6b2b0b431309afc7c53d43c96a1b70ad0
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2860/8530/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2860/8530/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-04_20.54.19/lib.mongooseim.logs/run.2020-09-04_20.54.20/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Excellent changes, very consistent and readable changes, useful addition. Thanks! 🎉

**Pull request merged**
