### PR TITLE
GraphQL CLI args as "--name value" with new help

### PR DESCRIPTION
**Pull request by chrzaszcz**
There are two main goals of this PR:

### 1. Change the argument format
The previous argument format for the GraphQL-based CLI was always JSON, which a bit difficult to use. For example, this is how you would ask for the number of users in a domain:

```
mongooseimctl account listUsers '{"domain": "localhost"}'
```

This is how you do it after the change:

```
mongooseimctl account listUsers --domain localhost
```

Strings and integers are automatically processed, so they don't need quoting (unless the string has special characters or spaces).
Arguments with complex types (lists, input objects) need to be passed as JSON.

### 2. Provide help for the new commands

The new commands are to replace the old ones, which used `admin_extra`.
- `mongooseimctl` on its own displays a list of categories, basic commands (not categorized) and general help.
- `mongooseimctl help` displays the old-style help with all deprecated commands, which are still supported.
- `mongooseimctl categoryName` displays a list of commands with descriptions.
- `mongooseimctl categoryName commandName --help` displays a list of arguments with descriptions. `--help` is required for argument-less commands, because otherwise they would be executed. For other commands you can omit `--help`.
- Errors in the command line should result in user-friendly help.

There is more information displayed, please try it for yourself. Some examples are shown below, but the formatting is better in the shell.

<details><summary><code>mongooseimctl</code></summary>
<pre>Usage: <b>mongooseimctl</b> [<u style="text-decoration-style:single">category</u>] <u style="text-decoration-style:single">command</u> [<u style="text-decoration-style:single">arguments</u>]

Most MongooseIM commands are grouped into the following categories:
  <b>account</b>     Account management 
  <b>domain</b>      Domain management 
  <b>gdpr</b>        Personal data management according to GDPR 
  <b>httpUpload</b>  Http upload 
  <b>inbox</b>       Inbox bin management 
  <b>last</b>        Last activity management 
  <b>metric</b>      Metrics management 
  <b>muc</b>         MUC room management 
  <b>muc_light</b>   MUC Light room management 
  <b>offline</b>     Offline deleting old messages 
  <b>private</b>     Private storage management 
  <b>roster</b>      Roster/Contacts management 
  <b>session</b>     Session management 
  <b>stanza</b>      Stanza management 
  <b>stat</b>        Statistics 
  <b>token</b>       OAUTH token management 
  <b>vcard</b>       Vcard management 

To list the commands in a particular category:
  mongooseimctl <u style="text-decoration-style:single">category</u>

The following basic system management commands do not have a category:
  <b>graphql</b> <u style="text-decoration-style:single">query</u>                Execute graphql query or mutation 
  <b>help</b> <u style="text-decoration-style:single">[--tags [tag] | com?*]</u>  Show help for the deprecated commands 
  <b>mnesia</b> <u style="text-decoration-style:single">[info]</u>                show information of Mnesia system 
  <b>restart</b>                      Restart MongooseIM 
  <b>status</b>                       Get MongooseIM status 
  <b>stop</b>                         Stop MongooseIM 

Commands to start a MongooseIM node:
  start           Start a MongooseIM node as daemon (detached from terminal)
  debug           Attach an interactive Erlang shell to a running MongooseIM node
  live            Start MongooseIM node in live (interactive) mode
  foreground      Start MongooseIM node in foreground (non-interactive) mode
MongooseIM cluster management commands:
  join_cluster other_node_name                Add current node to cluster
  leave_cluster                               Make the current node leave the cluster
  remove_from_cluster other_node_name         Remove dead node from the cluster
Extra Commands:
  bootstrap           Executes MongooseIM init scripts (used for initial configuration)
  print_install_dir   Prints path to MongooseIM release directory
  escript             Runs escript command using embedded Erlang Runtime System
</pre></details>

<details><summary><code>mongooseimctl account</code></summary>
<pre>The following commands are available in the category &apos;account&apos;:
  <b>banUser</b>             Ban an account: kick sessions and set a random password 
  <b>changeUserPassword</b>  Change the password of a user 
  <b>checkPassword</b>       Check if a password is correct 
  <b>checkPasswordHash</b>   Check if a password hash is correct (allowed methods: md5, sha). Works only for a plain passwords 
  <b>checkUser</b>           Check if a user exists 
  <b>countUsers</b>          Get number of users per domain 
  <b>listUsers</b>           List users per domain 
  <b>registerUser</b>        Register a user. Username will be generated when skipped 
  <b>removeUser</b>          Remove a user 

To list the arguments for a particular command:
  mongooseimctl account <u style="text-decoration-style:single">command</u> --help
</pre></details>

<details><summary><code>mongooseimctl account listUsers</code></summary>
<pre>Missing mandatory arguments for command &apos;listUsers&apos;: &apos;domain&apos;

Usage: <b>mongooseimctl</b> account listUsers <u style="text-decoration-style:single">arguments</u>

Each argument has the format: --<u style="text-decoration-style:single">name</u> <u style="text-decoration-style:single">value</u>
Available arguments are listed below with the corresponding GraphQL types:
  <b>domain</b>  String! 

Scalar values do not need quoting unless they contain special characters or spaces.
Complex input types are passed as JSON maps or lists, depending on the type.
When a type is followed by &apos;!&apos;, the corresponding argument is required.
</pre></details>

### CODE REVIEW

**Comment by mongoose-im** [comment]
[pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/131383) / pgsql_mnesia / 2f749f90fcb5d71807d54adf26266bbd3a8b2c4c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131383/pgsql_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/131406) / small_tests / 0ec7cd7006208fa8c55443ccc3659144e66a38ae
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131406/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/131406/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-05_14.21.35/lib.mongooseim.logs/run.2022-08-05_14.21.36/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/131424) / small_tests / 9e78cc5b3abf67746080685b4755d2f4617ff75a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131424/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/131424/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-05_14.22.47/lib.mongooseim.logs/run.2022-08-05_14.22.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/131518) / small_tests / 32ff3ef997bd7383f7b28e732eddf44d31e3180a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131518/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/131518/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-08_14.27.17/lib.mongooseim.logs/run.2022-08-08_14.27.18/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/131619) / small_tests / ac5296a87ed1d47301471b3038df9e1c5227a42e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131619/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/131619/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-09_14.34.50/lib.mongooseim.logs/run.2022-08-09_14.34.50/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/131995) / small_tests / 51928d4b798f52fa3ec141f64d59bb49f1990357
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/131995/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/131995/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_10.32.22/lib.mongooseim.logs/run.2022-08-11_10.32.23/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132022) / small_tests / b758546c4d308783e4da6d90f92576b023f3feb0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132022/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132022/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_11.19.46/lib.mongooseim.logs/run.2022-08-11_11.19.46/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132045) / small_tests / 7ad6f38ba3db7dbfdce5f48b1adcce313b6ebec5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132045/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132045/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_11.43.00/lib.mongooseim.logs/run.2022-08-11_11.43.00/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132076) / small_tests / 2ecbc96d499b1807174c1aa19473475ba67ab6dc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132076/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132076/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_12.02.23/lib.mongooseim.logs/run.2022-08-11_12.02.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132279) / small_tests / 420ac4ecdc5926274268101a07ed80dab422d96a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132279/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132279/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_14.36.38/lib.mongooseim.logs/run.2022-08-11_14.36.39/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132285) / small_tests / 39dc603eca07dddbae17c02dde6d46ef01d70123
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132285/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132285/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-11_14.38.03/lib.mongooseim.logs/run.2022-08-11_14.38.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132416) / small_tests / 57018087e4468ab533e5db3586798882e4f14d4a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132416/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132416/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_11.06.36/lib.mongooseim.logs/run.2022-08-12_11.06.37/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132497) / small_tests / 5820056b7c19b04f36e92bb18e93f9c9cdd0b44a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132497/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132497/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_12.34.58/lib.mongooseim.logs/run.2022-08-12_12.34.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/132577) / small_tests / 42c2401a6a723e7a6debc860acbca8954eddbc89
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3724/132577/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3724/132577/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-12_13.34.11/lib.mongooseim.logs/run.2022-08-12_13.34.11/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
