### PR TITLE
Add thread and parent thread to client api

### PR DESCRIPTION
**Pull request by imcyee**
Add support XEP-0201 https://xmpp.org/extensions/xep-0201.html to client api for message

This PR addresses #
Add thread and parent thread to client api

### CODE REVIEW

**Comment by vkatsuba** [comment]
Hi @imcyee, thanks for your contribution. In current implementation is missed test cases for new fields. Other important point is that options like `thread` and `parent` is mandatory, which means that everyone who uses this API on the side of client applications, after merging this PR, will have to update all applications too. I believe that those options should not be required and old implementation should work as with as without those new options. Other point is common tests should be expanded. But please also note that in the near future the API client will be completely rewritten, perhaps by this reason this PR will not be accepted.

**Review by vkatsuba — CHANGES_REQUESTED** [review]
Tests cases is missed. Common tests should be expanded and should cover the work of API both with and without new parameters.

**Comment by imcyee** [comment]
@vkatsuba 
`In current implementation is missed test cases for new fields.`
I can add missed test cases after getting your input on it (with my limited Erlang but I will try.)

`everyone who uses this API on the side of client applications, after merging this PR, will have to update all applications too`
Maybe I missed anything, because it seems that it is just another field in json like `id` of `origin-id`. If not supplied, it will be 'undefined'. If client doesn't require it, then they can simply ignore it. Or have I missed a bigger picture?

**Comment by vkatsuba** [comment]
@imcyee in order to be completely confident, need to have tests cases. Could you please run GitHub Actions in https://github.com/imcyee/MongooseIM/actions for check current behavior, select CI -> in `Run workflow.` select your branch ->  and press button `Run workflow`?

**Comment by imcyee** [comment]
> Tests cases is missed. Common tests should be expanded and should cover the work of API both with and without new parameters.

Okay, would you mind point a little direction for me. I found could be test in `rest_client_SUITE.erl` and `rest_SUITE.erl` in bigtest. Thinking if there is example file i can refer with my test.

I will give it a sample, if I am in the right direction.
msg_with_thread_is_sent_and_delivered_over_xmpp(Config) ->
    escalus:fresh_story(Config, [{alice, 1}, {bob, 1}], fun(Alice, Bob) ->
        BobJID = user_jid(Bob),
        MsgID = base16:encode(crypto:strong_rand_bytes(5)),
        M1 = rest_helper:make_msg_stanza_with_props(BobJID,MsgID),

        escalus:send(Alice, M1),

        M2 = escalus:wait_for_stanza(Bob),
        escalus:assert(is_message, M2)
    end).

**Comment by imcyee** [comment]
Accidentally close. Reopen.

**Comment by imcyee** [comment]
> @imcyee in order to be completely confident, need to have tests cases. Could you please run GitHub Actions in https://github.com/imcyee/MongooseIM/actions for check current behavior, select `CI` -> in `Run workflow.` select your branch -> and press button `Run workflow`?

I have start the `Run workflow` at the mean time I will try add a test case in rest_client_SUITE.erl

**Comment by vkatsuba** [comment]
@imcyee as you can see in [GitHub Actions](https://github.com/imcyee/MongooseIM/actions/runs/1176780170), provided tests crashes what is related to latest changes:
```
Failed big cases:
mam_SUITE:rdbms_prefs_cases:prefs_set_request
rest_client_SUITE:messages:messages_can_be_paginated
rest_client_SUITE:messages:all_messages_are_archived
rest_client_SUITE:messages:messages_with_user_are_archived
rest_client_SUITE:messages:messages_can_be_paginated
rest_client_SUITE:messages:messages_with_user_are_archived
rest_client_SUITE:messages:all_messages_are_archived
rest_client_SUITE:messages:messages_can_be_paginated
rest_client_SUITE:messages:messages_with_user_are_archived
rest_client_SUITE:messages:all_messages_are_archived
rest_client_SUITE:messages_with_props:msg_with_malformed_props_can_be_parsed
rest_client_SUITE:messages_with_props:msg_with_malformed_props_can_be_parsed
rest_client_SUITE:messages_with_props:msg_with_malformed_props_can_be_parsed
```

**Comment by imcyee** [comment]
Ya, a lot of crashes. currently is checking on the crashes. 
Why is this code crashing it?
`
mapfromlist(L) ->
    Nl = lists:map(fun({K, {V}}) when is_list(V) ->
                           {binary_to_existing_atom(K, utf8), mapfromlist(V)};
                      ({K, V}) ->
                           {binary_to_existing_atom(K, utf8), V}
                   end, L),
    maps:from_list(Nl).

decode_maplist(Ml) ->
    [mapfromlist(L) || {L} <- Ml].
`

**Comment by imcyee** [comment]
I have submit another pull request, because this pr git is messy. 
https://github.com/esl/MongooseIM/pull/3236

**Pull request closed without merging**
