### PR TITLE
Update to OTP 23

### PR DESCRIPTION
**Pull request by gustawlippa**
This PR addresses [MIM-1102](https://erlangsolutions.atlassian.net/browse/MIM-1102)

After upgrading dependencies and removing `katt` OTP 23 should work just fine.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[8482.1](https://travis-ci.org/esl/MongooseIM/jobs/721253488) / Erlang 23.0.3 / small_tests / bc43e53faa6eeebacbe8ca1ce36164ac375d889c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2840/8482/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2840/8482/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-08-26_07.33.08/lib.mongooseim.logs/run.2020-08-26_07.33.09/suite.log.html)

**Comment by mongoose-im** [comment]
[8483.1](https://travis-ci.org/esl/MongooseIM/jobs/721273364) / Erlang 23.0.3 / small_tests / 58ae6c82a7bcaf1245cfc4c07a506d032291cafa
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2840/8483/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2840/8483/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-08-26_09.06.10/lib.mongooseim.logs/run.2020-08-26_09.06.10/suite.log.html)

**Comment by NelsonVides** [comment]
Great great great, so cool to see compatibility with OTP23! 💪 
Let's just wait for CI now and we merge 😄

**Comment by mongoose-im** [comment]
[8484.1](https://travis-ci.org/esl/MongooseIM/jobs/721278857) / Erlang 23.0.3 / small_tests / 9ba59bf9aaa0dc5b2040bc23b6fde7741b047448
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2840/8484/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2840/8484/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-08-26_09.39.45/lib.mongooseim.logs/run.2020-08-26_09.39.45/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Excellent, everything green 👏 🎉

**Pull request merged**
