### PR TITLE
Update big_tests deps

### PR DESCRIPTION
**Pull request by NelsonVides**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/63936) / small_tests / ec8ad80e603b290e9178b70e6dd2da8a7113bf2c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/63936/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/63936/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_09.49.25/lib.mongooseim.logs/run.2021-07-22_09.49.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64007) / small_tests / c1339cff22278101ad02f93fef9b7da8dda89f08
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64007/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64007/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_11.11.46/lib.mongooseim.logs/run.2021-07-22_11.11.46/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64056) / small_tests / 0c45a987095b90009fa315e834e8da604d9614a7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64056/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64056/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_12.01.50/lib.mongooseim.logs/run.2021-07-22_12.01.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64092) / small_tests / c309e8bdc87a3d86749ddbe67c20b431179f7cb0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64092/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64092/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_12.13.39/lib.mongooseim.logs/run.2021-07-22_12.13.40/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64132) / small_tests / a339ca07c4af5c91674bda6ed882e92bbb1d9361
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64132/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64132/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_12.39.08/lib.mongooseim.logs/run.2021-07-22_12.39.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64167) / small_tests / 5595b029aca31409c2df1c055a6afa1da0902442
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64167/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64167/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_13.18.16/lib.mongooseim.logs/run.2021-07-22_13.18.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64193) / small_tests / 015ec1c74fd0f9eb79abfbe52e91365bb38e11f6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64193/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64193/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_13.36.44/lib.mongooseim.logs/run.2021-07-22_13.36.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64242) / small_tests / 217a021df43600f308f3df7643f106610a51e1d0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64242/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64242/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_14.14.16/lib.mongooseim.logs/run.2021-07-22_14.14.16/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64267) / small_tests / fc1488af1f599dc92e850584e55fa8c82c664382
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64267/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64267/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_14.29.15/lib.mongooseim.logs/run.2021-07-22_14.29.15/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64293) / small_tests / b478d050f513b8ad85bf479974655c85166d90fc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64293/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64293/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_15.54.57/lib.mongooseim.logs/run.2021-07-22_15.54.58/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64318) / small_tests / 7057762e23f574f4561b05701a151406ff1df4ea
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64318/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64318/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_17.24.16/lib.mongooseim.logs/run.2021-07-22_17.24.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64341) / small_tests / 3d8e44fa5e2f23a122e2a3f088e7865578aeeefc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64341/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64341/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_18.07.13/lib.mongooseim.logs/run.2021-07-22_18.07.13/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/64367) / small_tests / e08e3e37ce431842dc93ad75472e20b1492dde0e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3192/64367/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3192/64367/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-22_18.54.39/lib.mongooseim.logs/run.2021-07-22_18.54.39/suite.log.html)

**Comment by vkatsuba** [comment]
Closed due to suggestion to update deps in separate PR's.

**Pull request closed without merging**
