### PR TITLE
Support dynamic domains in mod_last

### PR DESCRIPTION
**Pull request by chrzaszcz**
Add support for dynamic domains to `mod_last` and its backends.

Side changes:
- Fix error handling when updating last info. Previously the error tuple would result in `badmatch` as `Acc` was expected in both hooks.

This PR does **not** include:
- Supporting `remove_domain`.
- Migration guide.

Both tasks will be done separately.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62886) / small_tests / dabca02036e8979f64438d38e6577e6b76bfac4b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/62886/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/62886/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-15_14.18.48/lib.mongooseim.logs/run.2021-07-15_14.18.48/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/62974) / small_tests / bbcdce5f0308b9960ad3805b75ae35f135fb7653
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/62974/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/62974/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-16_06.52.56/lib.mongooseim.logs/run.2021-07-16_06.52.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_21_3](https://circleci.com/gh/esl/MongooseIM/64648) / small_tests / 9676977b6e6fee908f2060b9da50b43e38821c30
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/64648/small_tests.default)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/64823) / small_tests / e6c41538479bf2f004c5fadf69ff5707a53fdf87
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/64823/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/64823/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-27_06.32.17/lib.mongooseim.logs/run.2021-07-27_06.32.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/64920) / small_tests / 6c8bb5c63a29a8b2e5d1d4fafdeae8b103209a68
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/64920/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/64920/small_tests.23.1/small/ct_run.mongooseim@localhost.2021-07-27_07.59.29/lib.mongooseim.logs/run.2021-07-27_07.59.30/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/65061) / small_tests / 9ee98c8a728775a122a992956a56e02e091cd97b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/65061/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/65061/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-27_10.03.09/lib.mongooseim.logs/run.2021-07-27_10.03.09/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/65123) / small_tests / 90d615637bf3a41726dba4226ee1aa8618ef1f7c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/65123/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/65123/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-27_12.38.31/lib.mongooseim.logs/run.2021-07-27_12.38.31/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Simply neat, just one small comment 👌🏽

**Review by vkatsuba — APPROVED** [review]

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/65365) / small_tests / 21c00e58148cbd2e5ab6182b338aaa5a15dd6bd8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3188/65365/small_tests.24.0) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3188/65365/small_tests.24.0/small/ct_run.mongooseim@localhost.2021-07-28_06.21.41/lib.mongooseim.logs/run.2021-07-28_06.21.42/suite.log.html)

**Pull request merged**
