### PR TITLE
Instrument/hooks

### PR DESCRIPTION
**Pull request by chrzaszcz**
The main goal is to use `mongoose_instrument` instead of `mongoose_metrics` for the automatic hook metrics.

Main changes:
- `gen_hook` is using a new `mongoose_instrument_hooks` module to set up, tear down and execute events.
- Events are named `hook_HOOKNAME`, e.g. `hook_filter_packet`.
- Host type is a label, and this implies that if you try to set up both global and host-type-specific handlers for the same hook, it would result in an error. Such an error is caught and logged, but the handlers are set up anyway (as they were before). We could introduce a notion of scope defined statically per hook (global or host-type), but it would be a separate task - and a big one.
- The logic for skipping hooks is same as before, with the exception of `mam*_flush_messages` hooks, which are removed, because they were used only for instrumentation, and provided no value, because these operations are already instrumented.

Other minor changes are described in commit messages.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[ldap_mnesia_25](https://circleci.com/gh/esl/MongooseIM/220516) / ldap_mnesia / af5d56ed9dd6463ec089ae7782f4f9e858cb52fe
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220516/ldap_mnesia.25.3.2.9-amd64)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/220554) / elasticsearch_and_cassandra_mnesia / 38aa5888d510592f9ceec941d5c0f167e070a160
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220554/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4289/220554/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%400ae7aec66c0b.2024-05-31_06.24.30/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/220597) / elasticsearch_and_cassandra_mnesia / e5a5e341a824a258b7cc5de6bc55040eccada2f9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220597/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4289/220597/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40ed41f2bc72a5.2024-05-31_07.19.26/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/220686) / elasticsearch_and_cassandra_mnesia / 72aabea328109cdbbc829806c1928161affa38e4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220686/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4289/220686/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%402f55efa45978.2024-05-31_17.08.24/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/220730) / elasticsearch_and_cassandra_mnesia / 8981b8638f311623fbb75c7de4f4870aed88786a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220730/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4289/220730/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%400f2f6da0d51a.2024-06-03_06.32.23/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/220796) / elasticsearch_and_cassandra_mnesia / 4c4d89ddbeb3a14aea3afbfa00bfcc32677008ca
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4289/220796/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4289/220796/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40cfac9153dc35.2024-06-03_14.52.26/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good. Thanks for the changes.

**Pull request merged**
