### PR TITLE
Use escalus with new cleanup system

### PR DESCRIPTION
**Pull request by kanes115**
This PR uses new escalus version. https://github.com/esl/escalus/pull/182

### CODE REVIEW

**Comment by mongoose-im** [comment]
[4935.5](https://travis-ci.org/esl/MongooseIM/jobs/393560806) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / 6520ded7095a92a1a02b21a39d08ac1e8c6958d6
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4935/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4935/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-3188e15c-9963-4b9e-aa13-998532d2bb7f.2018-06-18_10.16.49/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4935/elasticsearch_and_cassandra_mnesia.19.3/small/ct_run.mongooseim@localhost.2018-06-18_10.10.03/lib.mongooseim.logs/run.2018-06-18_10.10.03/suite.log.html)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by kanes115** [comment]
@michalwski , ah, sorry... updating it

**Comment by mongoose-im** [comment]
[4937.5](https://travis-ci.org/esl/MongooseIM/jobs/393606596) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / 1642d4e6792967388202cc159bb0133795f8d8ad
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4937/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4937/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-583cb2b0-b07e-4a73-960e-0fdaf1869b68.2018-06-18_12.39.21/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4937/elasticsearch_and_cassandra_mnesia.19.3/small/ct_run.mongooseim@localhost.2018-06-18_12.32.35/lib.mongooseim.logs/run.2018-06-18_12.32.35/suite.log.html)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by michalwski** [comment]
@kanes115 I see there are some failures in users removal on `riak_mnesia` job (users are kept in riak in this PRESET). Can you take a look at it? You can unfold more details by clicking on the arrow on the left hand side of the suite and function name.

**Comment by mongoose-im** [comment]
[4939.5](https://travis-ci.org/esl/MongooseIM/jobs/393677773) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / a82e0987a59f2376747d333827b5cb445612d8b4
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4939/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4939/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-a0d60982-bb18-41f5-9113-11d5765e5107.2018-06-18_15.16.13/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4939/elasticsearch_and_cassandra_mnesia.19.3/small/ct_run.mongooseim@localhost.2018-06-18_15.09.27/lib.mongooseim.logs/run.2018-06-18_15.09.27/suite.log.html)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by michalwski** [comment]
@kanes115 I can see that in `mssql_mnesia` job there are some failures in `end_per_suite` due to failed unregistration.

**Comment by kanes115** [comment]
@michalwski I can see this, I'm on it

**Comment by mongoose-im** [comment]
[4940.5](https://travis-ci.org/esl/MongooseIM/jobs/393763587) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / 2720409441c061966078040cbd51d990675ce767
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4940/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4940/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-03a777cd-acf8-40a7-b31b-95e5ad66e50a.2018-06-18_18.34.04/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4940/elasticsearch_and_cassandra_mnesia.19.3/small/ct_run.mongooseim@localhost.2018-06-18_18.27.05/lib.mongooseim.logs/run.2018-06-18_18.27.05/suite.log.html)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by kanes115** [comment]
I think that along with adding pools we should maybe also increase the timeout time? It should be actually very high because we really don't want to run other tests on dirty environments anyway (there could just be a warninig after certain period of time - currently warning log are produced by wpool after 3 seconds of overrun). So effectively it could be infinity, but practically 10-15 seconds? It looks as if deleting users from riak and mssql took more time (and I have locally tested it on mnesia). 

I can do one more thing - measure the times it takes to delete users on different presets with those pools - we can then increase timeout accordingly

**Comment by michalwski** [comment]
@kanes115 

> I can do one more thing - measure the times it takes to delete users on different presets with those pools - we can then increase timeout accordingly

That's good idea. Please note that this time depends on other modules enabled on the server. When a user is deleted there is a hook run which many modules have handlers for. This is to clean data after the removed user.

**Comment by mongoose-im** [comment]
[4943.5](https://travis-ci.org/esl/MongooseIM/jobs/394145843) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / 16d85bfc89caa91f99b4938f865c37f8f731bef1
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4943/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4943/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-e6345ea0-e1a1-40fd-8248-2a7a9421ca89.2018-06-19_15.17.56/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4943/elasticsearch_and_cassandra_mnesia.19.3/small/ct_run.mongooseim@localhost.2018-06-19_15.11.04/lib.mongooseim.logs/run.2018-06-19_15.11.04/suite.log.html)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by fenek** [comment]
Is it WIP or waiting for review?

**Comment by mongoose-im** [comment]
[4964.6](https://travis-ci.org/esl/MongooseIM/jobs/396748452) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / 72708fe54c1048c521d90372ffada422ea525ded
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4964/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4964/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-aa87c515-de1f-4130-8af5-2c68afdfbfb4.2018-06-26_07.50.10/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4964/elasticsearch_and_cassandra_mnesia.19.3/small/)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[4966.3](https://travis-ci.org/esl/MongooseIM/jobs/396780499) / Erlang 19.3 / mysql_redis / 22652e97aec889e4316abbe576721e042fe48f02
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4966/mysql_redis.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4966/mysql_redis.19.3/big/ct_run.test%40travis-job-e6709dc7-6996-4228-a3ff-8b8178e05c65.2018-06-26_09.28.44/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4966/mysql_redis.19.3/small/)
**OK: 2799** / Failed: 0 / **User-skipped: 222** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[4968.2](https://travis-ci.org/esl/MongooseIM/jobs/396859093) / Erlang 19.3 / internal_mnesia / 9860598e58c5ce4ba126efd4307e03791b076f1a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4968/internal_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4968/internal_mnesia.19.3/big/ct_run.test%40travis-job-4747ce2b-dd61-41fb-9a26-3c92f6588f7c.2018-06-26_12.28.32/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4968/internal_mnesia.19.3/small/)
**OK: 1060** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[4968.5](https://travis-ci.org/esl/MongooseIM/jobs/396859096) / Erlang 19.3 / ldap_mnesia / 9860598e58c5ce4ba126efd4307e03791b076f1a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4968/ldap_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4968/ldap_mnesia.19.3/big/ct_run.test%40travis-job-8c0c6644-e11c-4541-abd0-fa3f13ee5dff.2018-06-26_12.31.08/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4968/ldap_mnesia.19.3/small/)
**OK: 1024** / Failed: 0 / **User-skipped: 77** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[4969.6](https://travis-ci.org/esl/MongooseIM/jobs/396887537) / Erlang 19.3 / elasticsearch_and_cassandra_mnesia / f39eb4c9e030ca8e0ab3e4a2abad8fbd713cf2f4
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/1933/4969/elasticsearch_and_cassandra_mnesia.19.3) / [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4969/elasticsearch_and_cassandra_mnesia.19.3/big/ct_run.test%40travis-job-5e64f06c-c4c9-45f0-87ca-2b12ee0ebd1a.2018-06-26_13.48.27/index.html) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/1933/4969/elasticsearch_and_cassandra_mnesia.19.3/small/)
**OK: 445** / Failed: 0 / **User-skipped: 8** / Auto-skipped: 0

**Pull request merged**
