### PR TITLE
Removed ejabberd_hooks module

### PR DESCRIPTION
**Pull request by pawlooss1**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/156434) / small_tests / 39704bcdab81305d44122e181c874c1306af37f9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3892/156434/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3892/156434/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-07_10.29.13/lib.mongooseim.logs/run.2022-12-07_10.29.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157316) / small_tests / 6a31f0a3872637ea334f8e7a7d6c2280e6e5da32
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3892/157316/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3892/157316/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-12_10.08.47/lib.mongooseim.logs/run.2022-12-12_10.08.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157347) / small_tests / 3d711fcfc58ea27ebc21b663e40b4545a899c660
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3892/157347/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3892/157347/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-12_11.12.52/lib.mongooseim.logs/run.2022-12-12_11.12.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157371) / small_tests / 25d7042298824ff25acc36330610c9b647256f56
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3892/157371/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3892/157371/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-12_11.50.54/lib.mongooseim.logs/run.2022-12-12_11.50.55/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good, nice to see the `mongoose_hooks` module getting much cleaner now :ok_hand:

**Pull request merged**
