### PR TITLE
Enable metrics_c2s_SUITE for dynamic domains

### PR DESCRIPTION
**Pull request by Premwoik**
Enable metrics_c2s_SUITE for dynamic domains.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/73408) / small_tests / 7f01406a5d51fdbab051a7bcbc873da82a776027
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3277/73408/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3277/73408/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-09-16_14.42.37/lib.mongooseim.logs/run.2021-09-16_14.42.38/suite.log.html)

**Review by vkatsuba — COMMENTED** [review]
Please resolve conflicts in `big_tests/dynamic_domains.spec`.

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/73786) / small_tests / a3587a275a33e0a97c5d82a28b1810abdadc8e04
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3277/73786/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3277/73786/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-09-17_08.06.51/lib.mongooseim.logs/run.2021-09-17_08.06.52/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good!

**Pull request merged**
