### PR TITLE
Refactored hook handlers in mod_cache_users

### PR DESCRIPTION
**Pull request by pawlooss1**
This PR changes all hook handlers in `mod_cache_users` module to `gen_hook` format.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148928) / small_tests / a3fd523c200e97161860d1f5e03ed864e3451ff0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/148928/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/148928/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_09.14.42/lib.mongooseim.logs/run.2022-11-04_09.14.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148954) / small_tests / a951741bf9f0d046ec9e3b616f6a7d3e5e138f08
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/148954/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/148954/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_09.51.12/lib.mongooseim.logs/run.2022-11-04_09.51.12/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/148984) / small_tests / ebffb2973ba5808ec6748d19087d81c73f246bba
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/148984/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/148984/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-04_10.34.32/lib.mongooseim.logs/run.2022-11-04_10.34.33/suite.log.html)

**Comment by mongoose-im** [comment]
[riak_mnesia_24](https://circleci.com/gh/esl/MongooseIM/149243) / riak_mnesia / ef4d6dcd068b9eefab871aa2e4d4329c6bb5aa0f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/149243/riak_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149399) / small_tests / c535bc13a248ea22b3e4569c81129ed47acd6c0f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/149399/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/149399/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-07_11.35.06/lib.mongooseim.logs/run.2022-11-07_11.35.06/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/149961) / small_tests / 2e60e6ba746a7e012571aee45fb67721dfe30dba
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/149961/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/149961/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-08_09.11.13/lib.mongooseim.logs/run.2022-11-08_09.11.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/150004) / small_tests / 859115b1353770fd57d7dc3462dd2f5b3bf78ae3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3842/150004/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3842/150004/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-08_10.06.07/lib.mongooseim.logs/run.2022-11-08_10.06.08/suite.log.html)

**Review by kamilwaz — APPROVED** [review]
Looks good :+1:

**Pull request merged**
