### PR TITLE
Don't override included overlay vars

### PR DESCRIPTION
**Pull request by chrzaszcz**
There is an issue with the overriding logic in `relx`: included vars override previously defined ones, but there is no simple
way of overriding the included vars other than including another file. This way making the `dev` releases resulted in incorrect vars.
Big tests succeeded because they had their own overriding logic.

This change ensures that no vars are overridden. The included file is always at the bottom, and in this case both `relx` and our templating scripts work the same (included vars override the previous ones).

Another changes:
- Avoid specifying defaults explicitly - they are documented, and the user could define them with different values if necessary.
- Rename `mim2` node for consistency.

Possible further improvements:
- Improve `relx` with a more intuitive and useful overriding logic.
- Adjust our templating scripts to work like relx - I am reluctant to do so, because our scripts are more intuitive, and the logic extends nicely to merging multiple files, what we do for big tests.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/142136) / ldap_mnesia / 74465ea2f2fcc35a06cf43ca58f85fa6cc7d0891
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3794/142136/ldap_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142179) / small_tests / b3dad82cdd9b816d7c070f0a4f94acadb8a57479
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3794/142179/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3794/142179/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_07.47.53/lib.mongooseim.logs/run.2022-10-05_07.47.53/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142229) / small_tests / 9000f5a3e80f03004b78a366b4c73d1865f328bc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3794/142229/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3794/142229/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_08.10.03/lib.mongooseim.logs/run.2022-10-05_08.10.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142361) / small_tests / 71ebcc85afe1597dfc822f33e4270a66bcc2c644
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3794/142361/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3794/142361/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-05_12.02.14/lib.mongooseim.logs/run.2022-10-05_12.02.15/suite.log.html)

**Review by NelsonVides — COMMENTED** [review]
Not sure I understand correctly. You moved the `./vars-toml.config` file to the bottom, so variables defined there will override those in the per-node config, right? But in that case `./vars-toml.config` defines for example `node_name`, and `c2s_port`, so it'd override those defined in all other configs. Am I understanding something the other way around? 🤔

**Comment by chrzaszcz** [comment]
> But in that case `./vars-toml.config` defines for example `node_name`, and `c2s_port`, so it'd override those defined in all other configs.
If you look at the diff, `./vars-toml.config` defines neither  `node_name` nor `c2s_port`. **No variable is overriden.**

**Review by NelsonVides — APPROVED** [review]
Excellent! I got confused trying to understand how it was working before and how it does in this PR, it's all clear now 😄

**Pull request merged**
