### PR TITLE
Fix for nkpacket_app fails to start when it's not possible to send UDP packet

### PR DESCRIPTION
**Pull request by aleklisi**
This PR attempts to fix the issue described as `nkpacket_app fails to start when it's not possible to send UDP packet`.

Notice: after merging https://github.com/NetComposer/nkpacket/pull/5 we can switch to `NetComposer/nkpacket`.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[6199.1](https://travis-ci.org/esl/MongooseIM/jobs/499205207) / Erlang 19.3 / small_tests / 226adade25a1a1402261ef8eb7216f55be11b03c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6199/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2229/6199/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-02-27_10.59.48/lib.mongooseim.logs/run.2019-02-27_10.59.49/suite.log.html)

**Comment by mongoose-im** [comment]
[6207.1](https://travis-ci.org/esl/MongooseIM/jobs/501437515) / Erlang 19.3 / small_tests / 44baa680f2f82545d31110f788991eebd69f36fb
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6207/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2229/6207/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-03-04_11.18.44/lib.mongooseim.logs/run.2019-03-04_11.18.45/suite.log.html)

**Comment by mongoose-im** [comment]
[6211.1](https://travis-ci.org/esl/MongooseIM/jobs/501915050) / Erlang 19.3 / small_tests / f01ec9119e18ab296cc5ec83ee0c6037c1ae4e67
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6211/small_tests.19.3)

**Comment by mongoose-im** [comment]
[6212.1](https://travis-ci.org/esl/MongooseIM/jobs/501926863) / Erlang 19.3 / small_tests / 0a4be91e84cf2f5fc2b735dfb94dbe02a7097b86
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6212/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2229/6212/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-03-05_09.07.34/lib.mongooseim.logs/run.2019-03-05_09.07.36/suite.log.html)

**Comment by mongoose-im** [comment]
[6216.1](https://travis-ci.org/esl/MongooseIM/jobs/501992395) / Erlang 19.3 / small_tests / d5c11fe719847776b6a7839614e13f65029ddc24
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6216/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2229/6216/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-03-05_12.29.26/lib.mongooseim.logs/run.2019-03-05_12.29.27/suite.log.html)

**Comment by mongoose-im** [comment]
[6220.1](https://travis-ci.org/esl/MongooseIM/jobs/502552421) / Erlang 19.3 / small_tests / 312a27186d6443b06fffc02d056f3bc6686c3a9d
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2229/6220/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2229/6220/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-03-06_13.06.21/lib.mongooseim.logs/run.2019-03-06_13.06.22/suite.log.html)

**Comment by aleklisi** [comment]
Since I did not manage to fix nksip, and it required cowboy update I close thi PR

**Pull request closed without merging**
