### PR TITLE
C2s/privacy

### PR DESCRIPTION
**Pull request by NelsonVides**
This implements privacy and blocking. They require presences.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134421) / small_tests / 22b7e2f38a68e397ff58a6151200b760f1b45df3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/134421/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/134421/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-02_21.59.37/lib.mongooseim.logs/run.2022-09-02_21.59.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134578) / small_tests / a18c463fd62d967b38a2ea4081d08c14d46786ce
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/134578/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/134578/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-03_13.25.06/lib.mongooseim.logs/run.2022-09-03_13.25.06/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134679) / small_tests / 2870c7d895d8b2ba8af8f3ff57041bdcc37dd0bf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/134679/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/134679/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-03_14.27.56/lib.mongooseim.logs/run.2022-09-03_14.27.57/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134807) / small_tests / cf3284cb38b9f15c3897953a060a05255c49c663
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/134807/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/134807/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-03_14.47.12/lib.mongooseim.logs/run.2022-09-03_14.47.12/suite.log.html)

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/137972) / ldap_mnesia / b7737016b39b97e1ddf19f96cdb1fe21af6ab4c9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/137972/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/index.html)
**OK: 823** / **Failed: 15** / **User-skipped: 425** / **Auto-skipped: 3** 
<details><summary>mod_blocking_SUITE:effect:messages_from_blocked_user_dont_arrive</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,
        <<"alice_unnamed_529_messages_from_blocked_user_dont_arrive_532@localhost/res1">>,
        escalus_tcp,<0.20496.0>,
        [{event_manager,<0.20473.0>},
         {server,<<"localhost">>},
         {username,
           <<"alicE_unnamed_529_messages_from_blocked_user_dont_arrive_532">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.20473.0>},
            {server,<<"localhost">>},
            {username,
              <<"alicE_unnamed_529_messages_from_blocked_user_dont_arrive_532">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,
           <<"alice_unnamed_529_messages_from_blocked_user_dont_arrive_532">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,
           <<"alicE_unnamed_529_messages_from_blocked_user_dont_arrive_532">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"500cc237743adf62">>}]},
      [{xmlel,<<"message">>,
         [{<<"from">>,
           <<"bob_unnamed_529_messages_from_blocked_user_dont_arrive_532@localhost/res1">>},
          {<<"to">>,
           <<"alice_unnamed_529_messages_from_blocked_user_dont_arrive_532@localhost/res1">>},
          {<<"type">>,<<"chat">>}],
         [{xmlel,<<"body">>,[],[{xmlcda...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.mod_blocking_SUITE.logs/run.2022-09-20_14.17.57/mod_blocking_suite.messages_from_blocked_user_dont_arrive.30594.html)
</details>
<details><summary>mod_blocking_SUITE:effect:blocking_propagates_to_resources</summary>


```erlang
{error,
  {timeout_when_waiting_for_stanza,
    [{escalus_client,wait_for_stanza,
       [{client,
          <<"bob_unnamed_529_blocking_propagates_to_resources_530@localhost/res1">>,
          escalus_tcp,<0.20507.0>,
          [{event_manager,<0.20459.0>},
           {server,<<"localhost">>},
           {username,
             <<"bOb_unnamed_529_blocking_propagates_to_resources_530">>},
           {resource,<<"res1">>}],
          [{event_client,
             [{event_manager,<0.20459.0>},
            {server,<<"localhost">>},
            {username,
              <<"bOb_unnamed_529_blocking_propagates_to_resources_530">>},
            {resource,<<"res1">>}]},
           {resource,<<"res1">>},
           {username,
             <<"bob_unnamed_529_blocking_propagates_to_resources_530">>},
           {server,<<"localhost">>},
           {host,<<"localhost">>},
           {port,5222},
           {auth,{escalus_auth,auth_plain}},
           {wspath,undefined},
           {username,
             <<"bOb_unnamed_529_blocking_propagates_to_resources_530">>},
           {server,<<"localhost">>},
           {password,<<"makrolika">>},
           {stream_id,<<"6bf312951db9b8f0">>}]},
        5000],
       [{file,
          "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_client.erl"},
        {line,136}]},
     {privacy_helper,gets_error,3,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_helper.erl"},
        {line,26}]},
     {mod_blocki...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.mod_blocking_SUITE.logs/run.2022-09-20_14.17.57/mod_blocking_suite.blocking_propagates_to_resources.5253.html)
</details>
<details><summary>mod_blocking_SUITE:effect:blocking_doesnt_interfere</summary>


```erlang
{error,
  {timeout_when_waiting_for_stanza,
    [{escalus_client,wait_for_stanza,
       [{client,
          <<"bob_unnamed_529_blocking_doesnt_interfere_534@localhost/res1">>,
          escalus_tcp,<0.20506.0>,
          [{event_manager,<0.20487.0>},
           {server,<<"localhost">>},
           {username,
             <<"bOb_unnamed_529_blocking_doesnt_interfere_534">>},
           {resource,<<"res1">>}],
          [{event_client,
             [{event_manager,<0.20487.0>},
            {server,<<"localhost">>},
            {username,
              <<"bOb_unnamed_529_blocking_doesnt_interfere_534">>},
            {resource,<<"res1">>}]},
           {resource,<<"res1">>},
           {username,
             <<"bob_unnamed_529_blocking_doesnt_interfere_534">>},
           {server,<<"localhost">>},
           {host,<<"localhost">>},
           {port,5222},
           {auth,{escalus_auth,auth_plain}},
           {wspath,undefined},
           {username,
             <<"bOb_unnamed_529_blocking_doesnt_interfere_534">>},
           {server,<<"localhost">>},
           {password,<<"makrolika">>},
           {stream_id,<<"933028698bc0ea7f">>}]},
        5000],
       [{file,
          "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_client.erl"},
        {line,136}]},
     {privacy_helper,gets_error,3,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_helper.erl"},
        {line,26}]},
     {mod_blocking_SUITE,'-blocking_doesnt_interfer...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.mod_blocking_SUITE.logs/run.2022-09-20_14.17.57/mod_blocking_suite.blocking_doesnt_interfere.30978.html)
</details>
<details><summary>mod_blocking_SUITE:effect:messages_from_any_blocked_resource_dont_arrive</summary>


```erlang
{error,
  {timeout_when_waiting_for_stanza,
    [{escalus_client,wait_for_stanza,
       [{client,
          <<"alice_unnamed_529_messages_from_any_blocked_resource_dont_arrive_531@localhost/res1">>,
          escalus_tcp,<0.20497.0>,
          [{event_manager,<0.20466.0>},
           {server,<<"localhost">>},
           {username,
             <<"alicE_unnamed_529_messages_from_any_blocked_resource_dont_arrive_531">>},
           {resource,<<"res1">>}],
          [{event_client,
             [{event_manager,<0.20466.0>},
            {server,<<"localhost">>},
            {username,
              <<"alicE_unnamed_529_messages_from_any_blocked_resource_dont_arrive_531">>},
            {resource,<<"res1">>}]},
           {resource,<<"res1">>},
           {username,
             <<"alice_unnamed_529_messages_from_any_blocked_resource_dont_arrive_531">>},
           {server,<<"localhost">>},
           {host,<<"localhost">>},
           {port,5222},
           {auth,{escalus_auth,auth_plain}},
           {wspath,undefined},
           {username,
             <<"alicE_unnamed_529_messages_from_any_blocked_resource_dont_arrive_531">>},
           {server,<<"localhost">>},
           {password,<<"matygrysa">>},
           {stream_id,<<"fb9400966c5c6fdb">>}]},
        5000],
       [{file,
          "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_client.erl"},
        {line,136}]},
     {privacy_helper,gets_error,3,
       [{file,
          "/home/circleci/pro...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.mod_blocking_SUITE.logs/run.2022-09-20_14.17.57/mod_blocking_suite.messages_from_any_blocked_resource_dont_arrive.30850.html)
</details>
<details><summary>mod_blocking_SUITE:offline:messages_after_relogin</summary>


```erlang
{error,
  {{assertion_failed,assert,is_chat_message,
     [<<"Hey bob, carpe diem!">>],
     {xmlel,<<"message">>,
       [{<<"from">>,<<"bob_unnamed_536@localhost/res1">>},
        {<<"to">>,<<"alice_unnamed_536@localhost">>},
        {<<"type">>,<<"chat">>}],
       [{xmlel,<<"body">>,[],
          [{xmlcdata,<<"Hey alice, are you there?">>}]}]},
     "<message from='bob_unnamed_536@localhost/res1' to='alice_unnamed_536@localhost' type='chat'><body>Hey alice, are you there?</body></message>"},
   [{escalus_new_assert,assert_true,2,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_new_assert.erl"},
       {line,84}]},
    {mod_blocking_SUITE,'-message_is_delivered/3-lc$^0/1-0-',2,
      [{file,
         "/home/circleci/project/big_tests/tests/mod_blocking_SUITE.erl"},
       {line,654}]},
    {escalus_story,story,4,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_story.erl"},
       {line,72}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
    {test_server,run_test_case_eval1,6,
      [{file,"test_server.erl"},{line,1292}]},
    {test_server,run_test_case_eval,9,
      [{file,"test_server.erl"},{line,1224}]}]}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.mod_blocking_SUITE.logs/run.2022-09-20_14.17.57/mod_blocking_suite.messages_after_relogin.html)
</details>
<details><summary>privacy_SUITE:blocking:block_group_message</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,<<"alice_block_group_message_612@localhost/res1">>,
        escalus_tcp,<0.24747.0>,
        [{event_manager,<0.24662.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_group_message_612">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24662.0>},
            {server,<<"localhost">>},
            {username,<<"alicE_block_group_message_612">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_group_message_612">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_group_message_612">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"9166ffb94e4364fc">>}]},
      [{xmlel,<<"message">>,
         [{<<"from">>,
           <<"bob_block_group_message_612@localhost/res1">>},
          {<<"to">>,
           <<"alice_block_group_message_612@localhost/res1">>},
          {<<"type">>,<<"chat">>}],
         [{xmlel,<<"body">>,[],
            [{xmlcdata,<<"Hi, blocked group!">>}]}]}]}}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_group_message.9476.html)
</details>
<details><summary>privacy_SUITE:blocking:block_jid_presence_in</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,<<"alice_block_jid_presence_in_615@localhost/res1">>,
        escalus_tcp,<0.24749.0>,
        [{event_manager,<0.24683.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_jid_presence_in_615">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24683.0>},
            {server,<<"localhost">>},
            {username,<<"alicE_block_jid_presence_in_615">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_jid_presence_in_615">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_jid_presence_in_615">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"914fa187a3b0921c">>}]},
      [{xmlel,<<"presence">>,
         [{<<"from">>,
           <<"bob_block_jid_presence_in_615@localhost/res1">>},
          {<<"to">>,
           <<"alice_block_jid_presence_in_615@localhost/res1">>}],
         []}]}}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_jid_presence_in.9860.html)
</details>
<details><summary>privacy_SUITE:blocking:block_subscription_message</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,
        <<"alice_block_subscription_message_618@localhost/res1">>,
        escalus_tcp,<0.24755.0>,
        [{event_manager,<0.24704.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_subscription_message_618">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24704.0>},
            {server,<<"localhost">>},
            {username,<<"alicE_block_subscription_message_618">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_subscription_message_618">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_subscription_message_618">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"52362ebe75f34308">>}]},
      [{xmlel,<<"message">>,
         [{<<"from">>,
           <<"bob_block_subscription_message_618@localhost/res1">>},
          {<<"to">>,
           <<"alice_block_subscription_message_618@localhost/res1">>},
          {<<"type">>,<<"chat">>}],
         [{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi!">>}]}]}]}}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_subscription_message.9604.html)
</details>
<details><summary>privacy_SUITE:blocking:block_jid_message_but_not_presence</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,
        <<"alice_block_jid_message_but_not_presence_621@localhost/res1">>,
        escalus_tcp,<0.24758.0>,
        [{event_manager,<0.24725.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_jid_message_but_not_presence_621">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24725.0>},
            {server,<<"localhost">>},
            {username,
              <<"alicE_block_jid_message_but_not_presence_621">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_jid_message_but_not_presence_621">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_jid_message_but_not_presence_621">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"c5fadf2818dc30ed">>}]},
      [{xmlel,<<"message">>,
         [{<<"from">>,
           <<"bob_block_jid_message_but_not_presence_621@localhost/res1">>},
          {<<"to">>,
           <<"alice_block_jid_message_but_not_presence_621@localhost/res1">>},
          {<<"type">>,<<"chat">>}],
         [{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi, Alice!">>}]}]}]}}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_jid_message_but_not_presence.23427.html)
</details>
<details><summary>privacy_SUITE:blocking:block_all_message</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,<<"alice_block_all_message_614@localhost/res1">>,
        escalus_tcp,<0.24750.0>,
        [{event_manager,<0.24676.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_all_message_614">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24676.0>},
            {server,<<"localhost">>},
            {username,<<"alicE_block_all_message_614">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_all_message_614">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_all_message_614">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"07e9b56df5646e7a">>}]},
      [{xmlel,<<"message">>,
         [{<<"from">>,<<"bob_block_all_message_614@localhost/res1">>},
          {<<"to">>,<<"alice_block_all_message_614@localhost/res1">>},
          {<<"type">>,<<"chat">>}],
         [{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi!">>}]}]}]}}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_all_message.9732.html)
</details>
<details><summary>privacy_SUITE:blocking:block_jid_iq</summary>


```erlang
{error,
  {test_case_failed,
    {has_stanzas_but_shouldnt,
      {client,<<"alice_block_jid_iq_617@localhost/res1">>,escalus_tcp,
        <0.24753.0>,
        [{event_manager,<0.24697.0>},
         {server,<<"localhost">>},
         {username,<<"alicE_block_jid_iq_617">>},
         {resource,<<"res1">>}],
        [{event_client,
           [{event_manager,<0.24697.0>},
            {server,<<"localhost">>},
            {username,<<"alicE_block_jid_iq_617">>},
            {resource,<<"res1">>}]},
         {resource,<<"res1">>},
         {username,<<"alice_block_jid_iq_617">>},
         {server,<<"localhost">>},
         {host,<<"localhost">>},
         {port,5222},
         {auth,{escalus_auth,auth_plain}},
         {wspath,undefined},
         {username,<<"alicE_block_jid_iq_617">>},
         {server,<<"localhost">>},
         {password,<<"matygrysa">>},
         {stream_id,<<"6731f2f909818b63">>}]},
      [{xmlel,<<"iq">>,
         [{<<"from">>,<<"alice_block_jid_iq_617@localhost">>},
          {<<"to">>,<<"alice_block_jid_iq_617@localhost/res1">>},
          {<<"id">>,<<"457b56c7bcce259547f624677cf9a0bf">>},
          {<<"type">>,<<"result">>}],
         []},
       {xmlel,<<"iq">>,
         [{<<"from">>,<<"bob_block_jid_iq_617@localhost/res1">>},
          {<<"to">>,<<"alice_block_jid_iq_617@localhost/res1">>},
          {<<"type">>,<<"get">>},
          {<<"id">>,<<"958d7fc36756ea8b89becd708e09fa8b">>}],
         [{xmlel,<<"query">>,
            [{<<"xmlns">>,<<"jabber:iq...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_jid_iq.23299.html)
</details>
<details><summary>privacy_SUITE:blocking:block_jid_message</summary>


```erlang
{error,
  {timeout_when_waiting_for_stanza,
    [{escalus_client,wait_for_stanza,
       [{client,<<"bob_block_jid_message_613@localhost/res1">>,
          escalus_tcp,<0.24759.0>,
          [{event_manager,<0.24669.0>},
           {server,<<"localhost">>},
           {username,<<"bOb_block_jid_message_613">>},
           {resource,<<"res1">>}],
          [{event_client,
             [{event_manager,<0.24669.0>},
            {server,<<"localhost">>},
            {username,<<"bOb_block_jid_message_613">>},
            {resource,<<"res1">>}]},
           {resource,<<"res1">>},
           {username,<<"bob_block_jid_message_613">>},
           {server,<<"localhost">>},
           {host,<<"localhost">>},
           {port,5222},
           {auth,{escalus_auth,auth_plain}},
           {wspath,undefined},
           {username,<<"bOb_block_jid_message_613">>},
           {server,<<"localhost">>},
           {password,<<"makrolika">>},
           {stream_id,<<"d8e0bc8193a71322">>}]},
        5000],
       [{file,
          "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_client.erl"},
        {line,136}]},
     {privacy_helper,gets_error,3,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_helper.erl"},
        {line,26}]},
     {privacy_SUITE,'-block_jid_message/1-fun-0-',2,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_SUITE.erl"},
        {line,418}]},
     {escalus_story,story,4,
       [{file,
          "/ho...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_jid_message.9348.html)
</details>
<details><summary>privacy_SUITE:blocking:block_jid_all</summary>


```erlang
{error,
  {timeout_when_waiting_for_stanza,
    [{escalus_client,wait_for_stanza,
       [{client,<<"bob_block_jid_all_619@localhost/res1">>,escalus_tcp,
          <0.24767.0>,
          [{event_manager,<0.24711.0>},
           {server,<<"localhost">>},
           {username,<<"bOb_block_jid_all_619">>},
           {resource,<<"res1">>}],
          [{event_client,
             [{event_manager,<0.24711.0>},
            {server,<<"localhost">>},
            {username,<<"bOb_block_jid_all_619">>},
            {resource,<<"res1">>}]},
           {resource,<<"res1">>},
           {username,<<"bob_block_jid_all_619">>},
           {server,<<"localhost">>},
           {host,<<"localhost">>},
           {port,5222},
           {auth,{escalus_auth,auth_plain}},
           {wspath,undefined},
           {username,<<"bOb_block_jid_all_619">>},
           {server,<<"localhost">>},
           {password,<<"makrolika">>},
           {stream_id,<<"df16f88e4f307470">>}]},
        5000],
       [{file,
          "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_client.erl"},
        {line,136}]},
     {privacy_helper,gets_error,3,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_helper.erl"},
        {line,26}]},
     {privacy_SUITE,'-block_jid_all/1-fun-0-',2,
       [{file,
          "/home/circleci/project/big_tests/tests/privacy_SUITE.erl"},
        {line,693}]},
     {escalus_story,story,4,
       [{file,
          "/home/circleci/project/big_...
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.block_jid_all.9988.html)
</details>
<details><summary>privacy_SUITE:allowing:allow_subscription_both_message</summary>


```erlang
{error,
  {{assertion_failed,assert,is_error,
     [<<"cancel">>,<<"service-unavailable">>],
     {xmlel,<<"message">>,
       [{<<"from">>,
         <<"bob_allow_subscription_both_message_625@localhost/res1">>},
        {<<"to">>,
         <<"alice_allow_subscription_both_message_625@localhost/res1">>},
        {<<"type">>,<<"chat">>}],
       [{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi, Alice XYZ!">>}]}]},
     "<message from='bob_allow_subscription_both_message_625@localhost/res1' to='alice_allow_subscription_both_message_625@localhost/res1' type='chat'><body>Hi, Alice XYZ!</body></message>"},
   [{escalus_new_assert,assert_true,2,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_new_assert.erl"},
       {line,84}]},
    {privacy_SUITE,'-allow_subscription_both_message/1-fun-0-',2,
      [{file,"/home/circleci/project/big_tests/tests/privacy_SUITE.erl"},
       {line,532}]},
    {escalus_story,story,4,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_story.erl"},
       {line,72}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
    {test_server,run_test_case_eval1,6,
      [{file,"test_server.erl"},{line,1292}]},
    {test_server,run_test_case_eval,9,
      [{file,"test_server.erl"},{line,1224}]}]}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.allow_subscription_both_message.10116.html)
</details>
<details><summary>privacy_SUITE:allowing:allow_subscription_to_from_message</summary>


```erlang
{error,
  {{assertion_failed,assert,is_error,
     [<<"cancel">>,<<"service-unavailable">>],
     {xmlel,<<"message">>,
       [{<<"from">>,
         <<"bob_allow_subscription_to_from_message_626@localhost/res1">>},
        {<<"to">>,
         <<"alice_allow_subscription_to_from_message_626@localhost/res1">>},
        {<<"type">>,<<"chat">>}],
       [{xmlel,<<"body">>,[],[{xmlcdata,<<"Hi, Alice XYZ!">>}]}]},
     "<message from='bob_allow_subscription_to_from_message_626@localhost/res1' to='alice_allow_subscription_to_from_message_626@localhost/res1' type='chat'><body>Hi, Alice XYZ!</body></message>"},
   [{escalus_new_assert,assert_true,2,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_new_assert.erl"},
       {line,84}]},
    {privacy_SUITE,'-allow_subscription_to_from_message/1-fun-0-',2,
      [{file,"/home/circleci/project/big_tests/tests/privacy_SUITE.erl"},
       {line,492}]},
    {escalus_story,story,4,
      [{file,
         "/home/circleci/project/big_tests/_build/default/lib/escalus/src/escalus_story.erl"},
       {line,72}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
    {test_server,run_test_case_eval1,6,
      [{file,"test_server.erl"},{line,1292}]},
    {test_server,run_test_case_eval,9,
      [{file,"test_server.erl"},{line,1224}]}]}}
```

[Report log](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/137972/ldap_mnesia.24.3.4/big/ct_run.test%409ed2f33c7267.2022-09-20_14.15.15/big_tests.tests.privacy_SUITE.logs/run.2022-09-20_14.18.43/privacy_suite.allow_subscription_to_from_message.37250.html)
</details>

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138036) / small_tests / 559015e733d8aabb0d61dac312b9d979c9024ddc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/138036/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/138036/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-20_14.25.56/lib.mongooseim.logs/run.2022-09-20_14.25.57/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138963) / small_tests / a959bce471a21bba04327b0223658f39f6e40a99
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/138963/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/138963/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_13.39.37/lib.mongooseim.logs/run.2022-09-23_13.39.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139019) / small_tests / e591151651fbf2c32e4eb0b619812d24598f0851
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/139019/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/139019/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_14.11.00/lib.mongooseim.logs/run.2022-09-23_14.11.00/suite.log.html)

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/139047) / ldap_mnesia / fadd027239ba03b0362b2b7900b4d2f2f45a692d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3747/139047/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3747/139047/ldap_mnesia.24.3.4/big/ct_run.test%40074bfba31c3a.2022-09-23_14.35.56/index.html)
**OK: 865** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

**Review by kamilwaz — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
