### PR TITLE
Change readthedocs theme

### PR DESCRIPTION
**Pull request by kmakiela**
This PR addresses [MIM-1238](https://erlangsolutions.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=MIM&modal=detail&selectedIssue=MIM-1238)

It seems that most of the issues we had with the docs can be solved by finding an appropriate theme and this is the one that best suits our preferences. 
Left to do after merge -> upload new version of the docs to `readthedocs`

### CODE REVIEW

**Comment by chrzaszcz** [comment]
Could you provide more information about how it looks, what are the differences and what other alternatives were investigated? I also cannot build docs locally - it seems some work or configuration is needed to allow that:

```$ mkdocs serve
INFO    -  Building documentation...
WARNING -  Config value: 'site_favicon'. Warning: Unrecognised configuration name: site_favicon
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs

Aborted with 1 Configuration Errors!```

**Comment by kmakiela** [comment]
I mostly looked into the possibility of customising already existing readthedocs or moving to github pages. Both seemed reasonable but in the end I chose to stick with the readthedocs as long as I could make it look pretty. The advantages of the proposed theme include:
- expandable sections
- less dead space
- moving table of contents to a more readable position
- more readable and copyable code snippets

For a local build this additional instruction is needed but since we don't build the docs in our pipeline I believe there is no need to add it. 

And yes, the themes are customisable, it would require overriding some assets - more information i.e. [here](https://github.com/squidfunk/mkdocs-material/blob/master/docs/customization.md)

**Comment by mongoose-im** [comment]
[8731.1](https://travis-ci.org/esl/MongooseIM/jobs/744226446) / Erlang 23.0.3 / small_tests / c211696d73f6503e942e203029a2f1207c523814
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2946/8731/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2946/8731/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-11-18_03.47.02/lib.mongooseim.logs/run.2020-11-18_03.47.02/suite.log.html)

**Comment by NelsonVides** [comment]
@chrzaszcz this change seems to work for me locally, adding to the mkdocs.yml file this:
```
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
```
That way I do have the syntax highlighting, though colours are very soft-pastel tones, but it works :)

**Pull request merged**
