### PR TITLE
Section-based auth config

### PR DESCRIPTION
**Pull request by chrzaszcz**
Change the way auth methods are specified:
- Sections for each auth method are now required.
- A list of auth methods is no longer required. It can be used to enable selected methods in a specific order. When not specified, it is created automatically from the auth method sections in alphabetical order.

**Motivation:**
- Check for required options was broken - when a method was on the list but there was no section for it (no options configured), the check did not work.
- Defaults could not be introduced without having all sections always enabled, which would clutter the configuration.

**Other changes:**
- Moved the check for unsupported auth methods and modules to the TOML processing. This way it is easier to test and more consistent. The tests are changed to have less mocking and to be consistent with the rest of the suite and the check for error patterns can now be used in other test cases as well.

**Planned in the next PR:**
- Defaults for the auth methods.
- Moving `scram_iterations` to `auth.password`.

**Example 1** - before:
```
[auth]
  methods = ["ldap"]

  [auth.ldap]
    base = "ou=Users,dc=esl,dc=com"
    filter = "(objectClass=inetOrgPerson)"
```

After - the `auth` section itself can be skipped as it has no options:
```
[auth.ldap]
  base = "ou=Users,dc=esl,dc=com
  filter = "(objectClass=inetOrgPerson)"
```

**Example 2** - before:
```
[auth]
  methods = ["rdbms"]
  scram_iterations = 64
```

After - the subsection is now necessary:
```
[auth]
  scram_iterations = 64
  [auth.rdbms]
```

Alternatively:
```
[auth]
  scram_iterations = 64
  rdbms = {}
```

**Example 3** - most complicated, unlikely:
```
[auth]
  methods = ["rdbms", "ldap"]

  [auth.ldap]
    base = "ou=Users,dc=esl,dc=com"
    filter = "(objectClass=inetOrgPerson)"
```

After - `rdbms` section needs to be added. `methods` is still needed to sort them.
```
[auth]
  methods = ["rdbms", "ldap"]

  [auth.ldap]
    base = "ou=Users,dc=esl,dc=com"
    filter = "(objectClass=inetOrgPerson)"

  [auth.rdbms]
```

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/94103) / small_tests / d5c48f162669b738afad496f42c80013ea609aa1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/94103/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/94103/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-10_16.39.38/lib.mongooseim.logs/run.2021-12-10_16.39.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/94786) / small_tests / 43b897d2873cb426acb9a753c70e456ece892606
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/94786/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/94786/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-15_17.27.19/lib.mongooseim.logs/run.2021-12-15_17.27.19/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/94900) / small_tests / 4ae697206cc10c4fafe71f80264628681e625bc6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/94900/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/94900/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-16_07.45.26/lib.mongooseim.logs/run.2021-12-16_07.45.26/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/94937) / small_tests / 35f510d36983a66c6b2b6ec6fd7399e0aa9372e5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/94937/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/94937/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-16_08.04.13/lib.mongooseim.logs/run.2021-12-16_08.04.13/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95035) / small_tests / ad87bcecae895266e7369e4e740e1198e5ab92c3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/95035/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/95035/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-16_14.25.40/lib.mongooseim.logs/run.2021-12-16_14.25.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95064) / small_tests / e95c1e00315a5b9069e59b1fda4fcfd2dcbfe596
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/95064/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/95064/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-16_14.29.48/lib.mongooseim.logs/run.2021-12-16_14.29.48/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95073) / small_tests / 33f283749f15fda2ebf67560dc61bd7b214685a4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3446/95073/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3446/95073/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-16_14.30.38/lib.mongooseim.logs/run.2021-12-16_14.30.39/suite.log.html)

**Review by Premwoik — APPROVED** [review]
Looks good to me :) I like how unsupported auth methods and modules are checked now.

**Pull request merged**
