### PR TITLE
Prepared queries - DRAFT 2

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR is rebased version of #3014.

Proposed changes include:
* Queries

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9072.1](https://travis-ci.org/esl/MongooseIM/jobs/757566661) / Erlang 23.0.3 / small_tests / ad1e07650093e6301780ef37401cd6d32fbdb322
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3025/9072/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3025/9072/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-04_16.31.38/lib.mongooseim.logs/run.2021-02-04_16.31.38/suite.log.html)

**Comment by mongoose-im** [comment]
[9076.1](https://travis-ci.org/esl/MongooseIM/jobs/757691165) / Erlang 23.0.3 / small_tests / 395ea9e82648d8f653fbdf9ac94d56e7a7489703
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3025/9076/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3025/9076/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-05_14.32.51/lib.mongooseim.logs/run.2021-02-05_14.32.52/suite.log.html)

**Comment by mongoose-im** [comment]
[9098.1](https://travis-ci.org/esl/MongooseIM/jobs/759640050) / Erlang 23.0.3 / small_tests / f08f2b567c2cf00d71df7876babbac2d7c08824a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3025/9098/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3025/9098/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-19_14.37.50/lib.mongooseim.logs/run.2021-02-19_14.37.50/suite.log.html)

**Comment by mongoose-im** [comment]
[9107.1](https://travis-ci.org/esl/MongooseIM/jobs/760167025) / Erlang 23.0.3 / small_tests / 75625725007ad22b20d572ff80307f0bfb03199b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3025/9107/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3025/9107/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-23_14.46.59/lib.mongooseim.logs/run.2021-02-23_14.46.59/suite.log.html)

**Comment by arcusfelis** [comment]
https://github.com/esl/MongooseIM/pull/3039
rebased on the current master

**Pull request closed without merging**
