### PR TITLE
Improve error handling in session

### PR DESCRIPTION
**Pull request by kamilwaz**
Improve error handling in session

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/155152) / small_tests / 9dcb2a2067cc274ebb10b921d062ea2961a62646
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3883/155152/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3883/155152/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-01_09.06.27/lib.mongooseim.logs/run.2022-12-01_09.06.27/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/155418) / small_tests / bd0c840d84acf3c558d29be938d8bfcd0d5ffb75
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3883/155418/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3883/155418/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-01_14.37.47/lib.mongooseim.logs/run.2022-12-01_14.37.48/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
I think all the changes are good, but I think we need to address some cases that give unexpected results:

Listing sessions for a non-existent domain results in an empty list, which makes the impression that the domain exists, but there are no users connected. So for example if I type `loclahost` instead of `localhost`, I might assume that my server has no sessions, which is not true.
```
$ _build/mim1/rel/mongooseim/bin/mongooseimctl session listSessions --domain x
{
  "data" : {
    "session" : {
      "listSessions" : [
        
      ]
    }
  }
}
```

The same happens for non-existent users:
```
 _build/mim1/rel/mongooseim/bin/mongooseimctl session listUserSessions --user a@b
egrep: warning: egrep is obsolescent; using grep -E
{
  "data" : {
    "session" : {
      "listUserSessions" : [
        
      ]
    }
  }
}
```

This behaviour is present for multiple commands, e.g.
```
$ _build/mim1/rel/mongooseim/bin/mongooseimctl session kickUser --user x@z
egrep: warning: egrep is obsolescent; using grep -E
{
  "data" : {
    "session" : {
      "kickUser" : [
        
      ]
    }
  }
}
```

Another corner case is that if you try to list sessions while a user is connected with SSE (REST or GraphQL), it crashes because of no IP address. To reproduce, run this in one shell:
```
curl -H 'Authorization: Basic YWRtaW46c2VjcmV0' -v -N http://localhost:5551/api/graphql/sse?query=subscription%20%7Bstanza%20%7BsubscribeForMessages%28caller%3A%22alice%40localhost%22%29%20%7Bstanza%7D%7D%7D
```

Then, while the previous command is running, do:
```
$ _build/mim1/rel/mongooseim/bin/mongooseimctl session listUserSessions --user alice@localhost
{
  "errors" : [
    {
      "path" : [
        "session",
        "listUserSessions"
      ],
      "message" : "Unexpected SessionAdminQuery resolver crash",
      "extensions" : {
        "code" : "resolver_crash"
      }
    }
  ],
  "data" : {
    "session" : {
      "listUserSessions" : null
    }
  }
}

```

**Review by chrzaszcz — APPROVED** [review]
Looks good :+1:

**Pull request merged**
