### PR TITLE
TOML config

### PR DESCRIPTION
**Pull request by chrzaszcz**
This is a draft PR for a feature branch. Having such a PR is useful to test the branch after each merge from master.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[8385.1](https://travis-ci.org/esl/MongooseIM/jobs/711408992) / Erlang 22.0 / small_tests / e08e1ee8b8478ee3042370ea19d7b9dd013980fe
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8385/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8385/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-07-24_10.08.29/lib.mongooseim.logs/run.2020-07-24_10.08.30/suite.log.html)

**Comment by mongoose-im** [comment]
[8394.1](https://travis-ci.org/esl/MongooseIM/jobs/713202624) / Erlang 22.0 / small_tests / e613f7a1d081802422cae5435e9fcbf575cae669
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8394/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8394/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-07-30_08.01.48/lib.mongooseim.logs/run.2020-07-30_08.01.48/suite.log.html)

**Comment by mongoose-im** [comment]
[8425.1](https://travis-ci.org/esl/MongooseIM/jobs/717166879) / Erlang 22.0 / small_tests / 3c28afe0f717023c40cdf7b367da9a6d14d0230a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8425/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8425/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-12_07.23.03/lib.mongooseim.logs/run.2020-08-12_07.23.04/suite.log.html)

**Comment by mongoose-im** [comment]
[8426.1](https://travis-ci.org/esl/MongooseIM/jobs/717170869) / Erlang 22.0 / small_tests / 28fa6b7d37c02152069e8bf721a290c153eba664
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8426/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8426/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-12_08.06.53/lib.mongooseim.logs/run.2020-08-12_08.06.54/suite.log.html)

**Comment by mongoose-im** [comment]
[8427.1](https://travis-ci.org/esl/MongooseIM/jobs/717512586) / Erlang 22.0 / small_tests / 5bbebd8a45a8209a31539b54b539dacf683e56b4
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8427/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8427/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-13_08.11.54/lib.mongooseim.logs/run.2020-08-13_08.11.54/suite.log.html)

**Comment by mongoose-im** [comment]
[8429.1](https://travis-ci.org/esl/MongooseIM/jobs/717898963) / Erlang 22.0 / small_tests / f1759344fb6d00af4eb70b7a2b13108dd61f5dff
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8429/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8429/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-14_12.38.43/lib.mongooseim.logs/run.2020-08-14_12.38.44/suite.log.html)

**Comment by mongoose-im** [comment]
[8440.1](https://travis-ci.org/esl/MongooseIM/jobs/718714684) / Erlang 22.0 / small_tests / da2ac4831d6c7d018a1e37a62c7bec82e8ef34f8
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8440/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8440/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-17_18.04.11/lib.mongooseim.logs/run.2020-08-17_18.04.11/suite.log.html)

**Comment by mongoose-im** [comment]
[8441.1](https://travis-ci.org/esl/MongooseIM/jobs/718873237) / Erlang 22.0 / small_tests / b4e9048a5f18cc17a1cffdc13e6781f4dffd84db
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8441/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8441/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-18_07.41.56/lib.mongooseim.logs/run.2020-08-18_07.41.57/suite.log.html)

**Comment by mongoose-im** [comment]
[8461.1](https://travis-ci.org/esl/MongooseIM/jobs/719184286) / Erlang 22.0 / small_tests / fd776f8ce7caa2394d40a28728908a4814f1893c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8461/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8461/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-08-19_06.21.28/lib.mongooseim.logs/run.2020-08-19_06.21.28/suite.log.html)

**Comment by mongoose-im** [comment]
[8518.1](https://travis-ci.org/esl/MongooseIM/jobs/723446492) / Erlang 23.0.3 / small_tests / abb51566af4df268f2d4b46447f3589bdb1f58b8
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8518/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8518/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-02_13.54.25/lib.mongooseim.logs/run.2020-09-02_13.54.25/suite.log.html)

**Comment by mongoose-im** [comment]
[8565.1](https://travis-ci.org/esl/MongooseIM/jobs/728913014) / Erlang 23.0.3 / small_tests / 5aaa84195ba10e2becc73fe7da5df4a7068373e2
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8565/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8565/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-21_08.43.04/lib.mongooseim.logs/run.2020-09-21_08.43.05/suite.log.html)

**Comment by mongoose-im** [comment]
[8566.1](https://travis-ci.org/esl/MongooseIM/jobs/728924086) / Erlang 23.0.3 / small_tests / f5de879aadfa5fdde5bef2e7f374a9d865038b5c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8566/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8566/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-21_09.02.15/lib.mongooseim.logs/run.2020-09-21_09.02.16/suite.log.html)

**Comment by mongoose-im** [comment]
[8570.1](https://travis-ci.org/esl/MongooseIM/jobs/728992138) / Erlang 23.0.3 / small_tests / 9144193174b7fbe2535605a690a3cff7cd28aff7
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8570/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8570/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-21_13.54.12/lib.mongooseim.logs/run.2020-09-21_13.54.13/suite.log.html)

**Comment by mongoose-im** [comment]
[8571.1](https://travis-ci.org/esl/MongooseIM/jobs/729548590) / Erlang 23.0.3 / small_tests / 9a8b162dbc332b4e59427de6e66573f108533495
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8571/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8571/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-23_08.13.03/lib.mongooseim.logs/run.2020-09-23_08.13.03/suite.log.html)

**Comment by mongoose-im** [comment]
[8573.1](https://travis-ci.org/esl/MongooseIM/jobs/729874783) / Erlang 23.0.3 / small_tests / cf0cd331a7fbaa762452c158d462a2be2ec1a801
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8573/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8573/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-24_08.09.04/lib.mongooseim.logs/run.2020-09-24_08.09.05/suite.log.html)

**Comment by mongoose-im** [comment]
[8574.1](https://travis-ci.org/esl/MongooseIM/jobs/729901463) / Erlang 23.0.3 / small_tests / 78adc73a6b344252fbb9b6cdb8ee3447641c4a63
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8574/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8574/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-24_10.10.38/lib.mongooseim.logs/run.2020-09-24_10.10.38/suite.log.html)

**Comment by mongoose-im** [comment]
[8575.1](https://travis-ci.org/esl/MongooseIM/jobs/729919347) / Erlang 23.0.3 / small_tests / f60966779292d5db88721b34b3013b8262c1f2db
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8575/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8575/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-24_11.28.11/lib.mongooseim.logs/run.2020-09-24_11.28.12/suite.log.html)

**Comment by mongoose-im** [comment]
[8580.1](https://travis-ci.org/esl/MongooseIM/jobs/730315158) / Erlang 23.0.3 / small_tests / ae56d8c42760f10146dfdf7ab4fd6302bfe92199
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8580/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8580/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-25_16.35.50/lib.mongooseim.logs/run.2020-09-25_16.35.51/suite.log.html)

**Comment by mongoose-im** [comment]
[8582.1](https://travis-ci.org/esl/MongooseIM/jobs/730907105) / Erlang 23.0.3 / small_tests / 310b371507885b69f29ef9d352395a9fa8b5823d
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8582/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8582/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-28_10.06.22/lib.mongooseim.logs/run.2020-09-28_10.06.23/suite.log.html)

**Comment by mongoose-im** [comment]
[8583.1](https://travis-ci.org/esl/MongooseIM/jobs/731109715) / Erlang 23.0.3 / small_tests / 8cd5f3efa78f3057cc5d12dc6d8248fdceff071b
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8583/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8583/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-28_22.14.19/lib.mongooseim.logs/run.2020-09-28_22.14.19/suite.log.html)

**Comment by mongoose-im** [comment]
[8584.1](https://travis-ci.org/esl/MongooseIM/jobs/731192457) / Erlang 23.0.3 / small_tests / 08d8b46f484bb4c3ae95276b8c172117d0d605da
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8584/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8584/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-29_07.18.58/lib.mongooseim.logs/run.2020-09-29_07.18.58/suite.log.html)

**Comment by mongoose-im** [comment]
[8587.1](https://travis-ci.org/esl/MongooseIM/jobs/731252391) / Erlang 23.0.3 / small_tests / 2327334d0d614a3b172f65d4fae4f9ba26aad209
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8587/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8587/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-29_12.04.14/lib.mongooseim.logs/run.2020-09-29_12.04.15/suite.log.html)

**Comment by mongoose-im** [comment]
[8590.1](https://travis-ci.org/esl/MongooseIM/jobs/731282553) / Erlang 23.0.3 / small_tests / dba5b45d7d30298d2ace87897774a9e66bd084ab
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8590/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8590/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-29_14.27.12/lib.mongooseim.logs/run.2020-09-29_14.27.12/suite.log.html)

**Comment by mongoose-im** [comment]
[8596.1](https://travis-ci.org/esl/MongooseIM/jobs/731342520) / Erlang 23.0.3 / small_tests / a25b3a70a687c35c6ba2ef982124c54eb4c3ac9a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8596/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8596/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-29_17.41.26/lib.mongooseim.logs/run.2020-09-29_17.41.26/suite.log.html)

**Comment by mongoose-im** [comment]
[8598.2](https://travis-ci.org/esl/MongooseIM/jobs/731394496) / Erlang 23.0.3 / internal_mnesia / 9046b1d37d5f0b3646ce74ba42aeb4f0a36143ab
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8598/internal_mnesia.23.0.3)/ [big](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8598/internal_mnesia.23.0.3/big//index.html)

**Comment by mongoose-im** [comment]
[8600.1](https://travis-ci.org/esl/MongooseIM/jobs/731413378) / Erlang 23.0.3 / small_tests / bb4cef28f9428fbf92ea1e29ffef754437008c7a
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8600/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8600/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-29_21.22.17/lib.mongooseim.logs/run.2020-09-29_21.22.18/suite.log.html)

**Comment by mongoose-im** [comment]
[8601.1](https://travis-ci.org/esl/MongooseIM/jobs/731509356) / Erlang 23.0.3 / small_tests / a258c6bda2c3ffa2ae641d7c141555ea3670df98
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2801/8601/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2801/8601/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-09-30_07.07.54/lib.mongooseim.logs/run.2020-09-30_07.07.54/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
🔥 🎆 💣 🏆 😍 ❤️ 😄 💪
 
Here we go, gold is coming!

**Pull request merged**
