### PR TITLE
Auth method defaults

### PR DESCRIPTION
**Pull request by chrzaszcz**
Introduce default values for `auth` methods, so they are easier to test and to find in the code.
The `undefined` values for LDAP are also included as defaults for consistency.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95574) / small_tests / d7a7fb500f0b33a35c23f557ff5673cb8b1a10b2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3458/95574/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3458/95574/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-17_13.51.58/lib.mongooseim.logs/run.2021-12-17_13.51.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95606) / small_tests / dc71bb97f969d761ba524173aa6c780daea1a54d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3458/95606/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3458/95606/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-17_14.18.06/lib.mongooseim.logs/run.2021-12-17_14.18.07/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/95654) / small_tests / 48136798438f228715c4a0e4785151f75ab6d481
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3458/95654/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3458/95654/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-12-17_15.13.34/lib.mongooseim.logs/run.2021-12-17_15.13.34/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Excellent 👍🏽

**Pull request merged**
