### PR TITLE
Instrument/log

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal of this PR is to add a new `mongoose_instrument_log` handler for instrumentation events. It can be used for generic event logging, debugging and testing.

It is configurable just like metrics, e.g.

```
[instrumentation.prometheus]
[instrumentation.log]
```

The new handler is enabled in the default config file for all presets - at least for now in the feature branch.
Log level is `debug` by default, but you can change it:

```
[instrumentation.log]
  level = "info"
```

The level can be overridden by adding e.g. `loglevel => error` to either the event config (on set-up) or the measurements (on execute/span).

Notes:
- I like `log_level` a bit more than `loglevel`, but the latter was already used in MIM, so I followed the naming.
- We could split measurements from metadata, because `loglevel` is metadata (just like in telemetry). I am not convinced because sometimes the distinction is blurry, and we also don't want too many map arguments in one function.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211193) / elasticsearch_and_cassandra_mnesia / ea40f5454d7e7d3c7bd55feb1b615cf8eecd60f1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211193/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211193/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%409dfb328623d8.2024-03-08_13.50.19/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211231) / elasticsearch_and_cassandra_mnesia / c240d984137dc08ef3438606c4d79bd0ca063b2d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211231/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211231/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40bbc9a5710724.2024-03-08_18.33.11/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211711) / elasticsearch_and_cassandra_mnesia / f4d2f7c062479ae6aa7f763cd28794d3aad183c7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211711/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211711/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%404c5c8acd2b19.2024-03-12_09.16.25/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211784) / elasticsearch_and_cassandra_mnesia / 3810ec38ab267926ec0a3248274a95e7d80487d0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211784/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211784/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%403edba00e0108.2024-03-12_10.43.24/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211809) / elasticsearch_and_cassandra_mnesia / 949f5ae0d3260a8088e9cbedf766dbf211e52870
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211809/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211809/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40b402f7c08f1a.2024-03-12_11.08.27/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211889) / elasticsearch_and_cassandra_mnesia / fb9b5d668b7516278c2bf73ed1009619ab44599d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211889/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211889/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40fdac1af18655.2024-03-13_08.02.42/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211917) / elasticsearch_and_cassandra_mnesia / 2d6415df48bb814c47fd68d2dd43427f2a863e71
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211917/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211917/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4079c3e163c383.2024-03-13_08.08.44/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/211955) / elasticsearch_and_cassandra_mnesia / 7c5511d9f199f44a0546aab9bcec1c7cfe5590e1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/211955/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/211955/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%401d78dc1afc09.2024-03-13_08.15.36/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/212135) / elasticsearch_and_cassandra_mnesia / ad2056fc6dba6d43c1eb66466438950f7e228f93
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4238/212135/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4238/212135/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40559a23dbbcb4.2024-03-13_10.41.11/index.html)
**OK: 429** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
