### PR TITLE
Patch ejabberd_sm

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses a couple of tweaks.

Proposed changes include:
* One less get_sessions/2 on open_session in SM
* Disconnect both present and not sessions in disconnect_removed_user

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186851) / small_tests / e2a8c3bc35b5487858acaf059b282cc5768ab587
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4096/186851/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4096/186851/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-12_08.51.17/lib.mongooseim.logs/run.2023-08-12_08.51.18/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/186922) / elasticsearch_and_cassandra_mnesia / 492085d8c4760a1a1051dce16376c8acd82f06fb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4096/186922/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4096/186922/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4080457d3a98d2.2023-08-12_10.17.05/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187107) / elasticsearch_and_cassandra_mnesia / e8a2cc858acfc5c92cc02d57263e01bbc36f0517
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4096/187107/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4096/187107/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%408ec25803ab40.2023-08-13_09.47.09/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
Awesome 🔥

**Pull request merged**
