### PR TITLE
Less MIM compiler warnings

### PR DESCRIPTION
**Pull request by gustawlippa**
This PR fixes some compiler warnings for MIM. This includes deprecated functions for example, which should mean less work when upgrading OTP versions.

There are two warnings left:
- `mod_http_upload_s3` uses `http_uri`, which is deprecated and will be removed with OTP25. It would probably be best to refactor this module to make the best of the new `uri_string` module, which has a bit different API, but I'd rather do this in a separate PR.
- conflicting behaviours of `mod_cowboy` when it comes to `init/2` and `terminate/3`. I've left it because from what I understand it shouldn't cause problems, and I'm not sure if this module is even used.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/103739) / small_tests / 2570ec7ea410857327a5a7e11ab901a89feff8a9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3524/103739/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3524/103739/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-31_08.26.36/lib.mongooseim.logs/run.2022-01-31_08.26.37/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/103887) / small_tests / a77a3b06ac627edcd2c3baa48638ccf39173a369
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3524/103887/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3524/103887/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-31_10.44.22/lib.mongooseim.logs/run.2022-01-31_10.44.22/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM 👍🏽

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
