### PR TITLE
Unified REST API: metrics

### PR DESCRIPTION
**Pull request by chrzaszcz**
Remove the obsolete `mongoose_api`. It had two handlers:
- `mongoose_api_users` is removed, because had functions that are fully covered by the new REST and GraphQL API's.
- `mongoose_api_metrics` had an incomplete API for metrics. For example, it did not fully handle metrics with compound names (more than one atom after the host type). I decided to move that functionality to `mongoose_admin_api_metrics` **without functional changes** (except error handling). The main reason is that this obsolete API was most likely unused. We can always extend it to use `mongoose_metrics_api` just like the GraphQL API does, should anyone need it. However, most likely we will eventually remove it with the whole REST API.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138558) / small_tests / 260c238c073067880cd0d79896a0f89250203f45
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138558/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138558/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_07.24.55/lib.mongooseim.logs/run.2022-09-23_07.24.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138584) / small_tests / f4b5e9a522778be61ed529650de864a3cef384df
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138584/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138584/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_07.35.24/lib.mongooseim.logs/run.2022-09-23_07.35.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138612) / small_tests / 5a8090c68db1439b030aa87e0b21c4a1e1d2fbf7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138612/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138612/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_07.41.49/lib.mongooseim.logs/run.2022-09-23_07.41.49/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138634) / small_tests / 2f4b9fbebb8c35c89a8485f00eb94e2efbb82e17
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138634/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138634/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_07.51.15/lib.mongooseim.logs/run.2022-09-23_07.51.16/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138689) / small_tests / ef54dc15830b7008b806bb9149d3ab5fb566b2ce
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138689/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138689/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_09.02.16/lib.mongooseim.logs/run.2022-09-23_09.02.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138767) / small_tests / c51f8ce99ee483945c473a7e3b5022fc2a4f481c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138767/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138767/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_09.43.51/lib.mongooseim.logs/run.2022-09-23_09.43.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138813) / small_tests / 9aa09f205aaf2c13d1ba2c78f4dcf41a9e134bab
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138813/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138813/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_11.58.02/lib.mongooseim.logs/run.2022-09-23_11.58.02/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138865) / small_tests / 23b0446f2ed61368295eb4315c1d5ceec989439e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138865/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138865/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_12.50.45/lib.mongooseim.logs/run.2022-09-23_12.50.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138893) / small_tests / 0401ec75f529af616e667912dd3162508bf739b8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138893/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138893/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_12.55.49/lib.mongooseim.logs/run.2022-09-23_12.55.50/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138993) / small_tests / 26799334546461517de21bf87e38ac9739c1a9f0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3771/138993/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3771/138993/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_13.49.07/lib.mongooseim.logs/run.2022-09-23_13.49.08/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Review by arcusfelis — COMMENTED** [review]
looks good

**Review by arcusfelis — COMMENTED** [review]
looks good

**Pull request merged**
