### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
Updating instrumentation configuration documentation.

Modifying valid instrumentation log level values, disabling 'none' value.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/239140) / elasticsearch_and_cassandra_mnesia / c5609766949a8016427fdff0b9f4ac10c6c5a67d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4382/239140/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4382/239140/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%4070cc7c468346.2024-10-11_15.54.49/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/239242) / elasticsearch_and_cassandra_mnesia / 24f397f9748812f87a889a0c8f1e773b1bc715e5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4382/239242/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4382/239242/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%400f2fba73343b.2024-10-16_09.06.40/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/239322) / elasticsearch_and_cassandra_mnesia / f6e474e26a63ff46b38786d185fd16fb35218ff2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4382/239322/elasticsearch_and_cassandra_mnesia.27.0.1-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4382/239322/elasticsearch_and_cassandra_mnesia.27.0.1-amd64/big.tar.gz//ct_run.test%40b69635de157d.2024-10-18_13.06.30/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
Looks good, thanks for the fixes 👍

**Pull request merged**
