### PR TITLE
Service management rework

### PR DESCRIPTION
**Pull request by chrzaszcz**
Rework service configuration and management, following the logic that is already present for modules, and thus making the two more unified.

Main changes:
- Put services in a map that is always included.
- Manage services in `mongoose_service`, like modules are managed in `mongoose_modules`. There is some discrepancy in naming, but the name is not changed as `mongoose_service` is itself a behaviour. There is no `replace_services` logic for tests, because it is would be just unused in the current tests.
- Resolve/sort dependencies in `mongoose_service_deps`, similarly to `gen_mod_deps`. Service deps are always hard and never have opts, which simplifies the logic.
- Make unit tests for services and their deps similar to the corresponding tests for modules.

See the commit messages for more details.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/118222) / small_tests / 7ebbfc3bb4b30592e768a98fd557d640d341ac18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3620/118222/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3620/118222/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-04-01_08.11.11/lib.mongooseim.logs/run.2022-04-01_08.11.12/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/118324) / small_tests / 4a3fec438621675cd51109f48cd2a45932814fd3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3620/118324/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3620/118324/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-04-01_12.48.46/lib.mongooseim.logs/run.2022-04-01_12.48.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/118403) / small_tests / 1a7a30d867e02c821b64f50327d978cc9b15b093
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3620/118403/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3620/118403/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-04-01_13.05.05/lib.mongooseim.logs/run.2022-04-01_13.05.05/suite.log.html)

**Review by Premwoik — APPROVED** [review]
All looks good to me :) I like the new service tests, look more clearly.

**Pull request merged**
