### PR TITLE
ejabberd_c2s: Omit features on required STARTTLS.

### PR DESCRIPTION
**Pull request by aszlig**
This should fix esl/ejabberd_tests#130, but I've not been able to test this by myself yet.

According to RFC 6120, section 5.3.1 it's not recommended to send features before the client has finished STARTTLS:

http://xmpp.org/rfcs/rfc6120.html#tls-rules-mtn

I've stumbled on this with Gajim 0.16.3 on Windows but haven't yet able to reproduce this with the very same client on NixOS, Ubuntu and Debian.

While this originally was/is an issue with Gajim, MongooseIM really should implement what is recommended by the RFC, regardless of whether clients out there break because of this (or see it as an open invitation to send cleartext passwords).

### CODE REVIEW

**Comment by michalwski** [comment]
Many thanks for the change. Could you please set the same name to the branch in ejabberd_tests? Thanks to that travis will automatically take your modified tests.

**Comment by aszlig** [comment]
@michalwski: Okay, one second, will change that...

**Comment by michalwski** [comment]
I've restarted the build on travis.

**Comment by aszlig** [comment]
@michalwski: Thanks :-)

**Comment by michalwski** [comment]
According to logs on travis:

>Pulling ejabberd_tests from {git,"git://github.com/aszlig/ejabberd_tests.git", {branch,"fix-features-on-required-starttls"}}

The dedicated test branch is used but the automatic comment was not posted here because of some credentials issue. Sth probably's changed in Github's API. I'll investigate that.

**Comment by aszlig** [comment]
@michalwski: Okay, the test has failed, is there a way to get the full ct_report from Travis?

**Comment by aszlig** [comment]
Force-pushed to trigger travis rebuild.

**Comment by michalwski** [comment]
There are several places when you can find some info about failure. First one is a console log from common_test - https://travis-ci.org/esl/MongooseIM/jobs/78714069#L1875

After all tests run there is also a summary printed to the travis log: https://travis-ci.org/esl/MongooseIM/jobs/78714069#L2091

And also at the end of the travis log you can find all suite.log files printed. The relevant line is this: https://travis-ci.org/esl/MongooseIM/jobs/78714069#L6597

Hope this helps.

If you want to debug just the connect_SUITE please edit  https://github.com/aszlig/ejabberd_tests/blob/fix-features-on-required-starttls/default.spec file to include only connect_SUITE. But remember to revert the change when you finally find and fix the problem.

**Comment by aszlig** [comment]
@michalwski: Okay, tests seem to have passed.

**Comment by michalwski** [comment]
@aszlig, thanks a lot for your contribution!

**Pull request merged**
