### PR TITLE
Correctly handle the case when TLS is disabled

### PR DESCRIPTION
**Pull request by chrzaszcz**
When the TLS section is missing, then according to the [documentation](https://esl.github.io/MongooseDocs/latest/configuration/listen/#tls-options-for-c2s) STARTTLS should be rejected. This was not the case: the feature was advertised, and a TLS upgrade performed by a client (who was informed about the support) resulted in a crash.

This PR fixes these issues:
- STARTTLS is only advertised when enabled.
- Upgrade attempt results in a correct failure element, as described in [RFC 6120](https://datatracker.ietf.org/doc/html/rfc6120#section-5.4.2.2)

The tests are updated to check these conditions, and to correctly verify the features for optional and required STARTTLS as well.

The bugs were discovered accidentally when checking https://github.com/esl/mongooseim-docker/issues/42. The statement about TLS disabled by default is changed in the docs, because it most likely confused the reporter of that issue.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195748) / elasticsearch_and_cassandra_mnesia / 27e1ce1aa503e0a05b18efb1172d9ca20134a5f3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4150/195748/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4150/195748/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4050223b8ff25b.2023-10-13_14.03.11/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195794) / elasticsearch_and_cassandra_mnesia / 5ea5574113c368e8b1b7fd22516a8c0af72e091d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4150/195794/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4150/195794/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40d737cd3b9a6d.2023-10-13_14.30.29/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195876) / elasticsearch_and_cassandra_mnesia / 68c2714be8cf3f3de75c7b3fcebf065425dbe168
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4150/195876/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4150/195876/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4050c05bc3eec2.2023-10-13_15.30.51/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195931) / elasticsearch_and_cassandra_mnesia / d9afeaaa608812c523b6cc1e1b33afa8eff77746
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4150/195931/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4150/195931/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%400998b6cbe0be.2023-10-13_16.35.25/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195951) / elasticsearch_and_cassandra_mnesia / ebe60bb1d5b16df751be8021f3dcdef1a493ace1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4150/195951/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4150/195951/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%401307bb7c4e46.2023-10-13_16.35.57/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
Nice, very nice, good catch! 🔥

**Pull request merged**
