### PR TITLE
Add GraphQL types for JID parts

### PR DESCRIPTION
**Pull request by chrzaszcz**
Add GraphQL types: `UserName`, `RoomName` and `ResourceName`. We already have `DomainName`.
The new types ensure that the input data is string-prepped correctly, and that no empty strings are allowed.

`RoomName` and `UserName` have the same syntax, but I think that their semantics are different enough to separate them. I tried to have one type called `LocalName`, but it was confusing. Something like `LocalPart` would be even more cryptic.

Added tests for the new types.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152586) / small_tests / a6ef5437ff373f6f2f815d35948abc91b29451c7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152586/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152586/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_11.29.59/lib.mongooseim.logs/run.2022-11-17_11.29.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152605) / small_tests / e736fbbbad7b2679fecd3eeb368816ba413e2221
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152605/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152605/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_11.32.10/lib.mongooseim.logs/run.2022-11-17_11.32.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152843) / small_tests / 569a4ed3b5d457b3e3ed7a660f2bb50bd653d2c9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152843/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152843/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_08.57.59/lib.mongooseim.logs/run.2022-11-18_08.58.00/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152946) / small_tests / f9ab0e9ca44a226b1a8723c4769a9504a626c64c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152946/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152946/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_17.32.07/lib.mongooseim.logs/run.2022-11-18_17.32.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152977) / small_tests / 715e725d385b344e5af607d8aed6156cbbf0b6a3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152977/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152977/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_17.54.19/lib.mongooseim.logs/run.2022-11-18_17.54.20/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152982) / small_tests / 5af8b3c1cdd95e50b029543773caf57f67fee791
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3862/152982/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3862/152982/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-18_17.54.55/lib.mongooseim.logs/run.2022-11-18_17.54.55/suite.log.html)

**Comment by kamilwaz** [comment]
I would change the type of `resource` in `priv/graphql/schemas/user/muc.gql` as well. The rest looks good.

**Review by kamilwaz — APPROVED** [review]

**Pull request merged**
