### PR TITLE
Instrument/label consistency

### PR DESCRIPTION
**Pull request by chrzaszcz**
Reimplement `mongoose_instrument` registry, allowing more consistency checks.

- Label keys for a given `EventName` need to be the same for all registered events - otherwise Prometheus metrics would break.
- In case of already registered events, the `set_up` callbacks are not called before raising the error.

A `gen_server` is used to eliminate possible race conditions during setup.

Previously, `mongoose_instrument_registry` was an ETS table. Now a map: `#{event_name() => #{labels() => handlers()}}` is used instead.
- The map is initially stored in the state of the `gen_server`, but a call to `mongoose_instrument:persist()` should be done after initial setup, which stores it in a persistent term.
- The term is then updated for every future `set_up`/`tear_down` call.
- This means that the implementation is firstly optimized for updates, and after `persist` it is optimized for concurrent reads.

This is very similar to `gen_hook`, but the events are handled correctly even before `persist` is called. This seems to be needed, because some events might be triggered during startup, and they shouldn't fail.

---

Note: after a restart the persistent terms are always deleted, even if `terminate` was not called (e.g. `kill`). This means that all instrumentation is lost on restart. We could change this to make it permanent, but I think it would require a separate PR. The same applies to `gen_hook`, but additionally it can get into an inconsistent state when killed and started again - this is unlikely though.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_25](https://circleci.com/gh/esl/MongooseIM/208506) / small_tests / 4cf4a30ed721e596465885f795e6347678b2c0af
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208506/small_tests.25.3.2.6-amd64)

**Comment by mongoose-im** [comment]
[small_tests_25](https://circleci.com/gh/esl/MongooseIM/208541) / small_tests / a260d1873c95d79f779fd1a7a34dd8042a0a000e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208541/small_tests.25.3.2.6-amd64)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208574) / elasticsearch_and_cassandra_mnesia / 78074d553e9cdaec7ea469c87e6bea71b80a5fa5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208574/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208574/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40353a322f343f.2024-02-22_18.39.02/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208656) / elasticsearch_and_cassandra_mnesia / 7436e6d4dca6ededfb1ad18bd8825f50ee22bc66
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208656/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208656/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40cdf0c4e58216.2024-02-23_08.35.48/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208696) / elasticsearch_and_cassandra_mnesia / 718f0181bdd3032ac63dcd749275b6143351be61
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208696/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208696/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40bcf02896fbc7.2024-02-23_15.14.58/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208726) / elasticsearch_and_cassandra_mnesia / 050a842496f38e3cb371ccd67f0e3a41befb7a21
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208726/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208726/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40fae40eff51b5.2024-02-23_15.31.35/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208752) / elasticsearch_and_cassandra_mnesia / a217513db1ec4cfe1590b6cc3a9a7295522cc025
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208752/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208752/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4024cebd955c37.2024-02-23_15.59.52/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/208785) / elasticsearch_and_cassandra_mnesia / 34699003ead274a319a3e9012d8355ae7a5cc760
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/208785/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/208785/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40866f7f51b5a3.2024-02-23_17.31.26/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/209341) / elasticsearch_and_cassandra_mnesia / 582da60337b44cfde2e657953922356bf9b2b2c7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/209341/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/209341/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%405174f1ab93e8.2024-02-27_10.49.43/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/209433) / elasticsearch_and_cassandra_mnesia / 277171b75fdf560c1e79fc7a92f5c0fd98ce54a3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4228/209433/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4228/209433/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40ea9b8b00fd45.2024-02-27_12.00.45/index.html)
**OK: 417** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good to me

**Pull request merged**
