### PR TITLE
C2s code cleanup

### PR DESCRIPTION
**Pull request by chrzaszcz**
This PR cleans up some minor leftovers of the old c2s, and finishes renaming `Handler` to `ModState`, which was done incompletely.

More details in commit messages.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/165376) / small_tests / 53bc2431958cbb6869536b8415558e49e31ca496
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3959/165376/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3959/165376/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-02-08_12.02.20/lib.mongooseim.logs/run.2023-02-08_12.02.20/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/165399) / small_tests / 4bd9e890015d5fd30a2244dfa26e8420a116f7c6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3959/165399/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3959/165399/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-02-08_17.59.34/lib.mongooseim.logs/run.2023-02-08_17.59.35/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/165424) / small_tests / 1bc311301883d0861eba52bdf1f40cd0fa1b445e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3959/165424/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3959/165424/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-02-08_18.53.11/lib.mongooseim.logs/run.2023-02-08_18.53.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/165452) / small_tests / cb60d77b30523bd142417d56dbd59b38f0f9791b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3959/165452/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3959/165452/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-02-09_07.22.21/lib.mongooseim.logs/run.2023-02-09_07.22.22/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM 👌🏽

**Review by DenysGonchar — APPROVED** [review]
looks fine

**Pull request merged**
