### PR TITLE
Put mod_disco opts in a map with defaults

### PR DESCRIPTION
**Pull request by chrzaszcz**
Also:
- Order `default_mod_config` alphabetically.
- Add `mod_config/2` helper
- Minor fix in the docs
- Removed the special case of `undefined` module treated as `mod_disco` - it was counter-intuitive.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/107427) / small_tests / de43d68b0624a2fcb8db4637ba02488e237226b9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3550/107427/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3550/107427/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-17_14.50.12/lib.mongooseim.logs/run.2022-02-17_14.50.12/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/107460) / small_tests / e3bd9da2a3da7fcdffae23b327a45acf262dab69
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3550/107460/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3550/107460/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-17_15.15.03/lib.mongooseim.logs/run.2022-02-17_15.15.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/107485) / small_tests / 6a3945f4112ff0da133a25ee064839da499d955a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3550/107485/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3550/107485/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-17_15.24.31/lib.mongooseim.logs/run.2022-02-17_15.24.31/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/107512) / small_tests / c6cb0f05cd5229e624cfef8bf425a1f459d7ad98
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3550/107512/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3550/107512/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-02-17_15.31.52/lib.mongooseim.logs/run.2022-02-17_15.31.53/suite.log.html)

**Review by gustawlippa — APPROVED** [review]
Looks good 👍

**Pull request merged**
