### PR TITLE
mod_bosh config in a map

### PR DESCRIPTION
**Pull request by chrzaszcz**
**Main changes:**
- Put `mod_bosh` options in a map with defaults.
- Use `mongoose_backend` in `mod_bosh`. Make it global as the only backend (`mnesia`) uses Mnesia globally and the `node_cleanup` hook is global as well. Start it only once to avoid warnings for duplicated hooks.
- Put `backend` in the config spec for `mod_bosh` and `mod_auth_token` even if there is only one backend to avoid setting it in multiple places (system metrics, backend module). Document it as well - for consistency and to simplify adding new custom backends.

**Other changes:**
- Create a directory for helpers shared between small and big tests. Use it for default module config.
- Make `mod_bosh` config match the docs (time units, positive vs. non-negative integers).
- Fix `mongoose_module_metrics` to work with module opts in maps and use the defaults.
- Reject BOSH connections to host types for which the module is not enabled.
- Make BOSH tests more stable - the first test can fail under specific circumstances (coverage disabled, freshly started node).

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/105462) / small_tests / bfde9e96738a6f4dbe978801231cb4c471afdb9b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/105462/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/105462/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-11_12.22.02/lib.mongooseim.logs/run.2022-02-11_12.22.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106109) / small_tests / 94c33434a689ddfb6de8130f19c5825e1e7e7e8c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106109/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106109/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-15_18.10.20/lib.mongooseim.logs/run.2022-02-15_18.10.21/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106209) / small_tests / 3b240d35de64efbacd561f29d86e56de280bbef4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106209/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106209/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_07.42.48/lib.mongooseim.logs/run.2022-02-16_07.42.48/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106236) / small_tests / a8baf767c38b7b2b489d71ecddaa7386969325a9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106236/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106236/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_07.51.13/lib.mongooseim.logs/run.2022-02-16_07.51.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106256) / small_tests / 2af292c5b223bddc960394f8b7765bacf660ab6d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106256/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106256/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_08.23.12/lib.mongooseim.logs/run.2022-02-16_08.23.13/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106345) / small_tests / 4dc4aace2f61a12a31bad63f34868691707f2382
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106345/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106345/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_12.46.17/lib.mongooseim.logs/run.2022-02-16_12.46.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106355) / small_tests / 24ff70799b39d6da4781be437b692f656750b372
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106355/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106355/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_12.47.08/lib.mongooseim.logs/run.2022-02-16_12.47.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106485) / small_tests / 978d1174ccd4dde6fda90d046fd59e91241099ef
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106485/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106485/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_16.53.29/lib.mongooseim.logs/run.2022-02-16_16.53.30/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106506) / small_tests / c4ea8ab9add75e32810d5ada410d0cc3eda7d522
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106506/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106506/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_17.07.41/lib.mongooseim.logs/run.2022-02-16_17.07.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/106531) / small_tests / bfd1f23df62363d689a7bcb871c4597efa4c313f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3540/106531/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3540/106531/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-02-16_17.13.11/lib.mongooseim.logs/run.2022-02-16_17.13.12/suite.log.html)

**Review by gustawlippa — APPROVED** [review]
Thanks for the changes! I like the backend added, and the common test helper especially.

**Pull request merged**
