### PR TITLE
Pubsub item publisher

### PR DESCRIPTION
**Pull request by sstrigler**
add boolean config option item_publisher

if set to true publishers of items will be stored with event and
broadcasted along according to

https://xmpp.org/extensions/xep-0060.html#publisher-publish-success-publisher

### CODE REVIEW

**Comment by michalwski** [comment]
Hi @sstrigler,

Thanks for your PR! Will you have some time to modify tests? I see `pep_SUITE` and `pubsub_SUITE` are failing in all jobs on travis.

**Comment by sstrigler** [comment]
Sorry, haven't been notified about your comment. Will look into this.

**Comment by sstrigler** [comment]
This patch also depends on https://github.com/xsf/xeps/pull/267

So before that one is accepted and merged this here should not be merged either.

**Comment by sstrigler** [comment]
rebased on current master, fixed bug and force pushed

**Comment by sstrigler** [comment]
*ooops* force pushed another fix

dialyzer complained and pointed out another bug which was not covered by a test case. I decided to not go write a test for my new stuff since it would require quite some work as in require a whole new configuration to start the tests with. Or is there an easier way? Maybe just reload and start the module with a different configuration and then run the test in question?

I think in the long run it would be better to be able to configure nodes accordingly during run time. This would require even more changes to the XEP though. And I left this out for now.

**Comment by michalwski** [comment]
@sstrigler I see your patch to XEP-0060 got merged and published.

Do you think you will find some time to write a simple test case? 

> Maybe just reload and start the module with a different configuration and then run the test in question?

Yes, reloading with changed config for mod_pubsub will work. You have some helper functions in `dynamic_modules` in `test/ejabberd_tests/tests`.

**Comment by sstrigler** [comment]
Hu?

**Comment by michalwski** [comment]
Yes, I merged this without tests. Feel free to add them at anytime.
Or you are not referring to lack of tests?

**Comment by sstrigler** [comment]
We're there no more tests failing?

**Comment by michalwski** [comment]
They are still failing in your other PR #1027. This one was green.

**Comment by sstrigler** [comment]
Oh, lol, ok! Very well then. :p

**Pull request merged**
