### PR TITLE
Prepared queries (WIP)

### PR DESCRIPTION
**Pull request by chrzaszcz**
PR from a feature branch, used for testing

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9038.1](https://travis-ci.org/esl/MongooseIM/jobs/755709837) / Erlang 23.0.3 / small_tests / be32c6ea9cf567839f38713f3058fb12c5234162
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3014/9038/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3014/9038/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-01-22_17.33.58/lib.mongooseim.logs/run.2021-01-22_17.33.59/suite.log.html)

**Comment by mongoose-im** [comment]
[9045.1](https://travis-ci.org/esl/MongooseIM/jobs/756387380) / Erlang 23.0.3 / small_tests / 5009505a0693695141af7fca7f9d800bd9fa8f85
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3014/9045/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3014/9045/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-01-27_10.57.19/lib.mongooseim.logs/run.2021-01-27_10.57.20/suite.log.html)

**Comment by mongoose-im** [comment]
[9071.1](https://travis-ci.org/esl/MongooseIM/jobs/757545037) / Erlang 23.0.3 / small_tests / 6d326bf7666f3e13004dfd726fe5f92f7c853f75
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3014/9071/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3014/9071/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-04_13.57.56/lib.mongooseim.logs/run.2021-02-04_13.57.57/suite.log.html)

**Comment by arcusfelis** [comment]
Moved to https://github.com/esl/MongooseIM/pull/3025

**Pull request closed without merging**
