### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by NelsonVides**
Just update all dependencies again, with special care to the newer worker_pool 6.0, and reorder the declarations in rebar.config. See commits for a step-by-step declaration.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[dynamic_domains_pgsql_mnesia_23](https://circleci.com/gh/esl/MongooseIM/99122) / pgsql_mnesia / b85f39151b6f6d4f7cb946ad988d9012a0f72890
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3490/99122/pgsql_mnesia.23.1)

**Comment by mongoose-im** [comment]
[dynamic_domains_mysql_redis_24](https://circleci.com/gh/esl/MongooseIM/99162) / mysql_redis / 1f9c4c566077218e97ded91081e290326a37edf2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3490/99162/mysql_redis.24.0.5)

**Comment by mongoose-im** [comment]
[dynamic_domains_mysql_redis_24](https://circleci.com/gh/esl/MongooseIM/99184) / mysql_redis / 8a99e35f61c11fd1959f0a79654a71ab8572c01b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3490/99184/mysql_redis.24.0.5)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/99228) / small_tests / 44dc361a56f697927a7eb228a2f849e4e97fe8e8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3490/99228/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3490/99228/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-01-08_16.51.28/lib.mongooseim.logs/run.2022-01-08_16.51.29/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/99241) / small_tests / a2ab135a2275f6cdb934d449af37a50c00342c04
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3490/99241/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3490/99241/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-01-08_16.57.05/lib.mongooseim.logs/run.2022-01-08_16.57.06/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
