### PR TITLE
Feature: unified REST API

### PR DESCRIPTION
**Pull request by chrzaszcz**
The work in this feature branch has been completed. It is read for merge.

- [x] Replace `mongoose_api_client` with `mongoose_client_api_*`
- [x] Replace `mongoose_api_admin` with `mongoose_admin_api_*`
- [x] Remove `mongoose_commands` and `mod_*commands`
- [x] Replace `mongoose_domain_handler` with `mongoose_admin_api_*`
- [x] Replace `mongoose_api` with `mongoose_admin_api_*`
- [x] Implement handler configuration for Admin API
- [x] Document the new API

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/133780) / small_tests / f838ee1c958190c74c623eccfa1ebb010ed321f5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/133780/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/133780/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-25_07.11.14/lib.mongooseim.logs/run.2022-08-25_07.11.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/135146) / small_tests / 95bf2d5548ea821925e579512f028ab066896a72
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/135146/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/135146/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-06_12.34.11/lib.mongooseim.logs/run.2022-09-06_12.34.12/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/136844) / small_tests / 0c74a8f45be0cab37c36a24e9004d5ba3ca5e574
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/136844/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/136844/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_08.25.04/lib.mongooseim.logs/run.2022-09-15_08.25.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/137030) / small_tests / 72c0612b5928835ff3490903279810ca46d41ed5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/137030/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/137030/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-15_15.02.26/lib.mongooseim.logs/run.2022-09-15_15.02.26/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/137188) / small_tests / 6e954afa11b3f02d641aaab807e05ada9bf7bec1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/137188/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/137188/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-16_05.58.13/lib.mongooseim.logs/run.2022-09-16_05.58.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138214) / small_tests / b8ff2287d15d8a429170ead9b25f0c2db4547874
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/138214/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/138214/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-21_12.38.53/lib.mongooseim.logs/run.2022-09-21_12.38.54/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138479) / small_tests / df6df9ce6594d8f44b722b469ce4cea6a3bc5a2a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/138479/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/138479/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-22_13.19.07/lib.mongooseim.logs/run.2022-09-22_13.19.07/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139358) / small_tests / 0b4cd4e3cfc305e0d4c5dc2ee021657c1d7e3ca7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/139358/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/139358/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-26_13.46.05/lib.mongooseim.logs/run.2022-09-26_13.46.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139719) / small_tests / fecb1bd90b6423861e820cb585c5528c46b14c05
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/139719/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/139719/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-27_14.20.23/lib.mongooseim.logs/run.2022-09-27_14.20.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/139914) / small_tests / 2c1313815614b894ee00dd8f4e249ff15b0e872f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/139914/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/139914/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-28_10.15.44/lib.mongooseim.logs/run.2022-09-28_10.15.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140802) / small_tests / b88ec048690d00c827e8f476bb205e82b963cc1d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/140802/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/140802/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-03_12.03.04/lib.mongooseim.logs/run.2022-10-03_12.03.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/140849) / small_tests / 62738e123922e29235a26487999f08c3c0ff4655
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3741/140849/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3741/140849/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-03_12.32.50/lib.mongooseim.logs/run.2022-10-03_12.32.51/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]

**Pull request merged**
