### PR TITLE
Test for log in with conflicting resources

### PR DESCRIPTION
**Pull request by bartekgorny**
This PR is a failed attempt to reproduce #843, and at the same time the missing test for resource conflict use case.

### CODE REVIEW

**Comment by artefactop** [comment]
You are checking that client receive the response `escalus:assert(is_stream_error, [<<"conflict">>, <<"Replaced by new connection">>], E).` but in don't checking if session is still saved on redis

**Comment by bartekgorny** [comment]
True, because it proves that 'replaced' atom is sent, received and processed. Are you 110% sure the session remains in backend database? If so, then the problem is bad cleanup.

**Comment by artefactop** [comment]
Yes, it happened for us in production, could you check if when second client goes offline is you request `ejabberd_sm:get_user_resources(User, Server)` it returns one entry (the old one)

**Comment by bartekgorny** [comment]
ok, I'll see to it

**Comment by michalwski** [comment]
The duplicated sessions where most probably due to the race condition fixed in #1141

**Pull request closed without merging**
