### PR TITLE
Instrument/mod muc

### PR DESCRIPTION
**Pull request by chrzaszcz**
This PR converts `mod_muc` metrics from `mongoose_metrics` to `mongoose_instrument`.

- One probe is used for counting online and hibernated rooms to reduce duplication of work.
- Metrics are per-host-type now (they were global before).
- Instrumentation helpers for big tests are updated to allow testing probes.

More details in commit messages.

**Note:** In the current implementation, probes are started when instrumentation events are set up. As a result, the module is not started yet, while the probe is already enabled. There is a similar possibility of a race condition when a module is being stopped. This is why a `try ... catch` is required in `mod_muc:count_rooms/1`. A solution might be to start probes after starting the module, but this would make the code more complex. We could do it in a separate story if needed.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215919) / elasticsearch_and_cassandra_mnesia / 10f4b806bb66d159d92dd906ce1b35d457759262
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/215919/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/215919/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40577d2f075817.2024-04-17_15.41.27/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215934) / elasticsearch_and_cassandra_mnesia / 65159a7f20b6445c01bd2dc54bc56dedd2efc37d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/215934/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/215934/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40004ae301dce1.2024-04-17_15.42.34/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215987) / elasticsearch_and_cassandra_mnesia / 9a1b2370695db068996b5a6b76449e0ebf6defdf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/215987/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/215987/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40ae73b0a90c74.2024-04-18_10.56.20/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216008) / elasticsearch_and_cassandra_mnesia / 23330dcbe78114c01b1083329acbbd0f1373b117
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216008/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216008/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%405f5b940f6f18.2024-04-18_10.56.56/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216035) / elasticsearch_and_cassandra_mnesia / 8ec1de45d2111ee721c3c4a7b532e1e64941881e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216035/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216035/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40b83df3cb8ce2.2024-04-18_11.11.47/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216076) / elasticsearch_and_cassandra_mnesia / 9178ff3e08d27606492b35bfeb80aa94f4c02347
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216076/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216076/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%407d4404c52c34.2024-04-18_12.02.00/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216109) / elasticsearch_and_cassandra_mnesia / 8ccbee1caf13852725edc3ac64ba6096383f5670
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216109/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216109/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%403722df1145d1.2024-04-19_08.29.25/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216135) / elasticsearch_and_cassandra_mnesia / 79264cada29e8e9e772d71adbaf6c1eeaeea8784
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216135/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216135/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4071f119a17306.2024-04-19_10.44.28/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216210) / elasticsearch_and_cassandra_mnesia / 392d20f4f173cb49f69fe8ab1df11eecbd8a0a18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/216210/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/216210/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4020d1fb5d462f.2024-04-22_14.09.17/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217027) / elasticsearch_and_cassandra_mnesia / 84b71e89878e6d8b12eeeea04c69e2377c535dcc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/217027/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/217027/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%407c506db8917a.2024-04-24_07.57.02/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217058) / elasticsearch_and_cassandra_mnesia / de6434377a1a928986f82f54c32b8dbd9c9bda2b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4268/217058/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4268/217058/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40c2841d1d502d.2024-04-24_08.18.57/index.html)
**OK: 447** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
looks ok

**Pull request merged**
