### PR TITLE
Get rid of base16

### PR DESCRIPTION
**Pull request by NelsonVides**
The `base16` library is not needed since OTP25: https://www.erlang.org/doc/apps/stdlib/binary.html#encode_hex/1 now the same functionality is in the binary module.

Note though that `erlcloud` pulls then version 1.0, but I've already submitted a PR to `erlcloud` upgrading that: https://github.com/erlcloud/erlcloud/pull/781

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/245971) / elasticsearch_and_cassandra_mnesia / 2e4b4de73a25d31ec15111f3a72786b7b65b4950
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4415/245971/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4415/245971/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40f12579d12cc7.2024-12-04_10.58.32/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/246645) / elasticsearch_and_cassandra_mnesia / 70f2a334de8750691d5a1618d885035dc10371d4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4415/246645/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4415/246645/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4011c9b31ad774.2024-12-04_21.24.23/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251511) / elasticsearch_and_cassandra_mnesia / 2decccac3d662aba192c7d248c002fd849985120
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4415/251511/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4415/251511/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4064f4edf6f496.2024-12-17_07.08.24/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by telezynski — APPROVED** [review]
Looks good!

**Pull request merged**
