### PR TITLE
Remove deprecated mod_revproxy

### PR DESCRIPTION
**Pull request by chrzaszcz**
This module is dead - it was impossible to configure it since version 4.2.0

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/117725) / small_tests / e23b199150ff9aeb9c5faaa9719b2aa18fdb51c3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3617/117725/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3617/117725/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-30_10.43.27/lib.mongooseim.logs/run.2022-03-30_10.43.27/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/117814) / small_tests / 4cd19d258194509bde9700590918746d2fb212e9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3617/117814/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3617/117814/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-30_11.39.08/lib.mongooseim.logs/run.2022-03-30_11.39.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/117818) / small_tests / f7d56ec80931502a87c1dd9a32b3550b46af15e2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3617/117818/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3617/117818/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-30_11.39.32/lib.mongooseim.logs/run.2022-03-30_11.39.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/117840) / small_tests / 6315f5647083a7dba1e388e62666d45ed1555071
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3617/117840/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3617/117840/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-30_11.43.59/lib.mongooseim.logs/run.2022-03-30_11.44.00/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Great, kill dead code with 🔥 
(Though now I'm left thinking, what was the purpose of such reverse proxy in MIM, how was it working and why was it added... 🤔 )

**Comment by chrzaszcz** [comment]
> Great, kill dead code with 🔥 (Though now I'm left thinking, what was the purpose of such reverse proxy in MIM, how was it working and why was it added... 🤔 )

The purpose was to use it as a regular web server. We dropped it when introducing the TOML config because it was super-complicated.

**Comment by gustawlippa** [comment]
There's one place with something relating to this I think: https://github.com/esl/MongooseIM/blob/66a1652820b5d122a07a4cb83f76380f8e770315/rebar.config#L24

**Comment by chrzaszcz** [comment]
> There's one place with something relating to this I think:
> 
> https://github.com/esl/MongooseIM/blob/66a1652820b5d122a07a4cb83f76380f8e770315/rebar.config#L24
Done

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/117890) / small_tests / ab4b9fc87528d3552f5c7e2e8364a4148fb58b85
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3617/117890/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3617/117890/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-03-30_14.42.09/lib.mongooseim.logs/run.2022-03-30_14.42.10/suite.log.html)

**Pull request merged**
