### PR TITLE
[WIP] tls 1.3 old

### PR DESCRIPTION
**Pull request by vkatsuba**
Test suite is failed:
- [ ] riak_mnesia
- [ ] internal_mnesia

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/80282) / small_tests / bf225d1ca27c85f03a5bfe7845ad0c6a4871c6fb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3344/80282/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3344/80282/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-10-18_16.00.51/lib.mongooseim.logs/run.2021-10-18_16.00.52/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/80387) / small_tests / 906ce3714d007f6e67f19a24bc1c7ae52b9c5652
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3344/80387/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3344/80387/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-10-18_17.56.01/lib.mongooseim.logs/run.2021-10-18_17.56.02/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/80414) / small_tests / 925aeddf5dff033657217375b397310b34454097
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3344/80414/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3344/80414/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-10-18_18.32.23/lib.mongooseim.logs/run.2021-10-18_18.32.23/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/80605) / small_tests / 3c1065829e91f01e21665ac0d5dedde5e8b98d42
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3344/80605/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3344/80605/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-10-19_18.18.14/lib.mongooseim.logs/run.2021-10-19_18.18.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/80656) / small_tests / 13a26ea12e4360ac5974740eeac7113eb8194c7a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3344/80656/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3344/80656/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-10-19_22.17.47/lib.mongooseim.logs/run.2021-10-19_22.17.48/suite.log.html)

**Comment by Neustradamus** [comment]
@vkatsuba: Any progress on this PR?

**Comment by chrzaszcz** [comment]
This is an outdated PR, and TLS 1.3 is already  supported (and enabled).

**Comment by vkatsuba** [comment]
Hey @Neustradamus! Unfortunately, I'm no longer supporting this project, but as far as I know, TLS 1.3 support has already been added to MongooseIM. You can find more details in the documentation here: https://github.com/esl/MongooseIM/blob/6.2.1/doc/configuration/TLS-hardening.md#otp-tls-hardening. Hope that helps!

**Pull request closed without merging**
