### PR TITLE
updating MIM badges to release 6.1.x

### PR DESCRIPTION
**Pull request by DenysGonchar**
updating MIM badges to release 6.1.x

FYI, documentation for 6.1.0 release is already updated:
- https://esl.github.io/MongooseDocs/6.1.0/

+adding missing parallel flag for coveralls GH action.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/180648) / small_tests / edaccc3129d4492a207157d5bdda5549c8d6b604
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4055/180648/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4055/180648/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-13_06.59.25/lib.mongooseim.logs/run.2023-07-13_06.59.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_25_arm64](https://circleci.com/gh/esl/MongooseIM/180991) / small_tests / adb20a9d63b204a7f8e7842382570db85776d840
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4055/180991/small_tests.25.3-arm64)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/181751) / small_tests / 71872b956ae0c99e00b29c7d11d05f64ba81a7da
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4055/181751/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4055/181751/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-07-20_23.11.41/lib.mongooseim.logs/run.2023-07-20_23.11.42/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good 👍

**Pull request merged**
