### PR TITLE
Use 'format_items = map' by default for config sections

### PR DESCRIPTION
**Pull request by chrzaszcz**
Clean up item formatting:
- For sections, use `format_items = map` by default.
- For lists, use `format_items = list` by default.

Remove explicit `format_items = map` for all sections.
For sections that are formatted as lists, use `format_items = list`. Trivial cases are converted to maps in this PR.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/124211) / small_tests / 1544b5647e927c6ae84410387854a4a1ac331ae9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3655/124211/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3655/124211/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-05-25_16.29.33/lib.mongooseim.logs/run.2022-05-25_16.29.33/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/124267) / small_tests / 5df266066b911b52c4df13d47ae95fae3c158ea2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3655/124267/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3655/124267/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-05-26_07.15.44/lib.mongooseim.logs/run.2022-05-26_07.15.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/124292) / small_tests / 651e21afed17ad9f17338ca4d49d7e9c68e7d7ff
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3655/124292/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3655/124292/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-05-26_09.12.17/lib.mongooseim.logs/run.2022-05-26_09.12.17/suite.log.html)

**Review by Premwoik — APPROVED** [review]
Looks good :)

**Review by arcusfelis — APPROVED** [review]

**Pull request merged**
