### PR TITLE
Instrument/hook handlers: auth - register

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to use `mongoose_instrument` for user registration metrics instead of handlers updating `mongoose_metrics`.

- Use eparate events are used for regular and anonymous users.
- `instrumentation` callback is added to `mongoose_gen_auth`.
- `accounts_SUITE` and `anonymous_SUITE` are updated, and they cover all events. This means that `metrics_register_SUITE` can be removed.
- `anonymous_purge` operation is now instrumented, so this hook doesn't need its instrumentation event anymore.
- no hooks are removed, because although `register_user` has no handlers, it looks useful for purposes other than instrumentation.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/222462) / elasticsearch_and_cassandra_mnesia / ddda747579c9f9e1f769004131e5ac7353936c05
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4301/222462/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4301/222462/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%407fdb07edd32f.2024-06-13_12.51.55/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/222905) / elasticsearch_and_cassandra_mnesia / eeeed78ab432dbc2ce614e39e369d41d662823dc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4301/222905/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4301/222905/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40537ecd0abf62.2024-06-14_11.09.54/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/222938) / elasticsearch_and_cassandra_mnesia / d2ab907f8c10a5593cf416f4e9dfe240945e928a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4301/222938/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4301/222938/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40cfb8d5b4d20f.2024-06-14_14.34.18/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
