### PR TITLE
Remove watchdog

### LINKED ISSUE #382: Watchdog is broken
[Watchdog](http://www.process-one.net/docs/ejabberd/guide_en.html#htoc102) is broken. We might try fixing it or simply remove it. I think (though might be wrong) this is not a frequently used feature. Look for `{error,bad_module}` in the listing below. The module responsible for this functionality is `ejabberd_system_monitor`.

```
40> AliceSpec.
[{username,<<"alice">>},
 {server,<<"localhost">>},
 {password,<<"w0KvVnqJGvrcwRv%2Ff59cm%2FyqzOXtVL4Ll0ofjD407C%2B0uEWnX2Sdf6n7jBJqO43v">>},
 {compression,<<"zlib">>}]
(search)`Alice7': {ok, Alice7, _, _} = escalus_connection:start(AliceSpec).
41> {ok, Alice8, _, _} = escalus_connection:start(AliceSpec).
{ok,{client,undefined,escalus_tcp,#Port<0.6630>,false,false,
            <0.110.0>,undefined},
    [{username,<<"alice">>},
     {server,<<"localhost">>},
     {password,<<"w0KvVnqJGvrcwRv%2Ff59cm%2FyqzOXtVL4Ll0ofjD407C%2B0uEWnX2Sdf6n7jBJqO43v">>},
     {compression,<<"zlib">>},
     {host,<<"localhost">>}],
    [{compression,false},
     {starttls,false},
     {stream_management,true},
     {advanced_message_processing,false}]}
42> escalus:send(Alice8, escalus_stanza:chat_to(<<"localhost/watchdog">>, <<"help">>)).
ok
43> flush().
Shell got {stanza,
              {client,undefined,escalus_tcp,#Port<0.6629>,false,false,
                  <0.103.0>,undefined},
              {xmlel,<<"stream:error">>,[],
                  [{xmlel,<<"conflict">>,
                       [{<<"xmlns">>,
                         <<"urn:ietf:params:xml:ns:xmpp-streams">>}],
                       []},
                   {xmlel,<<"text">>,
                       [{<<"xmlns">>,
                         <<"urn:ietf:params:xml:ns:xmpp-streams">>},
                        {<<"xml:lang">>,<<"en">>}],
                       [{xmlcdata,<<"Replaced by new connection">>}]}]}}
Shell got {stanza,{client,undefined,escalus_tcp,#Port<0.6629>,false,false,
                          <0.103.0>,undefined},
                  {xmlstreamend,<<"stream:stream">>}}
Shell got {stanza,
              {client,undefined,escalus_tcp,#Port<0.6630>,false,false,
                  <0.110.0>,undefined},
              {xmlel,<<"message">>,
                  [{<<"from">>,<<"localhost/watchdog">>},
                   {<<"to">>,<<"alice@localhost/escalus-default-resource">>},
                   {<<"type">>,<<"chat">>}],
                  [{xmlel,<<"body">>,[],
                       [{xmlcdata,
                            <<"Commands:\n  kill <node> <pid>\n  showlh <node>\n  setlh <node> <integer>">>}]},
                   {xmlel,<<"archived">>,
                       [{<<"by">>,<<"alice@localhost">>},
                        {<<"id">>,<<"A3REDES4BM81">>}],
                       []}]}}
ok
44> escalus:send(Alice8, escalus_stanza:chat_to(<<"localhost/watchdog">>, <<"showlh mongooseim@localhost">>)).
ok
45> flush().
Shell got {stanza,
              {client,undefined,escalus_tcp,#Port<0.6630>,false,false,
                  <0.110.0>,undefined},
              {xmlel,<<"message">>,
                  [{<<"from">>,<<"localhost/watchdog">>},
                   {<<"to">>,<<"alice@localhost/escalus-default-resource">>},
                   {<<"type">>,<<"chat">>}],
                  [{xmlel,<<"body">>,[],
                       [{xmlcdata,
                            <<"Current large heap: {error,bad_module}">>}]},
                   {xmlel,<<"archived">>,
                       [{<<"by">>,<<"alice@localhost">>},
                        {<<"id">>,<<"A3REDIV42T01">>}],
                       []}]}}
ok
```

### PR DESCRIPTION
**Pull request by ppikula**
closes #382 

I'm wondering what to do with the alarms application. Without watchdog it will be unused, but  it has an interesting idea: https://github.com/chrzaszcz/alarms/blob/master/src/alarms_folsom_handler.erl. 

Currently we are not using folsom, but maybe analogous module reporting to mongoose_metrics is a way to use this app.

What do you think?

### CODE REVIEW

**Comment by michalwski** [comment]
Yes, I think that would be a good idea. There is one problem though, `exometer` doesn't have equivalent for `folsom`'s history. As far as I can see this is used in the `alarms_folsom_handler.erl`.

**Comment by michalwski** [comment]
Please simplify `jlib:binary_to_jid` and friends by removing all parts parsing jid like `server/resource`. Also I think additional cleaning in routing should be done around the `server/resource` jid. F.e this [1] part in ejabberd_local.

[1]. https://github.com/esl/MongooseIM/blob/remove-watchdog/apps/ejabberd/src/ejabberd_local.erl#L395-L404

**Comment by fenek** [comment]
@michalwski 
I disagree, I use `server/resource` JIDs in some rare cases.

**Comment by michalwski** [comment]
Isn't there better idea then `server/resource`? This is ugly... What are these rare cases?

**Comment by fenek** [comment]
MUC Light compatibility mode. I have nothing against cleaning routing rules for such JIDs but I see no reason to ban such format, since it is perfectly valid JID (according to the specification).

**Comment by michalwski** [comment]
So If we want to stay with this rule than some tests covering such routing should be done in this PR.

**Comment by michalwski** [comment]
Actually the coverage around this rule is not that bad as I thought: https://coveralls.io/builds/3976329/source?filename=apps%2Fejabberd%2Fsrc%2Fejabberd_local.erl#L395

**Pull request merged**
