### PR TITLE
Map options for mod_muc_light

### PR DESCRIPTION
**Pull request by chrzaszcz**
Put `mod_muc_light` opts in a map with defaults.

Other changes:
- It was necessary to remove deps from `mod_inbox` - see the commit message for details.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113063) / small_tests / 47e7ee236d916ee402c90ad567c3ab3a6cf4f0b9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113063/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113063/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-08_16.46.56/lib.mongooseim.logs/run.2022-03-08_16.46.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/113100) / small_tests / fe288ea08891165e3883cbcc77e35940caf85c30
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113100/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113100/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-03-09_08.54.34/lib.mongooseim.logs/run.2022-03-09_08.54.34/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113133) / small_tests / 9702d839f7e94a658f222c193a613ca1cff7286e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113133/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113133/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-09_09.04.14/lib.mongooseim.logs/run.2022-03-09_09.04.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/113199) / small_tests / 30e851ba45e281d20d6e3f370b100afe4450f25a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113199/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113199/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-03-09_10.25.05/lib.mongooseim.logs/run.2022-03-09_10.25.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/113227) / small_tests / b564b05f3fa498a07dde0bb54bb5596144360799
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113227/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113227/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-03-09_10.38.21/lib.mongooseim.logs/run.2022-03-09_10.38.22/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_23](https://circleci.com/gh/esl/MongooseIM/113270) / small_tests / c196d559be7390ba1dca6bbbfc1f0f23b4dd0cb9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113270/small_tests.23.1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113270/small_tests.23.1/small/ct_run.mongooseim@localhost.2022-03-09_10.41.11/lib.mongooseim.logs/run.2022-03-09_10.41.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113308) / small_tests / 06a1100c31d4b5730f2350a008549b5f10a3bedf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3580/113308/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3580/113308/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-09_10.59.08/lib.mongooseim.logs/run.2022-03-09_10.59.08/suite.log.html)

**Review by gustawlippa — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
