### PR TITLE
Use mongoose_backend in mod_global_distrib_mapping

### PR DESCRIPTION
**Pull request by chrzaszcz**
Get rid of the dynamically compiled module.

Also: simplify functions that always returned `{ok, Val}`.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113433) / small_tests / 1e2be66e2bcf4f2224f43d58052903d7379d1970
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3582/113433/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3582/113433/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-09_14.12.38/lib.mongooseim.logs/run.2022-03-09_14.12.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113510) / small_tests / 3301486f9ee54571fb8ade951afc0627ba437b87
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3582/113510/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3582/113510/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-09_15.07.37/lib.mongooseim.logs/run.2022-03-09_15.07.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/113528) / small_tests / b00733a1dc8b0c6c55c0f815efc9735f41ac1b0c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3582/113528/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3582/113528/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-09_15.21.57/lib.mongooseim.logs/run.2022-03-09_15.21.58/suite.log.html)

**Review by gustawlippa — APPROVED** [review]
Nice! One more to go...

**Pull request merged**
