### PR TITLE
Use prebuilt Docker images with Erlang to build packages

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to use Docker images with Erlang built by [cimg-erlang](https://github.com/esl/cimg-erlang) and available at [erlangsolutions/erlang](https://hub.docker.com/repository/docker/erlangsolutions/erlang/tags) not only as Docker CircleCI exectors, but also as package builders.

Main changes:
- Update CircleCI to built packages for OS releases supported by [cimg-erlang](https://github.com/esl/cimg-erlang):
  - debian (bookworm, bullseye, buster),
  - ubuntu (oracular, noble, jammy, focal),
  - rockylinux (8, 9),
  - almalinux (8, 9).
- Update Dockerfiles and build scripts used to build packages.
  - Use a separate builder and target image.
  - Simplify and unify the scripts and Dockerfiles.
  - Update the package specs to support latest Ubuntu and Rocky/Alma releases.
  
For more details, see the commit messages.

Next steps:
- Publish the new packages. We could do it with the next minor release.

Other future improvements - IMO not needed for now:
- We could sync the target OS release list used by this repo and `cimg-erlang` to avoid possible mismatch. I don't see it as a big issue for now, because the OS releases don't change that often.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_26](https://circleci.com/gh/esl/MongooseIM/239809) / small_tests / 8e59f3ff196d3fb6e96eb0027e3017d9a476c0a1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4385/239809/small_tests.26.2.5.4-amd64) / [small](https://esl.github.io/html-zip-reader/PR/4385/239809/small_tests.26.2.5.4-amd64/small.tar.gz//ct_run.mongooseim@localhost.2024-10-29_17.11.33/lib.mongooseim.logs/run.2024-10-29_17.11.34/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_26](https://circleci.com/gh/esl/MongooseIM/239832) / small_tests / 924ffc232aa2e5df511ab0810e48e74acd18bb47
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4385/239832/small_tests.26.2.5.4-amd64) / [small](https://esl.github.io/html-zip-reader/PR/4385/239832/small_tests.26.2.5.4-amd64/small.tar.gz//ct_run.mongooseim@localhost.2024-10-29_17.22.01/lib.mongooseim.logs/run.2024-10-29_17.22.02/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/239862) / elasticsearch_and_cassandra_mnesia / 744e3886bf2dabf9498b2e7c109fe55a7cee5ba2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4385/239862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4385/239862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40057352d03ae2.2024-10-29_17.43.52/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/239903) / elasticsearch_and_cassandra_mnesia / dda6c9770d1e9ab826766e93da3fe40dac9fdac5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4385/239903/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4385/239903/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4068747e0d6e30.2024-10-30_07.56.40/index.html)
**OK: 473** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
