### PR TITLE
MIM-2328 Remove mongoose_sanity_checks_SUITE from big tests

### PR DESCRIPTION
**Pull request by telezynski**
This test suite is not needed anymore.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242862) / elasticsearch_and_cassandra_mnesia / 167390507454d0e0259340eca0f9f049f3cac94c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/index.html)
**OK: 0** / **Failed: 1** / User-skipped: 0 / **Auto-skipped: 521** 
<details><summary>ct_framework:error_in_suite</summary>


```erlang
{error,'mongoose_sanity_checks_SUITE cannot be compiled or loaded'}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/big_tests.tests.mongoose_sanity_checks_SUITE.logs/run.2024-11-22_13.11.39/ct_framework.error_in_suite.html)
</details>
<details><summary>mam_SUITE:init_per_suite</summary>


```erlang
{fail,"cth_surefire:pre_init_per_suite/3 CTH call failed"}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/big_tests.tests.mam_SUITE.logs/run.2024-11-22_13.11.40/mam_suite.init_per_suite.html)
</details>
<details><summary>gdpr_SUITE:init_per_suite</summary>


```erlang
{fail,"cth_surefire:pre_init_per_suite/3 CTH call failed"}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/big_tests.tests.gdpr_SUITE.logs/run.2024-11-22_13.11.42/gdpr_suite.init_per_suite.html)
</details>
<details><summary>mongoose_cassandra_SUITE:init_per_suite</summary>


```erlang
{fail,"cth_surefire:pre_init_per_suite/3 CTH call failed"}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/big_tests.tests.mongoose_cassandra_SUITE.logs/run.2024-11-22_13.11.43/mongoose_cassandra_suite.init_per_suite.html)
</details>
<details><summary>mongoose_elasticsearch_SUITE:init_per_suite</summary>


```erlang
{fail,"cth_surefire:pre_init_per_suite/3 CTH call failed"}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4401/242862/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40699a663f620c.2024-11-22_13.11.39/big_tests.tests.mongoose_elasticsearch_SUITE.logs/run.2024-11-22_13.11.44/mongoose_elasticsearch_suite.init_per_suite.html)
</details>

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/242897) / elasticsearch_and_cassandra_mnesia / 883276ffd49de2dddb024758ce1bfec24e4e2971
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4401/242897/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4401/242897/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%408f49fd5a5f6d.2024-11-25_09.21.36/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/244506) / elasticsearch_and_cassandra_mnesia / 1ecc4b22d5e12f835602a3cd86cf87d1cfa5bb31
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4401/244506/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4401/244506/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4039172dae018b.2024-12-03_11.09.02/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/245823) / elasticsearch_and_cassandra_mnesia / 926db981cdebdf703056ffce6cab848ec5b8856a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4401/245823/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4401/245823/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%400802931462ad.2024-12-04_09.01.40/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/248257) / elasticsearch_and_cassandra_mnesia / 521100f1c3e6152ee1d811b1fa57828efa23bf15
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4401/248257/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4401/248257/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%408842db1aa7ab.2024-12-09_08.50.48/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
Looks good 👍

**Pull request merged**
