### PR TITLE
Improve GraphQL error handling for MUC

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to check and test error conditions in the MUC GraphQL API.

Main changes:
- Pass the whole room JID on room creation. It is more straightforward than passing both JID parts separately.
- Room JIDs should be bare.
- Nicks should be valid resource names.
- MAM-related operations check if the module is enabled.
- All JID types require the local part now.

Discovered bugs that should be fixed separately:
- If `mod_mam_muc` is enabled for `muclight.localhost`, it also stores messages for `muc.localhost`. Actually this misconfiguration was present in the tests, which were passing because of the bug.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154141) / small_tests / 6fd2dae77904660f5eb97d775b44f9ab79385fea
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154141/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154141/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_13.46.00/lib.mongooseim.logs/run.2022-11-24_13.46.01/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154167) / small_tests / de2e9dd5364b00fb565a87bfa4b43055727b854c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154167/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154167/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_14.03.36/lib.mongooseim.logs/run.2022-11-24_14.03.36/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154191) / small_tests / dd438482861e7226aad02745b38f54c512c272e5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154191/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154191/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_14.21.13/lib.mongooseim.logs/run.2022-11-24_14.21.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154215) / small_tests / 53f19a73865a01f74fc06a24fd3ba53e62947044
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154215/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154215/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_14.25.00/lib.mongooseim.logs/run.2022-11-24_14.25.01/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154242) / small_tests / ebc10d4e0dee1c796e66930001d5fa1f764c3392
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154242/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154242/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_14.30.24/lib.mongooseim.logs/run.2022-11-24_14.30.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154269) / small_tests / 8f676bd62ca980390f58a6bd9f58a0cae9cf070c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154269/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154269/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-24_14.41.01/lib.mongooseim.logs/run.2022-11-24_14.41.01/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154318) / small_tests / 0080cf500f6165aad79fe7faf57b2d15325c22f7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154318/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154318/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-25_08.25.55/lib.mongooseim.logs/run.2022-11-25_08.25.55/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/154390) / small_tests / 2a96fa9167d2703fd4bc66e6ba996e78489d7eb4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3875/154390/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3875/154390/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-25_09.57.33/lib.mongooseim.logs/run.2022-11-25_09.57.34/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]

**Pull request merged**
