### PR TITLE
Anonymous auth supports mnesia and cets backends

### PR DESCRIPTION
**Pull request by NelsonVides**
MIM-2066
`ejabberd_auth_anonymous` has now two backends, mnesia and cets, which can be configured.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/195541) / elasticsearch_and_cassandra_mnesia / fc5979cb92d87826be4c663e49f53bb3035ede49
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4148/195541/elasticsearch_and_cassandra_mnesia.26.0.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4148/195541/elasticsearch_and_cassandra_mnesia.26.0.2-amd64/big/ct_run.test%40b59141cbd696.2023-10-12_14.26.13/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/196044) / elasticsearch_and_cassandra_mnesia / fd682c50e5c9fe7d3ecd7ea4aa8b5b289ca7f176
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4148/196044/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4148/196044/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4076d9df9028ba.2023-10-17_08.50.37/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/196088) / elasticsearch_and_cassandra_mnesia / e296b936f334c3c383d3728f1c7dd0f62da82d32
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4148/196088/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4148/196088/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%4012a807baeae7.2023-10-17_09.31.22/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/196220) / elasticsearch_and_cassandra_mnesia / 0e5a5c46af659e83aabc115b6eb0074b3ff216ba
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4148/196220/elasticsearch_and_cassandra_mnesia.26.1.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4148/196220/elasticsearch_and_cassandra_mnesia.26.1.2-amd64/big/ct_run.test%40766caa370e21.2023-10-17_17.09.58/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
ok

**Review by DenysGonchar — COMMENTED** [review]
looks good

**Pull request merged**
