### PR TITLE
Changing config in mod_ping to map

### PR DESCRIPTION
**Pull request by JanuszJakubiec**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/112892) / small_tests / c02b93dbe02653c854b0e236d00a6d831aa7e740
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3579/112892/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3579/112892/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-08_11.07.08/lib.mongooseim.logs/run.2022-03-08_11.07.08/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/112926) / small_tests / a58d1953fb0c17c4eda1061dc7651c7045e13190
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3579/112926/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3579/112926/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-08_11.28.02/lib.mongooseim.logs/run.2022-03-08_11.28.02/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/112940) / small_tests / f5a3620ee63da0db52385613ad8d8aadab00e514
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3579/112940/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3579/112940/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2022-03-08_11.40.28/lib.mongooseim.logs/run.2022-03-08_11.40.28/suite.log.html)

**Review by gustawlippa — APPROVED** [review]
Looks good! 👍

**Pull request merged**
