### PR TITLE
Update to the latest escalus

### PR DESCRIPTION
**Pull request by NelsonVides**
Upgrading escalus, escalus deps, and also getting rid of what happened to the rebar.lock when a rebar different than that of the repository was used.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9103.1](https://travis-ci.org/esl/MongooseIM/jobs/760020681) / Erlang 23.0.3 / small_tests / 5c34c0922af4ae2ec508547fa5d4ccaff3387b3c
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3036/9103/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3036/9103/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-22_17.09.29/lib.mongooseim.logs/run.2021-02-22_17.09.29/suite.log.html)

**Comment by DenysGonchar** [comment]
why don't we just update the rebar3 stored in the repo instead of downgrading the format of the file?

**Comment by NelsonVides** [comment]
> why don't we just update the rebar3 stored in the repo instead of downgrading the format of the file?

I think that should be done consistently in the root of the repo as well as the big_test case, and perhaps it could be done together with a deps upgrade, no preference, but right now my urgency is getting a escalus that doesn't make ct useless :|

**Review by DenysGonchar — APPROVED** [review]
looks ok

**Pull request merged**
