### PR TITLE
Fix flaky TLS tests for GraphQL

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to properly fix the TLS error handling tests, which were sometimes returning `connection_closed` instead of the proper certificate error.

The reason for this was that `fusco` (just like `gun` and `httpc`) opens the connection and immediately tries to send the request. When getting the response:
- If the server closed the connection already, `connection_closed` would be the result.
- Otherwise, the result would be the TLS error.

To mitigate this, this PR uses the lower-level `ssl` module directly, breaking up the test into steps.
This way, the error can be checked without sending any further data.
The only downside was the need for manually constructing the request and parsing the response. To avoid coding this from scratch, the already existing lower-level utilities from `fusco` and `httpc` were used.

A proper solution would be to add an option to one of the client libraries to break up the request process into parts, but it would be too much for this simple issue.

---

To ensure that this is fixed:
- I repeated the `tls_enabled` group 100 times locally, with each group running each test 100 times instead of once, resulting in 100 runs of 900 parallel tests - 90000 tests in total (!)
- I repeated this on CI with 10 groups of 90 tests.
- I also repeated this locally with 10 groups of 90 tests, where the `ssl` library was slowed down on the client side by tracing it. Without the fix, it was failing always.

All tests succeeded.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218816) / elasticsearch_and_cassandra_mnesia / 835368352d201ca42e7dc8d90b2a90efe1c8025d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4279/218816/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4279/218816/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40368fbc4e2f27.2024-05-16_12.08.46/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218852) / elasticsearch_and_cassandra_mnesia / 20c460d0b209216002eeed660d19045f0bb386af
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4279/218852/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4279/218852/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40e12a7d2ae234.2024-05-16_13.21.34/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218926) / elasticsearch_and_cassandra_mnesia / 896ffa6bf25b826f052f14fe04b3d7f304fdb388
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4279/218926/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4279/218926/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%401323b4156b71.2024-05-16_14.02.03/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218954) / elasticsearch_and_cassandra_mnesia / b09db2297966e14016d08a3dde68b55573fc2fa6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4279/218954/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4279/218954/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4080acb0934a12.2024-05-16_14.07.55/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/218995) / elasticsearch_and_cassandra_mnesia / 35c374d8fdb0c5727208c502de95cda04414db3f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4279/218995/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4279/218995/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%400fd8c00de83b.2024-05-17_07.12.46/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by JanuszJakubiec — APPROVED** [review]

**Review by JanuszJakubiec — COMMENTED** [review]
Looks good

**Pull request merged**
