### PR TITLE
Improve error handling in token

### PR DESCRIPTION
**Pull request by kamilwaz**
Improve error handling in token

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152558) / small_tests / bd9625b4bf4a085c377cc50c3ab90d5273b691e8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/152558/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/152558/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_10.58.49/lib.mongooseim.logs/run.2022-11-17_10.58.50/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152631) / small_tests / dcec996bc95389813b7f0b56b46fbabcfb393aac
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/152631/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/152631/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_13.06.44/lib.mongooseim.logs/run.2022-11-17_13.06.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152660) / small_tests / e9cd3e09a39796c87d41e77a3acd3e7b4e00b5d1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/152660/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/152660/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_14.14.31/lib.mongooseim.logs/run.2022-11-17_14.14.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152683) / small_tests / f3d93e33b15d303451f2a7caf08ba6109904d6bd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/152683/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/152683/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_14.16.26/lib.mongooseim.logs/run.2022-11-17_14.16.26/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
The changes look good in general, but executing the commands in my shell shows the following issues still present:

### JID without user name is accepted

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153071) / small_tests / 20ed23ea9f907e576480f0f75ed8d9dd07bb6acb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/153071/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/153071/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-21_08.06.03/lib.mongooseim.logs/run.2022-11-21_08.06.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153339) / small_tests / 3c5b223a4ac47efe11e0a3c4e832ab79435bef11
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/153339/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/153339/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-21_14.09.35/lib.mongooseim.logs/run.2022-11-21_14.09.35/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/153571) / small_tests / e90c45779eabdd16f89038f965e17e45c4e00495
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3863/153571/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3863/153571/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-22_07.42.04/lib.mongooseim.logs/run.2022-11-22_07.42.05/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good :+1:

**Pull request merged**
