### PR TITLE
Support setting and getting custom configuration options in MUC Light GraphQL API

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses https://github.com/esl/MongooseIM/issues/3664    MIM-1686

Proposed changes include:
* Setting/getting fields
* Tests

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/133997) / small_tests / b6cb86b398a4efc09b80353d6e0a2af44d2b4489
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3742/133997/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3742/133997/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-29_08.46.46/lib.mongooseim.logs/run.2022-08-29_08.46.47/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134079) / small_tests / bf99100386fc19ec3a0d8f33288bbaf62f5f62d7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3742/134079/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3742/134079/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-30_08.55.02/lib.mongooseim.logs/run.2022-08-30_08.55.03/suite.log.html)

**Review by chrzaszcz — COMMENTED** [review]
Looks good, I added minor comments.

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/134155) / small_tests / f9d89a0e087f2654cb4ffec05bbc02a4cf23f364
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3742/134155/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3742/134155/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-08-31_13.06.03/lib.mongooseim.logs/run.2022-08-31_13.06.04/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]

**Pull request merged**
