### PR TITLE
Set cookie to mongooseim

### PR DESCRIPTION
**Pull request by chrzaszcz**
The default cookie should be the same as the app name.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/161385) / ldap_mnesia / 01045dfc434258dd9249e7d0a81765dbbf005275
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3930/161385/ldap_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/161407) / small_tests / 1f72f88f128b6c34225fae9ab21ff3783abffa98
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3930/161407/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3930/161407/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-12_07.18.21/lib.mongooseim.logs/run.2023-01-12_07.18.22/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/161435) / small_tests / 9bf924694b4552e043c594c18c497c0afbc782a6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3930/161435/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3930/161435/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-12_07.54.34/lib.mongooseim.logs/run.2023-01-12_07.54.35/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/161465) / small_tests / 24b3822a770892ba30434c2c2d403e42f6071a0b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3930/161465/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3930/161465/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-12_11.20.24/lib.mongooseim.logs/run.2023-01-12_11.20.24/suite.log.html)

**Review by DenysGonchar — APPROVED** [review]
LGTM

**Comment by DenysGonchar** [comment]
The default cookie should be the same as the app name.

**Pull request merged**
