### PR TITLE
Remove dynamically compiled modules

### PR DESCRIPTION
**Pull request by gustawlippa**
This PR removes dynamically compiled `_backend` modules and adds real proxy modules instead.
It also removes some dynamically compiled modules that were not backends.

`mod_bosh`, `mod_global_distrib` and `mod_pubsub` are left for later.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/85813) / small_tests / 94b2e300908443a0941e0ab9c676a96789f8afe4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3394/85813/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3394/85813/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-09_15.02.42/lib.mongooseim.logs/run.2021-11-09_15.02.43/suite.log.html)

**Comment by mongoose-im** [comment]
[dynamic_domains_pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/85821) / pgsql_mnesia / 94b2e300908443a0941e0ab9c676a96789f8afe4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3394/85821/pgsql_mnesia.24.0-1)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/85846) / small_tests / 55434820940eddf3ad904af36a9631bdd39972e5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3394/85846/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3394/85846/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-09_15.15.40/lib.mongooseim.logs/run.2021-11-09_15.15.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/85897) / small_tests / 5e3aa4cf3e4f5fb431bfb3a7591a5fb2deec1297
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3394/85897/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3394/85897/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-09_16.10.11/lib.mongooseim.logs/run.2021-11-09_16.10.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/85901) / small_tests / f71b7f021a64d16219f976ce18b30a9b54ade672
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3394/85901/small_tests.24.0.5) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3394/85901/small_tests.24.0.5/small/ct_run.mongooseim@localhost.2021-11-09_16.12.54/lib.mongooseim.logs/run.2021-11-09_16.12.54/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Extensive load tests showed no difference in performance. Test were performed for:
- One to one chat with MAM and Inbox
- One to one chat w/MAM but w/o Inbox
- MAM lookup
- MUC Light w/o Inbox

**Pull request merged**
