### PR TITLE
Change config in muclight was replacing old config.

### PR DESCRIPTION
**Pull request by jaspreet-android**
This PR addresses [#4173 ](https://github.com/esl/MongooseIM/issues/4173)

Proposed changes include: 
This change will fix the config in muc-light which was replacing the old config to the default value.

### CODE REVIEW

**Comment by jaspreet-android** [comment]
> Hi, thanks for the pull request. We would have to have tests for the fix inside muc_light suite in the big tests directory: https://github.com/esl/MongooseIM/blob/master/big_tests/tests/graphql_muc_light_SUITE.erl

Screenshot 2023-11-21 at 9 01 23 PM
I think test is passing on my side.

**Review by NelsonVides — CHANGES_REQUESTED** [review]
Hi @jaspreet-android 
Thanks a lot for this PR, seems like sensible code, however, it lacks *new* tests, so we can't accept it without a proof that the issue was there and the source code changes indeed fixed it. Please add tests for any bugfix submitted. I'll work on this sooner than later within the scheduled sprint planning of MIM in case you didn't manage to do so earlier.

**Comment by NelsonVides** [comment]
@jaspreet-android I just tested locally, and `muc_light_SUITE` (not `graphql_muc_light_SUITE` as you pasted in your screenshot), fails in my machine. This needs fixing, old tests can't fail and new functionality must come with new tests.

**Comment by jaspreet-android** [comment]
This is fixed as in master, so I am closing it.

**Pull request closed without merging**
