### PR TITLE
Mongoose c2s

### PR DESCRIPTION
**Pull request by NelsonVides**
This is a feature branch for the new `mongoose_c2s` prototype. The goal is to have all of CI re-enabled and green.

Pending are things that were partially inside of the old `ejabberd_c2s`:
- [x] Presences: escalus needs them to function.
- [x] Ping
- [x] Stream management
- [x] CSI
- [x] Privacy lists
- [x] Last
- [x] Register

And tests that used to depend on the internals of `ejabberd_c2s`, `ejabberd_c2s_sup`, or the older version of `ranch`:
- [x] fix new version of ranch
- [x] Refactor tests using old c2s internals to be compatible with the new one
- [x] Fix all remaining disabled test suites
- [x] Verify test coverage does not go down

### CODE REVIEW

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/137894) / ldap_mnesia / 05df7d144eda1ed31394276e0c87ac3883d80e2a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/137894/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/137894/ldap_mnesia.24.3.4/big/ct_run.test%400e668b939f40.2022-09-20_13.33.15/index.html)
**OK: 4** / Failed: 0 / **User-skipped: 6** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/137924) / ldap_mnesia / 6a2100cbc8be330333c601f10eacd044a0f8db5a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/137924/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/137924/ldap_mnesia.24.3.4/big/ct_run.test%40ac2da6339e41.2022-09-20_13.54.33/index.html)
**OK: 789** / Failed: 0 / **User-skipped: 425** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/138715) / ldap_mnesia / 1023aa71ebe945b7a0c5778ff28e6f9e2ce27b81
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/138715/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/138715/ldap_mnesia.24.3.4/big/ct_run.test%40e3eac8308b0a.2022-09-23_09.24.00/index.html)
**OK: 789** / Failed: 0 / **User-skipped: 425** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/138793) / ldap_mnesia / 5f5c26e6ee84ae71b897c7c042ae7ed8ce21108b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/138793/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/138793/ldap_mnesia.24.3.4/big/ct_run.test%400bcbec15de60.2022-09-23_09.51.36/index.html)
**OK: 794** / Failed: 0 / **User-skipped: 425** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/138840) / small_tests / 197643601defdc3c2b11c2f90b27ea06d568fc86
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/138840/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/138840/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-09-23_12.24.24/lib.mongooseim.logs/run.2022-09-23_12.24.24/suite.log.html)

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/138843) / ldap_mnesia / 197643601defdc3c2b11c2f90b27ea06d568fc86
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/138843/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/138843/ldap_mnesia.24.3.4/big/ct_run.test%40a7f084676910.2022-09-23_12.24.07/index.html)
**OK: 813** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/140825) / ldap_mnesia / 1608c49b882a6b55bac5ebcf2dfd2b91e504fdb9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/140825/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/140825/ldap_mnesia.24.3.4/big/ct_run.test%402c7612165031.2022-10-03_12.18.04/index.html)
**OK: 865** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/140951) / ldap_mnesia / 6f9302eadd1f2ace8d1b942dd5a4924381c0a3c2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/140951/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/140951/ldap_mnesia.24.3.4/big/ct_run.test%40129bf0298112.2022-10-03_14.53.49/index.html)
**OK: 1043** / Failed: 0 / **User-skipped: 427** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_24](https://circleci.com/gh/esl/MongooseIM/141057) / ldap_mnesia / 121cdf973b82ab17696c64de51209cf18452df1f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/141057/ldap_mnesia.24.3.4)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/141057/ldap_mnesia.24.3.4/big/ct_run.test%407b5e7e268ec1.2022-10-04_06.25.23/index.html)
**OK: 1218** / Failed: 0 / **User-skipped: 431** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[dynamic_domains_mysql_redis_25](https://circleci.com/gh/esl/MongooseIM/141339) / mysql_redis / 458e76557b122c644e3b6d7f69e5aa705cc37262
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/141339/mysql_redis.25.0.1)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141309) / small_tests / 0ff33d6018dcd64f49fdb6cade75b00fde7571cc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/141309/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/141309/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_08.29.04/lib.mongooseim.logs/run.2022-10-04_08.29.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141551) / small_tests / 87e25f6f10b48daf47c040ac6bdc98523479236c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/141551/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/141551/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_11.45.54/lib.mongooseim.logs/run.2022-10-04_11.45.54/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/141932) / small_tests / 0d487f8751ac9f298e5d7bc6fea143717d2f0d18
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/141932/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/141932/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-04_14.06.41/lib.mongooseim.logs/run.2022-10-04_14.06.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/142679) / small_tests / a50b2b1cafb8a2e16686198b5bd8b52e08a32371
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/142679/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/142679/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-06_12.16.23/lib.mongooseim.logs/run.2022-10-06_12.16.24/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/143002) / small_tests / 636aa93566986d59f24860677f64c51754b016ca
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/143002/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/143002/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-07_14.14.16/lib.mongooseim.logs/run.2022-10-07_14.14.16/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/143558) / small_tests / e3a74aef0eb66ab4256fa1a1fafe13196556c236
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/143558/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/143558/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-11_11.36.41/lib.mongooseim.logs/run.2022-10-11_11.36.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/145455) / small_tests / bbc6885c1a612791250cf8285c99a3a1bdb1acb5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/145455/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/145455/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-19_12.20.40/lib.mongooseim.logs/run.2022-10-19_12.20.40/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147552) / small_tests / 49eb66ceb5bb6df8a0d8883916c42a2524cdd232
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/147552/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/147552/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_02.51.39/lib.mongooseim.logs/run.2022-10-28_02.51.40/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151001) / small_tests / c69582426e22aa2e1c63aa66161d542f5a3c8c00
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/151001/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/151001/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-10_09.27.56/lib.mongooseim.logs/run.2022-11-10_09.27.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/151672) / small_tests / 707f6d6bb6b72138f9b551d8a5e73a10284f0250
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/151672/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/151672/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-14_14.23.59/lib.mongooseim.logs/run.2022-11-14_14.23.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152135) / small_tests / a59c2b332ac86b054cc478d7ab21f621b4ca7072
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/152135/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/152135/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_08.59.04/lib.mongooseim.logs/run.2022-11-16_08.59.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152318) / small_tests / a35467842705f07a19d67735fa7e889a152abf4d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/152318/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/152318/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_13.24.10/lib.mongooseim.logs/run.2022-11-16_13.24.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152452) / small_tests / 1f1e4f95f86f4aad74cf29c3ac86f7092d00ca1e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/152452/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/152452/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-16_15.16.34/lib.mongooseim.logs/run.2022-11-16_15.16.34/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/152518) / small_tests / 29c7bdc50507ce92e6486f75da6d6fb6c0b7e2c8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/152518/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/152518/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-11-17_10.16.25/lib.mongooseim.logs/run.2022-11-17_10.16.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/155697) / small_tests / e2a049368f5e626ceb302894d07990e4d03448c2
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/155697/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/155697/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-02_10.27.21/lib.mongooseim.logs/run.2022-12-02_10.27.22/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/155975) / small_tests / 22ebb0b7545269b669aa959d15be860ca38149c4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/155975/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/155975/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-02_14.35.32/lib.mongooseim.logs/run.2022-12-02_14.35.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158282) / small_tests / 87560036b568e6c9a22625d40c6be8d08afc771b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/158282/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/158282/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-16_10.34.17/lib.mongooseim.logs/run.2022-12-16_10.34.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/160042) / small_tests / bb5e4328fea128c443c3cb982a3771628af7c5ec
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/160042/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/160042/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-04_12.50.58/lib.mongooseim.logs/run.2023-01-04_12.50.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/160065) / small_tests / 025f2a78fcaf2902d8c96875559417838b234825
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/160065/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/160065/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-04_12.57.10/lib.mongooseim.logs/run.2023-01-04_12.57.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/160360) / small_tests / 6d836ef15e619914577c1862c0bcc6d2c01ded93
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/160360/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/160360/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-05_15.43.45/lib.mongooseim.logs/run.2023-01-05_15.43.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/160740) / small_tests / 682387432969bd05d3ff852b55f8671ad66a23a4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/160740/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/160740/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-09_13.01.58/lib.mongooseim.logs/run.2023-01-09_13.01.58/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/160895) / small_tests / fc5b4c205688724a79cee6a805a2700ebec5cd56
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/160895/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/160895/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-09_17.06.06/lib.mongooseim.logs/run.2023-01-09_17.06.06/suite.log.html)

**Comment by mongoose-im** [comment]
[riak_mnesia_24](https://circleci.com/gh/esl/MongooseIM/161103) / riak_mnesia / 00ad413fdfdf4b3d9201aada49a330830d7f53b8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/161103/riak_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/161330) / small_tests / 7f34b4c22053f4e7456b272536a83cf5755c12eb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/161330/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/161330/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-11_16.42.08/lib.mongooseim.logs/run.2023-01-11_16.42.09/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/162455) / small_tests / 7849967ed7611e3c14489a68599b5532aa2cea63
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/162455/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/162455/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-23_16.49.42/lib.mongooseim.logs/run.2023-01-23_16.49.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/162479) / small_tests / b6343e1fb8461d050bae5c2e948070df0a1b6d13
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/162479/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/162479/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-23_17.15.25/lib.mongooseim.logs/run.2023-01-23_17.15.25/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/162508) / small_tests / 8d3e8821b4e40cb1e40f821421faab9a9b6c53ad
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/162508/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/162508/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-23_17.41.56/lib.mongooseim.logs/run.2023-01-23_17.41.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/162933) / small_tests / ce82e621a2810801fce57a216df959a5f6a202dc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/162933/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/162933/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-26_09.02.31/lib.mongooseim.logs/run.2023-01-26_09.02.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163529) / small_tests / a79e63fdb14aebe090297f9d50f97b0a1f98264c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/163529/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/163529/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-27_11.30.43/lib.mongooseim.logs/run.2023-01-27_11.30.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163754) / small_tests / e31c8c82ba0e07ec06c4b0cc112d54e4bc28252b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/163754/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/163754/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-27_14.47.34/lib.mongooseim.logs/run.2023-01-27_14.47.35/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163992) / small_tests / 85fc53adf4dfeebea31a9c23db9271c7bf720ac0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/163992/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/163992/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-30_08.18.54/lib.mongooseim.logs/run.2023-01-30_08.18.55/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/164016) / small_tests / 8f20f7f2515affa307b38a89a937cbb373de2943
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3765/164016/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3765/164016/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-30_08.50.28/lib.mongooseim.logs/run.2023-01-30_08.50.29/suite.log.html)

**Comment by chrzaszcz** [comment]
Postponing the merge to master until this PR is load-tested.

**Comment by chrzaszcz** [comment]
**Load test report summary:** the c2s rework caused no statistically significant changes in performance. A more significant improvement in CPU usage of 1-4% was seen between PR-3394 and PR-3948/PR-3765, i.e. before the c2s rework. This was not investigated any further because it was out of scope of the c2s load tests.

One missing metric (`mam_lookup`) was detected for both code versions – this can be investigated separately.

**Review by DenysGonchar — APPROVED** [review]
this feature branch is ready to be merged, all the remaining minor tasks can be continued on master.

**Pull request merged**
