### PR TITLE
Remove imports, use library function [refactor]

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "just found some code which is a bit weird".

Proposed changes include:
* use jid:are_bare_equal instead of writing the same function in the modules.
* don't use imports in mam to make code a bit cleaner - we usually use the imported function only once.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/144479) / small_tests / e850ec74257afbbc6e0e927e66a1b1ebfb91b98c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3809/144479/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3809/144479/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-13_09.00.31/lib.mongooseim.logs/run.2022-10-13_09.00.32/suite.log.html)

**Comment by mongoose-im** [comment]
[pgsql_mnesia_25](https://circleci.com/gh/esl/MongooseIM/144489) / pgsql_mnesia / e850ec74257afbbc6e0e927e66a1b1ebfb91b98c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3809/144489/pgsql_mnesia.25.0.1)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3809/144489/pgsql_mnesia.25.0.1/big/ct_run.test%40ff627101cd7e.2022-10-13_09.02.06/index.html)
**OK: 4340** / Failed: 0 / **User-skipped: 97** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/144504) / small_tests / 5d14895f6bddc3fbb08a92cd4727148d71fe3260
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3809/144504/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3809/144504/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-13_09.24.13/lib.mongooseim.logs/run.2022-10-13_09.24.13/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
I like these kinds of fast PRs 😛

**Pull request merged**
