### PR TITLE
Test clustering and domain management with dynamic domains

### PR DESCRIPTION
**Pull request by chrzaszcz**
Test clustering with dynamic domains.

To do this, the dynamic domains needed to be configured with `service_domain_db` to survive app restart.
This is the expected way to configure dynamic domains, so it makes the tested configuration closer to the production one.

The changes exposed a bug in `service_domain_db:sync/0`. This helper function was broken and was successfully eliminated from the code.

As `service_domain_db` needed to be touched, domain-related test suites are also enabled for dynamic domains now.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/72416) / small_tests / fb0b90a92ecc24740a7ee935e51cae9d7f261ab6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3266/72416/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3266/72416/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-14_07.05.06/lib.mongooseim.logs/run.2021-09-14_07.05.06/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/72437) / small_tests / 346ed45563a4edd2fb0e958823302d21476c1136
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3266/72437/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3266/72437/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-14_07.11.29/lib.mongooseim.logs/run.2021-09-14_07.11.29/suite.log.html)

**Comment by mongoose-im** [comment]
[internal_mnesia_24](https://circleci.com/gh/esl/MongooseIM/72602) / internal_mnesia / 16cf8ede83f7cfae39ad0ff4958bc1bdd9010f1b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3266/72602/internal_mnesia.24.0.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/72680) / small_tests / a760fed5a5590fc3d7f8059e5e7d51e6c988a910
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3266/72680/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3266/72680/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-14_13.55.03/lib.mongooseim.logs/run.2021-09-14_13.55.04/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/72731) / small_tests / 0d8555924f19745a5e4d1a9ca6035fc9f5fc8b47
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3266/72731/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3266/72731/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-14_14.34.41/lib.mongooseim.logs/run.2021-09-14_14.34.41/suite.log.html)

**Review by vkatsuba — APPROVED** [review]

**Pull request merged**
