### PR TITLE
Prepared queries for modules

### PR DESCRIPTION
**Pull request by arcusfelis**
Rebased
https://github.com/esl/MongooseIM/pull/3025

Prepared queries for:
- `mod_mam` #2961, #2977
- `mod_roster` #2985
- `mod_privacy` #3004
- `mod_muc_light` #3011
- `mod_last` #3019
- `mod_offline` #3040
- `mod_muc` #3028

### CODE REVIEW

**Comment by mongoose-im** [comment]
[9115.1](https://travis-ci.org/esl/MongooseIM/jobs/760421665) / Erlang 23.0.3 / small_tests / 26521e4c3f6e844d78f6f9636f8112759b019085
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3039/9115/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3039/9115/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-02-25_08.50.00/lib.mongooseim.logs/run.2021-02-25_08.50.00/suite.log.html)

**Comment by mongoose-im** [comment]
[9154.1](https://travis-ci.org/esl/MongooseIM/jobs/760939053) / Erlang 23.0.3 / small_tests / ad1b72d1e79d961817399ee28cf677dd2c1d5a25
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3039/9154/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3039/9154/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-03-01_13.15.09/lib.mongooseim.logs/run.2021-03-01_13.15.09/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
This is a huge chunk of great work!

All PR's were reviewed before.
A quick look at the changes shows no issues.

However, the MUC PR is not merged here: https://github.com/esl/MongooseIM/pull/3028

**Review by chrzaszcz — CHANGES_REQUESTED** [review]
I realized we need to merge the MUC PR here.

**Comment by mongoose-im** [comment]
[9155.1](https://travis-ci.org/esl/MongooseIM/jobs/760951057) / Erlang 23.0.3 / small_tests / 7707c01d08e5e57ae4ba9f1da43e0636f5ab8a45
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/3039/9155/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/3039/9155/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2021-03-01_14.49.59/lib.mongooseim.logs/run.2021-03-01_14.50.00/suite.log.html)

**Comment by chrzaszcz** [comment]
@arcusfelis could you update the PR description so that we don't lose track of the PR's merged to this branch before you rebased it and changed the commit history?

**Review by chrzaszcz — APPROVED** [review]
Looks good after adding MUC

**Pull request merged**
