### PR TITLE
[merge after #3907] Test with OTP 25.2

### PR DESCRIPTION
**Pull request by chrzaszcz**
Test the latest Erlang/OTP version on CircleCI.
The image is using a newer OpenSSL as well (3.0.2), which required small corrections in CSR generation in big tests.

**Don't merge before #3907 is merged to master.**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158887) / small_tests / d1f5c287043d477a5f26360bff941a3da1ac70fa
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3906/158887/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3906/158887/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-21_15.33.25/lib.mongooseim.logs/run.2022-12-21_15.33.26/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158943) / small_tests / 0073aa1b8a34ede679e9caeb8202a0465c8a090d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3906/158943/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3906/158943/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-22_13.24.50/lib.mongooseim.logs/run.2022-12-22_13.24.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158969) / small_tests / 865329b09c87e04d262c4069ce081bc403064614
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3906/158969/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3906/158969/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-22_13.59.36/lib.mongooseim.logs/run.2022-12-22_13.59.37/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158992) / small_tests / 0e7e024ac2240fb99f4ac10af0f96ccb820f505a
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3906/158992/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3906/158992/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-22_15.12.17/lib.mongooseim.logs/run.2022-12-22_15.12.18/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/159019) / small_tests / 35e987e6eda3a71f94170621c9abf95f8dfbb138
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3906/159019/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3906/159019/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-22_15.41.49/lib.mongooseim.logs/run.2022-12-22_15.41.50/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
looks ok

**Pull request merged**
