### PR TITLE
C2s/fix listener access hook

### PR DESCRIPTION
**Pull request by chrzaszcz**
Fix a bug in listener access rules - all hooks being executed instead of one.
Test were added to replicate the issue and make sure it is no longer present after the fix.

The main part of the fix is to match on the listener ID.

More details in the commit messages.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163806) / small_tests / 63107ce5393b839e84b59c929e6d400ef31dbded
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3952/163806/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3952/163806/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-27_15.36.41/lib.mongooseim.logs/run.2023-01-27_15.36.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163915) / small_tests / 3df075c0709c7e6a54beb5471e5a518d892f9325
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3952/163915/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3952/163915/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-30_07.30.08/lib.mongooseim.logs/run.2023-01-30_07.30.09/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/163940) / small_tests / 5b1a3ae3bec9846a930d6382e8d1e726d7180d1e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3952/163940/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3952/163940/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-01-30_07.32.48/lib.mongooseim.logs/run.2023-01-30_07.32.49/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
