### PR TITLE
Refactor async writer for MAM

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "some old ugly code is a bit prettier now".

Proposed changes include:
* No message_queue_len call on each archived message
* Just do cast
* Store messages off the heap
* Remove modMamDropped2 metric

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/66955) / small_tests / 97052e42ff18c0d0a8a049cc36b29d8252d99448
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3216/66955/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3216/66955/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-11_09.58.59/lib.mongooseim.logs/run.2021-08-11_09.58.59/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_22](https://circleci.com/gh/esl/MongooseIM/67176) / small_tests / 3f04b58823b9492555bba7b2bcc91ad055aaf6fd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3216/67176/small_tests.22.3.4.9-1) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3216/67176/small_tests.22.3.4.9-1/small/ct_run.mongooseim@localhost.2021-08-12_08.54.02/lib.mongooseim.logs/run.2021-08-12_08.54.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/67382) / small_tests / cf5ca0fcc8ab482c0d7c3760c112ef51c98abf26
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3216/67382/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3216/67382/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-08-13_08.30.21/lib.mongooseim.logs/run.2021-08-13_08.30.21/suite.log.html)

**Review by chrzaszcz — APPROVED** [review]
Looks good! Load tests show a slight increase in performance and the batches are not lost somehow, maybe because of the removed `spawn_monitor`.

**Review by NelsonVides — COMMENTED** [review]
I like this one too very much as well. The off-heap strategy is a brilliant tiny detail, and nice removing of more spawns 👌🏽

**Pull request merged**
