### PR TITLE
Updating XEP-0060 Publish-Subscribe

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
Include a feature of http://jabber.org/protocol/pubsub#rsm in disco#info response. 

Check preconditions when accepting publish-options along with a publish request. We have two node types which advertise support for the publish-options feature.
In node push the preconditions are not checked. This node type is supporting xep-0163.
In node pep the changes are implemented, and the publish-options are being checked.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/186325) / small_tests / 6a03698fe6516c9907b30daaea5974d6572f40c4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/186325/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/186325/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-10_13.00.26/lib.mongooseim.logs/run.2023-08-10_13.00.27/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/187537) / small_tests / ffb36df8115d3b32cdc82a5d0e0e5de027b5cc74
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187537/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187537/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-14_12.54.08/lib.mongooseim.logs/run.2023-08-14_12.54.09/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/187609) / small_tests / ed3b986a9e678f0398fc52f829e61f9eeac4a815
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187609/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187609/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-14_15.56.35/lib.mongooseim.logs/run.2023-08-14_15.56.36/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187668) / elasticsearch_and_cassandra_mnesia / ff69e493b2d659fa5b393e47ed1cc82ea5fa4616
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187668/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187668/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4075d22998718f.2023-08-14_18.35.46/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187681) / elasticsearch_and_cassandra_mnesia / e54ca55d04ed6b1039d536cd5467b83e6f70b4d0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187681/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187681/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%401f2fd6cb2d12.2023-08-14_18.36.09/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187786) / elasticsearch_and_cassandra_mnesia / cc68fca71b4b622e176e15408ab35fd108105d39
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187786/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187786/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40294dd87c17cc.2023-08-15_10.35.28/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/187820) / elasticsearch_and_cassandra_mnesia / 54adfc081fda303ede2023483014668fcae6658f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4092/187820/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4092/187820/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%40a7b3af9f8629.2023-08-15_13.15.54/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Review by NelsonVides — APPROVED** [review]
LGTM 🔥

**Pull request merged**
