### PR TITLE
Simplify inet_stats/1 in mongoose_metrics

### PR DESCRIPTION
**Pull request by vkatsuba**
Proposed changes include:
* Simplify `inet_stats/1` in `mongoose_metrics`

### CODE REVIEW

**Comment by vkatsuba** [comment]
[GHA](https://github.com/esl/MongooseIM/actions/runs/1199484679)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/70063) / small_tests / 18f3369a2b46b252673c769eaa97b877268f2f9f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3244/70063/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3244/70063/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-03_22.22.56/lib.mongooseim.logs/run.2021-09-03_22.22.56/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/70092) / small_tests / a171c8ab0aaa25ecb8db8138634ac26cbfd5ca69
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3244/70092/small_tests.24.0.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3244/70092/small_tests.24.0.4/small/ct_run.mongooseim@localhost.2021-09-05_08.50.31/lib.mongooseim.logs/run.2021-09-05_08.50.32/suite.log.html)

**Comment by vkatsuba** [comment]
This PR is closed cuz can me used more better and simple approach. Will be done when will be have some change request for it.

**Pull request closed without merging**
