### PR TITLE
Update deps: cqerl

### PR DESCRIPTION
**Pull request by janciesla8818**
This PR aims to update re2, which is the dependency of cqerl.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[8662.1](https://travis-ci.org/esl/MongooseIM/jobs/737417870) / Erlang 23.0.3 / small_tests / 990e49a8145ab9f293553bde7e8ccf975159db65
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2914/8662/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2914/8662/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-10-20_14.40.09/lib.mongooseim.logs/run.2020-10-20_14.40.09/suite.log.html)

**Comment by mongoose-im** [comment]
[8664.1](https://travis-ci.org/esl/MongooseIM/jobs/737658573) / Erlang 23.0.3 / small_tests / e68461a78a0c69a0027c500bf6b7537d3bf373d8
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2914/8664/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2914/8664/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-10-21_09.08.51/lib.mongooseim.logs/run.2020-10-21_09.08.51/suite.log.html)

**Review by NelsonVides — CHANGES_REQUESTED** [review]
In rebar.lock, lines 138 for re2 and 156 for snappy, they don't seem to have been updated in the lock file, they should be pointing to the new urls and so on.

**Comment by mongoose-im** [comment]
[8672.1](https://travis-ci.org/esl/MongooseIM/jobs/738002515) / Erlang 23.0.3 / small_tests / 4491e6f43e22fd5cd6b705446b0c12663996064f
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2914/8672/small_tests.23.0.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2914/8672/small_tests.23.0.3/small/ct_run.mongooseim@localhost.2020-10-22_12.06.06/lib.mongooseim.logs/run.2020-10-22_12.06.07/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
Now it looks cool! 😄 
Let's just wait for CI as usual 🙃

**Pull request merged**
