### PR TITLE
Disable stanza_log

### PR DESCRIPTION
**Pull request by arcusfelis**
- Save Travis builds!

### CODE REVIEW

**Comment by erszcz** [comment]
Let's wait for CI to inspect the behaviour after the change.

**Comment by mongoose-im** [comment]
[8180.1](https://travis-ci.org/esl/MongooseIM/jobs/676167525) / Erlang 22.0 / small_tests / 4be27e44ded4b2bac3e4b112945568412db0cb74
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2717/8180/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2717/8180/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-04-17_12.32.27/lib.mongooseim.logs/run.2020-04-17_12.32.27/suite.log.html)

**Comment by arcusfelis** [comment]
NOPE, first version of this still prints stuff.

**Comment by NelsonVides** [comment]
> NOPE, first version of this still prints stuff.
> 
> Also, love the fact that it fails with: escalus_ct:get_stanza_log/0.
> 
> Wondering, if we use one file per log and we are opening too many of them...

@arcusfelis It fails because of a case clause here, there's no `false` option https://github.com/esl/escalus/blob/master/src/escalus_ct.erl#L82-L95

**Comment by mongoose-im** [comment]
[8184.1](https://travis-ci.org/esl/MongooseIM/jobs/677258839) / Erlang 22.0 / small_tests / 0511994164fc40895d7c95ee3619046a0b151d82
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2717/8184/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2717/8184/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-04-20_13.47.58/lib.mongooseim.logs/run.2020-04-20_13.47.59/suite.log.html)

**Comment by erszcz** [comment]
Seems to work fine now, for example here: https://travis-ci.org/github/esl/MongooseIM/jobs/677258842

**Comment by erszcz** [comment]
Looks good to me now. @NelsonVides @arcusfelis?

**Comment by bartekgorny** [comment]
Since we are at it, why don't we increase default log file size/count limits in app.config? It'd help in debugging failed CI builds.

**Pull request merged**
