### PR TITLE
Erlang27

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "Erlang 27".

Erlang 27 has Jit and cover uses jit for native coverage.
Ensure you see `jit` in the line:
```
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
```

Proposed changes include:
* Meck reported issue to OTP https://github.com/erlang/otp/issues/8661
* Meck reported issue to Meck https://github.com/eproxus/meck/issues/248
* Meck is broken for distributed cover. It does not reactivate cover after `meck:unload/1`. See https://github.com/esl/MongooseIM/pull/4328 as a proof of significant coverage improvement after removing mecking from one of the modules.
Meck still works well, if we enable cover on each node separately - this means slow `cover:do_compile_beam/2` executed on each node...
* amqp_common needed version update - some tips on how to compile on Erlang27, needed to define amqp_common as a dependency explicetly https://github.com/rabbitmq/rabbitmq-server/issues/11593
* CETS on Erlang 27 - useful to merge too, but independent PR https://github.com/esl/cets/pull/55
* geas_rebar3 is pulled by amqp, disabled using overrides (less dependencies to pull). Compilation issue reported https://github.com/crownedgrouse/geas/issues/7
* Fast_tls has a bug - wondering how it was working before? https://github.com/processone/fast_tls/commit/528d9759d6bec714115b5042827726d03e4de0ed - but basically, it uses i2d_x509 which overwrites data pointer in `ErlNifBinary`. For some reason it worked fine before 27. But yes, OpenSSL API is brilliantly confusing.

* worker_pool: report about warnings_as_errors https://github.com/inaka/worker_pool/issues/204 and a fix in 6.2.1 https://github.com/inaka/worker_pool/pull/205

Start nodes is significantly slower: 2 minutes vs 20 seconds with distributed cover.

**Maybe we can use hooks instead of meck for mocking parts of MongooseIM? we could still use meck for stuff which is not cover-compiled.**

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_26](https://circleci.com/gh/esl/MongooseIM/227134) / small_tests / 5bf21c67c5dc1d374bed571f8cd9a546093f400b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227134/small_tests.26.2.2-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227134/small_tests.26.2.2-amd64/small/ct_run.mongooseim@localhost.2024-07-09_14.49.16/lib.mongooseim.logs/run.2024-07-09_14.49.17/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227438) / small_tests / 956fecc33139db801197084f367f860c3c42b3d8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227438/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227438/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-10_15.28.44/lib.mongooseim.logs/run.2024-07-10_15.28.44/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227480) / small_tests / ae3360e51756fc943e5e31f2ec7f0f98edc78d45
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227480/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227480/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-10_15.49.51/lib.mongooseim.logs/run.2024-07-10_15.49.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227508) / small_tests / 7939a061021f55c46a52ea200ada401600d7ed14
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227508/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227508/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-10_21.04.33/lib.mongooseim.logs/run.2024-07-10_21.04.33/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227849) / small_tests / b5013f623ac8dec2a5f15983c2c7abefe7212c68
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227849/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227849/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-11_14.50.10/lib.mongooseim.logs/run.2024-07-11_14.50.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227906) / small_tests / 4a3ac008f3f8d40fdf9c6251968c8fbd27b3cf5d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227906/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227906/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-11_16.13.32/lib.mongooseim.logs/run.2024-07-11_16.13.32/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227932) / small_tests / aa6794f050409f1279edd87b2b285e650ec08f01
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227932/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227932/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-11_19.50.40/lib.mongooseim.logs/run.2024-07-11_19.50.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/227960) / small_tests / aa74cefd7c982edd1278620d478e5d227baebd2f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/227960/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/227960/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-11_20.29.34/lib.mongooseim.logs/run.2024-07-11_20.29.34/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27_arm64](https://circleci.com/gh/esl/MongooseIM/228004) / small_tests / 1838352853b4e5e4181551c2244a19a994ec4462
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/228004/small_tests.27.0-arm64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/228004/small_tests.27.0-arm64/small/ct_run.mongooseim@localhost.2024-07-11_22.06.42/lib.mongooseim.logs/run.2024-07-11_22.06.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_27_arm64](https://circleci.com/gh/esl/MongooseIM/228594) / small_tests / 1efa3675d260bb00d450b25f31db026fbbe7850e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/228594/small_tests.27.0-arm64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/228594/small_tests.27.0-arm64/small/ct_run.mongooseim@localhost.2024-07-15_10.02.37/lib.mongooseim.logs/run.2024-07-15_10.02.37/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/229775) / elasticsearch_and_cassandra_mnesia / e86c4789d4f1c3c2f1eecd0f864426a91ab655b3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/229775/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/229775/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%403440e214d511.2024-07-17_15.49.58/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/229865) / elasticsearch_and_cassandra_mnesia / fe2ab305fd80c30eebbfc0dd80f32fafa486b883
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/229865/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/229865/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%408d5f13a2a147.2024-07-22_08.23.08/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_27](https://circleci.com/gh/esl/MongooseIM/229998) / small_tests / 80199943a5cc83298a1f0dfc4416cdba45077c28
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/229998/small_tests.27.0-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/229998/small_tests.27.0-amd64/small/ct_run.mongooseim@localhost.2024-07-22_20.14.32/lib.mongooseim.logs/run.2024-07-22_20.14.33/suite.log.html)

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230061) / ldap_mnesia / 04fec95971ebc0091737161d223b74d7adb287b7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230061/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230061/ldap_mnesia.26.2.2-amd64/big/ct_run.test%4045942c4b811a.2024-07-22_21.26.08/index.html)
**OK: 581** / Failed: 0 / **User-skipped: 169** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230090) / ldap_mnesia / dc311179fd516066d7214ff651f8efd0b049dcb5
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230090/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230090/ldap_mnesia.26.2.2-amd64/big/ct_run.test%40ab316c4b1f4d.2024-07-22_22.05.13/index.html)
**OK: 287** / Failed: 0 / **User-skipped: 2** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230124) / ldap_mnesia / 69fe0e5c347b807162024049849a816dd6c4b462
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230124/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230124/ldap_mnesia.26.2.2-amd64/big/ct_run.test%4077b22ebd24c3.2024-07-22_22.22.41/index.html)
**OK: 44** / Failed: 0 / User-skipped: 0 / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230228) / pgsql_mnesia / cf072a45d5e7f267e1b81f84bd5b3a2b54fef40e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230228/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230228/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%409025b26e2721.2024-07-23_08.26.05/index.html)
**OK: 1** / Failed: 0 / User-skipped: 0 / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230258) / pgsql_mnesia / 56567be1a3e0aa24dd313552c58a0f8879710515
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230258/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230258/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%40f2694fb2280d.2024-07-23_08.35.25/index.html)
**OK: 53** / Failed: 0 / User-skipped: 0 / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230288) / pgsql_mnesia / 9a7b55eabd7972ac6dcd8b5905e3afac3828bf97
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230288/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230288/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%4026bc193a4338.2024-07-23_08.50.50/index.html)
**OK: 92** / Failed: 0 / User-skipped: 0 / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230323) / ldap_mnesia / 102afeb4d41a4e5321b8aaf9ccef579a4189c564
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230323/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230323/ldap_mnesia.26.2.2-amd64/big/ct_run.test%40ac1926a71160.2024-07-23_08.59.57/index.html)
**OK: 105** / Failed: 0 / **User-skipped: 2** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230355) / ldap_mnesia / 9d925c2dbabd953f23ba628520e487331aa7ba1f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230355/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230355/ldap_mnesia.26.2.2-amd64/big/ct_run.test%40afe56a550212.2024-07-23_09.17.59/index.html)
**OK: 283** / Failed: 0 / **User-skipped: 2** / Auto-skipped: 0 

---

[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230354) / pgsql_mnesia / 9d925c2dbabd953f23ba628520e487331aa7ba1f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230354/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230354/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%40c10267acc720.2024-07-23_09.18.00/index.html)
**OK: 381** / Failed: 0 / **User-skipped: 16** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230386) / pgsql_mnesia / 4eaaac0fe3ea8799de450765236dc9c7fc74cfba
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230386/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230386/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%40de18b13b2edd.2024-07-23_09.59.25/index.html)
**OK: 275** / Failed: 0 / **User-skipped: 16** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[pgsql_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230418) / pgsql_mnesia / 9bdc87048bc9d1f1fe11c3ab218fb37ff021523f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230418/pgsql_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230418/pgsql_mnesia.26.2.2-amd64/big/ct_run.test%4086de279a3fe0.2024-07-23_10.39.28/index.html)
**OK: 163** / Failed: 0 / User-skipped: 0 / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[ldap_mnesia_26](https://circleci.com/gh/esl/MongooseIM/230487) / ldap_mnesia / 38fd3cd0c7f8d529907b724c72ff3b86a1371fe9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230487/ldap_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230487/ldap_mnesia.26.2.2-amd64/big/ct_run.test%402f8b5b343334.2024-07-23_12.31.43/index.html)
**OK: 159** / Failed: 0 / **User-skipped: 4** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_27](https://circleci.com/gh/esl/MongooseIM/230744) / odbc_mssql_mnesia / 5f0fabebc7b8479bb847bc0839bdae8cf84db314
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230744/odbc_mssql_mnesia.27.0-amd64)

**Comment by mongoose-im** [comment]
[dynamic_domains_mssql_mnesia_27](https://circleci.com/gh/esl/MongooseIM/230783) / odbc_mssql_mnesia / 2510eb40a8cd141a40bf81eb84d524317705f965
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230783/odbc_mssql_mnesia.27.0-amd64)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/230823) / elasticsearch_and_cassandra_mnesia / 0baa124a2452ed5261461400d34a37412e43b77c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230823/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230823/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%40107bc87551ab.2024-07-23_23.09.24/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/230851) / elasticsearch_and_cassandra_mnesia / 17c870eead330bb9cccf0d8a0dba917c77c02559
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230851/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230851/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%407089ce3dab0d.2024-07-23_23.12.39/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/230882) / elasticsearch_and_cassandra_mnesia / 86cbe8685beeef0d2e14509cb8335b90d9a54d23
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/230882/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/230882/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%40d72a408b6190.2024-07-23_23.24.02/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/231766) / elasticsearch_and_cassandra_mnesia / cf9598c106533c08016a9d211b58c376232b0d98
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4320/231766/elasticsearch_and_cassandra_mnesia.27.0-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4320/231766/elasticsearch_and_cassandra_mnesia.27.0-amd64/big/ct_run.test%4081cf8adf804d.2024-07-25_13.31.01/index.html)
**OK: 439** / Failed: 0 / **User-skipped: 47** / Auto-skipped: 0

**Comment by arcusfelis** [comment]
Moved to https://github.com/esl/MongooseIM/pull/4348

**Pull request closed without merging**
