### PR TITLE
[skip ci] new push notification graph

### PR DESCRIPTION
**Pull request by goddammit**
This PR addresses #

Proposed changes include:
* describe the functionality changes
* describe new or updated tests
* describe changes to the documentation

### CODE REVIEW

**Comment by fenek** [comment]
@rslota Is the new graph correct? As far as I can see in the code, `mod_push_service_mongoosepush doesn't call `mod_pubsub`, but MongoosePush directly. Am I right?

**Comment by rslota** [comment]
> @rslota Is the new graph correct? As far as I can see in the code, mod_push_service_mongoosepush doesn't callmod_pubsub`, but MongoosePush directly. Am I right?

Yes, you're right. It's the other way around. `mod_push` passes notification to `mod_pubsub`, `mod_pubsub` uses hook to pass it to `mod_push_service_mongoosepush` and then `mod_push_service_mongoosepush` uses REST API to pass it to `MongoosePush.

**Comment by fenek** [comment]
@goddammit 

When can we expect the updated graph?

**Comment by rslota** [comment]
@fenek @goddammit The diagram is fixed now :)

**Comment by fenek** [comment]
@rslota 

Not yet. It still says "mypubUSB" :)

**Comment by rslota** [comment]
> Not yet. It still says "mypubUSB" :)

Oh, didn't notice that.

**Comment by rslota** [comment]
@fenek I've removed the USB.

**Comment by goddammit** [comment]
so can we close this?

**Comment by fenek** [comment]
@goddammit I'm waiting for last master build to succeed before merging any further PRs.

**Pull request merged**
