### PR TITLE
Instrument/hook handlers: privacy

### PR DESCRIPTION
**Pull request by chrzaszcz**
The goal is to use instrumentation rather than hook handlers to collect metrics in the privacy modules (`mod_privacy`, `mod_blocking`).

Main changes:
- Events are triggered in `mod_privacy`, because `mod_blocking` is calling functions from the former.
- One hook is removed, because it was used only for metrics.
- The event is usually generated either before the relevant hook is triggered. However, the `check_packet` event is triggered in the handler, because the hook is called from other modules, while it is handled in `mod_privacy`, which performs the actual check.
- Events are checked in tests for both modules. I added the check to most of the places, but the goal was not to cover all test cases with them. Some checks are in the helpers, and this is why I needed to declare one event in AMP test suite.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/221924) / elasticsearch_and_cassandra_mnesia / b960a3c73f85ca79ace335a297624f6bcb48ea93
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4298/221924/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4298/221924/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40217fc79a20d8.2024-06-11_14.23.16/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/222156) / elasticsearch_and_cassandra_mnesia / dfd78d927633b91cd55d1f6a2ad15b298ecc6874
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4298/222156/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4298/222156/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40d4de7e407042.2024-06-12_14.39.32/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/222207) / elasticsearch_and_cassandra_mnesia / 9104119126d1a0d516945591f75b6ecece743571
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4298/222207/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4298/222207/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40b7a82d075f70.2024-06-13_06.49.29/index.html)
**OK: 457** / Failed: 0 / **User-skipped: 41** / Auto-skipped: 0

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
