### PR TITLE
Convert ejabberd_auth to gen_hook

### PR DESCRIPTION
**Pull request by kamilwaz**
Convert ejabberd_auth to gen_hook

### CODE REVIEW

**Comment by mongoose-im** [comment]
[pgsql_mnesia_24](https://circleci.com/gh/esl/MongooseIM/147870) / pgsql_mnesia / bae9bd1f759e64c2967faafb8b7a470070ed7972
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3832/147870/pgsql_mnesia.24.3.4)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147931) / small_tests / 961d3ec428247181f96963b996f95de7f77376d6
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3832/147931/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3832/147931/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_13.05.10/lib.mongooseim.logs/run.2022-10-28_13.05.11/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/147994) / small_tests / b5d03f13b14ad72cdbe9b445e79c5ba3844541ff
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3832/147994/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3832/147994/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-10-28_13.42.26/lib.mongooseim.logs/run.2022-10-28_13.42.27/suite.log.html)

**Review by pawlooss1 — APPROVED** [review]
Neat 👌

**Pull request merged**
