### PR TITLE
Fix package build scripts

### PR DESCRIPTION
**Pull request by sebb7**
This PR allows current build scripts to be used for Ubuntu Focal and Centos 8.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[8293.1](https://travis-ci.org/esl/MongooseIM/jobs/689972568) / Erlang 22.0 / small_tests / 1facf8160222d6084ecc9da73ef3dd86e42b74f9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2752/8293/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2752/8293/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-05-22_09.51.07/lib.mongooseim.logs/run.2020-05-22_09.51.07/suite.log.html)

**Comment by sebb7** [comment]
Please do not merge it. I need to add one more fix.

**Comment by mongoose-im** [comment]
[8352.1](https://travis-ci.org/esl/MongooseIM/jobs/705466245) / Erlang 22.0 / small_tests / c553088b7e58e869a0586db42f10c5cdc21eba34
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2752/8352/small_tests.22.0) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2752/8352/small_tests.22.0/small/ct_run.mongooseim@localhost.2020-07-06_16.11.33/lib.mongooseim.logs/run.2020-07-06_16.11.33/suite.log.html)

**Comment by sebb7** [comment]
The newest changes were needed in order to:
- remove perl/python dependencies from MIM package explicitly, not by removing scripts one by one,
- remove erlang from CentOS 8 MIM package dependencies - shebang manipulation is disabled now - before shebangs were changed by rpm building tools during package building e.g.:
```
mangling shebang in /usr/lib/mongooseim/scripts/bootstrap20-template.escript from /usr/bin/env escript to #!/usr/bin/escript
```

**Pull request merged**
