### PR TITLE
Docker arm64 smoke test

### PR DESCRIPTION
**Pull request by chrzaszcz**
Run docker image smoke test for arm64

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_25](https://circleci.com/gh/esl/MongooseIM/170000) / small_tests / 7db21b2cd9b624c37552caf92d147d82de1f8172
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170000/small_tests.25.2.3-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170000/small_tests.25.2.3-amd64/small/ct_run.mongooseim@localhost.2023-03-16_07.39.38/lib.mongooseim.logs/run.2023-03-16_07.39.39/suite.log.html)

---

[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170015) / small_tests / 7db21b2cd9b624c37552caf92d147d82de1f8172
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170015/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170015/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_07.40.38/lib.mongooseim.logs/run.2023-03-16_07.40.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170034) / small_tests / cd98c716ba1d2695629d036d54148f5e877799e4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170034/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170034/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_08.38.15/lib.mongooseim.logs/run.2023-03-16_08.38.15/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170059) / small_tests / 65a1f865b5f970bdfd215bffc4ee3a9c1e69d1c1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170059/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170059/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_09.02.02/lib.mongooseim.logs/run.2023-03-16_09.02.02/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170092) / small_tests / 048ce7b8337e04f243e7a7094c4c97f8965b2561
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170092/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170092/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_10.13.13/lib.mongooseim.logs/run.2023-03-16_10.13.14/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170156) / small_tests / 79c0eec0db2af79051b48305750257d82c7fc54b
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170156/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170156/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_11.06.39/lib.mongooseim.logs/run.2023-03-16_11.06.39/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170184) / small_tests / 6ff2119035bf60fee10e5be18e43daf57a05aad4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170184/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170184/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_11.29.02/lib.mongooseim.logs/run.2023-03-16_11.29.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170218) / small_tests / 91e1586a9f3cb2331652e0146dee3a4785cefa80
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170218/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170218/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_11.44.05/lib.mongooseim.logs/run.2023-03-16_11.44.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170245) / small_tests / 0af5f301d43e6fc912da1bca72e72dbd040903e9
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170245/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170245/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_11.58.42/lib.mongooseim.logs/run.2023-03-16_11.58.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170274) / small_tests / 0b8c4dfd184b6be1e08b1b69942588d29f156537
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170274/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170274/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_12.14.40/lib.mongooseim.logs/run.2023-03-16_12.14.40/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170329) / small_tests / 7a9e4a90de8f7963efa5083d358158514c7c9c92
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170329/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170329/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_12.31.23/lib.mongooseim.logs/run.2023-03-16_12.31.23/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170358) / small_tests / a74c1a463f00a1e3950282b5f2587e5c77c45c80
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170358/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170358/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_13.04.41/lib.mongooseim.logs/run.2023-03-16_13.04.42/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/170392) / small_tests / d9fefc1dadb18fe4b4f051b2c38d326af01a1e63
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3988/170392/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3988/170392/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-03-16_14.09.17/lib.mongooseim.logs/run.2023-03-16_14.09.18/suite.log.html)

**Review by DenysGonchar — APPROVED** [review]
LGTM

**Pull request merged**
