### PR TITLE
Do not use mongoose_commands in the Client REST API

### PR DESCRIPTION
**Pull request by chrzaszcz**
Main changes:
- Use `mod_roster_api` directly in `mongoose_client_api_contacts` to make it consistent with the other `mongoose_cient_api_*` modules.
- Remove the obsolete `mongoose_api_client`, which was replaced by `mongoose_client_api`.

Other changes:
- Copy some code from `mod_commands` to `mongoose_client_api_contacts`. This allowed to simplify the logic.
- Disable the clients API for the `user` policy in `mod_commands` - it's admin-only now.
- Add type specs for request handling. Some `cowboy_rest` callbacks have complicated raw types, and I decided not to spec them all for this reason - it would complicate this PR.

Excluded from this PR:
- Error handling improvements - multiple conditions resulted in `internal server error` before, and this is unchanged.
- Removal of the code from `mod_commands`. To do so, the admin API would need to use the `_*api` modules directly.
- Making `mongoose_client_api_messages` use helper functions, just like the other API modules do - we missed this when implementing GraphQL API for messages (stanzas).
- Adding `mongoose_client_api_accounts` with the `change_password` command. It is now missing, because `mongoose_api_client` is removed.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128016) / small_tests / 09f4e4252416fd9331391224b97d1ac7133dbd93
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128016/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128016/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-27_12.59.33/lib.mongooseim.logs/run.2022-06-27_12.59.33/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128433) / small_tests / 5c16bc40aea42da9b5088df0a903734a66b0c41d
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128433/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128433/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-29_12.12.05/lib.mongooseim.logs/run.2022-06-29_12.12.05/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128457) / small_tests / 9c5d64caf96aa628304ae0fb4b47b398cc20e776
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128457/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128457/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-29_12.35.45/lib.mongooseim.logs/run.2022-06-29_12.35.45/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128486) / small_tests / 9a1cf16f8f0caa91fa8acb78af18c1004b7a4ee3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128486/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128486/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-29_13.37.03/lib.mongooseim.logs/run.2022-06-29_13.37.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128558) / small_tests / 079be4de1c198d9397230757537aef1fef9060bf
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128558/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128558/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-30_07.45.07/lib.mongooseim.logs/run.2022-06-30_07.45.07/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128638) / small_tests / af5e2578c3258f54c2e713ba672e6cf50116ffbd
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128638/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128638/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-30_11.22.51/lib.mongooseim.logs/run.2022-06-30_11.22.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128666) / small_tests / 69abc99784fb7ab4349e21c1b88d805f2507172f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128666/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128666/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-06-30_12.27.38/lib.mongooseim.logs/run.2022-06-30_12.27.38/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/128692) / small_tests / 77ca7882271bd2a7af58ba6f81555ba72f0454b8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3697/128692/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3697/128692/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-07-01_06.55.15/lib.mongooseim.logs/run.2022-07-01_06.55.15/suite.log.html)

**Review by Premwoik — APPROVED** [review]
Looks good 👍 I can't see any better solution. It's always hard for me to read these Rest API modules.

The interesting will be to stop using `mongoose_commands` in `mongoose_api_admin` because the endpoint is matched to the corresponding command automatically. So we probably need to define endpoints manually and then call the API modules from them?

I remember that Escalus uses functions from `mod_commands`, so we will need to change it to use the corresponding API module.

**Pull request merged**
