### PR TITLE
Use new Escalus

### PR DESCRIPTION
**Pull request by chrzaszcz**
Keep escalus up to date.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[6190.1](https://travis-ci.org/esl/MongooseIM/jobs/495916372) / Erlang 19.3 / small_tests / c1e332a943a9986bed3003f38933d5929ba5d4a9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2224/6190/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2224/6190/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-02-20_10.36.15/lib.mongooseim.logs/run.2019-02-20_10.36.16/suite.log.html)

**Comment by mongoose-im** [comment]
[6192.1](https://travis-ci.org/esl/MongooseIM/jobs/496053903) / Erlang 19.3 / small_tests / b045ddd0827e3e1c0d536e2d5871722429548f83
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2224/6192/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2224/6192/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-02-20_15.43.36/lib.mongooseim.logs/run.2019-02-20_15.43.37/suite.log.html)

**Comment by mongoose-im** [comment]
[6219.1](https://travis-ci.org/esl/MongooseIM/jobs/502519456) / Erlang 19.3 / small_tests / be53234907d80546eaf8e9e4e1d77b13084536b9
Reports [root](http://esl.github.io/mongooseim-ct-reports/s3_reports.html?prefix=PR/2224/6219/small_tests.19.3) / [small](https://mongooseim-ct-results.s3-eu-west-1.amazonaws.com/PR/2224/6219/small_tests.19.3/small/ct_run.mongooseim@localhost.2019-03-06_11.36.18/lib.mongooseim.logs/run.2019-03-06_11.36.18/suite.log.html)

**Comment by erszcz** [comment]
Awesome!

**Pull request merged**
