### PR TITLE
Prepare Release 6.0.0

### PR DESCRIPTION
**Pull request by chrzaszcz**
## Highlights

- GraphQL API and Command Line Interface (CLI) with many new commands
- Unified and reworked REST API
- Incremental and asynchronous dynamic domain deletion
- Full pagination support with RSM for Inbox
- Significant code refactoring
- Various improvements and fixes

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/157912) / small_tests / d98ec47fdbb3f7d5a43aa3a9dbcbb733fdb69d33
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3901/157912/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3901/157912/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-15_08.56.03/lib.mongooseim.logs/run.2022-12-15_08.56.03/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158179) / small_tests / b1fcbe7140cf910763874f109717595c35a12707
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3901/158179/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3901/158179/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-15_16.34.40/lib.mongooseim.logs/run.2022-12-15_16.34.41/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158362) / small_tests / 96960a86210322b2e6444bdf9d72938406e29924
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3901/158362/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3901/158362/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-16_16.01.54/lib.mongooseim.logs/run.2022-12-16_16.01.55/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158390) / small_tests / f97f5f68267984c2ff97e05f1fd97c849008b62c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3901/158390/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3901/158390/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-19_07.12.46/lib.mongooseim.logs/run.2022-12-19_07.12.46/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/158419) / small_tests / ec72b42e1cc58b5ba30b1c339888584334c53ea4
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3901/158419/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3901/158419/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2022-12-19_07.52.44/lib.mongooseim.logs/run.2022-12-19_07.52.45/suite.log.html)

**Review by JanuszJakubiec — APPROVED** [review]
Looks good

**Pull request merged**
