### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by NelsonVides**
A few cosmetic changes that can be taken out of the rework for components and merged already to master.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251782) / elasticsearch_and_cassandra_mnesia / c3a73d7b10d2aab49fb6bc10249a5bdd8dc70e20
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/251782/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/251782/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%4029f5dd9e658d.2024-12-17_15.24.48/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251839) / elasticsearch_and_cassandra_mnesia / 6e9a26c9e56dd0c1489ab5a70e9746eda1de3039
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/251839/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/251839/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%400aaf35d7e923.2024-12-17_16.24.27/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251871) / elasticsearch_and_cassandra_mnesia / 4357536ebf38f3cddf354da1e63f9602454b7f8c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/251871/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/251871/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40fa39de79d7f4.2024-12-17_17.12.07/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251899) / elasticsearch_and_cassandra_mnesia / d86e89c4f1273a4d2c7147e8cd328a173171d693
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/251899/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/251899/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40a2d3f8e9373b.2024-12-17_18.24.19/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/251972) / elasticsearch_and_cassandra_mnesia / 9408ed3b37eb0c4bc6ce9fdc95dbc6cbb1c06526
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/251972/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/251972/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40bc3e0b4ca065.2024-12-18_07.05.00/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0 
<details><summary>mam_SUITE:cassandra_muc_all:muc06:muc_message_with_stanzaid</summary>


```erlang
{failed,
  {mam_SUITE,end_per_testcase,
    {'EXIT',
      {{room_archive_size,0,[{times,200,1}],undefined},
       [{wait_helper,do_wait_until,1,
          [{file,
             "/home/circleci/project/big_tests/_build/default/lib/wait_helper/src/wait_helper.erl"},
           {line,127}]},
        {mam_helper,wait_for_room_archive_size,3,
          [{file,
             "/home/circleci/project/big_tests/tests/mam_helper.erl"},
           {line,800}]},
        {mam_helper,clean_room_archive,1,
          [{file,
             "/home/circleci/project/big_tests/tests/mam_helper.erl"},
           {line,744}]},
        {mam_helper,destroy_room,1,
          [{file,
             "/home/circleci/project/big_tests/tests/mam_helper.erl"},
           {line,737}]},
        {mam_SUITE,end_per_testcase,2,
          [{file,
             "/home/circleci/project/big_tests/tests/mam_SUITE.erl"},
           {line,980}]},
        {test_server,do_end_per_testcase,4,
          [{file,"test_server.erl"},{line,1638}]},
        {test_server,run_test_case_eval1,6,
          [{file,"test_server.erl"},{line,1346}]},
        {test_server,run_test_case_eval,9,
          [{file,"test_server.erl"},{line,1235}]}]}}}}
```

[Report log](https://esl.github.io/html-zip-reader/PR/4441/251972/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40bc3e0b4ca065.2024-12-18_07.05.00/big_tests.tests.mam_SUITE.logs/run.2024-12-18_07.05.00/mam_suite.muc_message_with_stanzaid.9091.html)
</details>

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252009) / elasticsearch_and_cassandra_mnesia / b834f9df544a44c9a2920f61c1e19a8a644b05bc
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/252009/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/252009/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%403f0ecefbed15.2024-12-18_07.27.54/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252030) / elasticsearch_and_cassandra_mnesia / aca6ad9e0aeca10c5f3d43fd192b6dbdc0c92458
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/252030/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/252030/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%404169514f1ecd.2024-12-18_07.45.12/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_27](https://circleci.com/gh/esl/MongooseIM/252059) / elasticsearch_and_cassandra_mnesia / 08f53a05e92b7a7ac84e90ddbd8e258ccf1c5726
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4441/252059/elasticsearch_and_cassandra_mnesia.27.1.2-amd64)/ [big](https://esl.github.io/html-zip-reader/PR/4441/252059/elasticsearch_and_cassandra_mnesia.27.1.2-amd64/big.tar.gz//ct_run.test%40845d9caceaf2.2024-12-18_08.59.30/index.html)
**OK: 472** / Failed: 0 / **User-skipped: 49** / Auto-skipped: 0

**Review by telezynski — APPROVED** [review]
Looks good

**Pull request merged**
