### PR TITLE
Mongoose commands improvements

### PR DESCRIPTION
**Pull request by michalwski**
Proposed changes include:
* mongoose_command's category as binary
* mongoose_command's description as binary
* updated relevant modules and tests affected by the change

### CODE REVIEW

**Comment by arcusfelis** [comment]
Looks fine, but I personally like how it was before (atoms and lists).

**Comment by ludwikbukowski** [comment]
but actually there were just redundant conversions from atom

**Comment by michalwski** [comment]
Ok, I hear you :) why did you like it better?

**Comment by bartekgorny** [comment]
For me the previous version looked better, without all the <<" fluff. But it is a matter of taste. Anyway, ok from me.

**Comment by michalwski** [comment]
Ok, let me explain.

1. The reason to change `category` from atom to binary is to avoid unnecessary conversion from/to binary.
2. The reason to change `des` from ordinary string to binaries is that in the code base we use binaries to represent text. I just want to be consistent with that.

**Comment by bartekgorny** [comment]
Yes I know, so I'm not opposing, just chiming in to show I have something to say ;)

**Pull request merged**
