### PR TITLE
Fix and update package building scripts

### PR DESCRIPTION
**Pull request by chrzaszcz**
This PR fixes and updates the packages built with CircleCI.

The original issue was that the `packages.erlang-solutions.com/...` repos stopped working. I reported this, and they are almost fully functional again (except for Centos 7).

In the meantime, I researched possible alternatives, because the repos are now considered old and discontinued.
- Using the new repos `binaries2.erlang-solutions.com/...` would be a good option, but they don't work. I reported this, but it will take time to fix these issues.
- Using directly downloaded packages from https://www.erlang-solutions.com/downloads/. This option worked correctly, so I used it.

With the new packages it was possible to update the Erlang versions, and add support for the newer Ubuntu 22.04 Jammy Jellyfish.

Notes:
- I had to use a few different Erlang versions, because of the availability of downloadable packages. This should be fixed, because we need to support all distros for each new Erlang version, and currently it is random. I reported all the issues with ESL Erlang packages.
- In the future we might want to support Arm64, but Erlang packages are not available atm, so it's a task for the future.
- I had to remove RPaths from the `rpm` packages to avoid errors, just like here https://github.com/esl/packages-pipeline/blob/master/esl_erlang/ctx/scripts/rpm/script.sh#L100-L101.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216539) / elasticsearch_and_cassandra_mnesia / f9e3fe145afa078836c5e9aeac88f2f9a6c0bd53
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216539/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216539/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%408b519929b1b1.2024-04-23_07.19.10/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216656) / elasticsearch_and_cassandra_mnesia / 496f6f3227816cbb1a1d8abe2ac718cadba7658c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216656/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216656/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%408c82dc8c2453.2024-04-23_09.28.16/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216684) / elasticsearch_and_cassandra_mnesia / 59b8484b6c96e5eb711fee48ef14c15cb3146d9f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216684/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216684/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%406289ae2221eb.2024-04-23_10.19.07/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216725) / elasticsearch_and_cassandra_mnesia / ae82786e0f07d95d51a618cb0fb5971e38d324fb
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216725/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216725/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40bad82eab95f2.2024-04-23_10.31.23/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216791) / elasticsearch_and_cassandra_mnesia / ca6728cc653ee69d2e0c6bff9da2a06ccc2e89c0
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216791/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216791/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%409e73882ccae0.2024-04-23_10.39.30/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216902) / elasticsearch_and_cassandra_mnesia / b7f9f3b08efd11c7bcd6168d27ef5a070e3cba31
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216902/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216902/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40244a0ac7bf4a.2024-04-23_12.28.40/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216926) / elasticsearch_and_cassandra_mnesia / 2fa7c12ce4ecdee17bc2af51ff473fb55a4811b7
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216926/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216926/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%408e360dca5a5e.2024-04-23_13.57.02/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/216963) / elasticsearch_and_cassandra_mnesia / c1bf34b363ea955d14447746a41016b3c54d8623
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/216963/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/216963/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4096e3ff45f431.2024-04-23_14.17.45/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217125) / elasticsearch_and_cassandra_mnesia / 771e7eab83668dc49daefbb2960305e8a230da0f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217125/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217125/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40600ba50f666e.2024-04-24_13.08.11/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217234) / elasticsearch_and_cassandra_mnesia / 6fc4efaf669fff3f9dbbfd5047a83fb66a72f513
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217234/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217234/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40b53aa8ece040.2024-04-24_16.58.12/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217240) / elasticsearch_and_cassandra_mnesia / e2073d014be885c7896c11d4b05c82671e8a88e3
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217240/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217240/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4020dd23f773a1.2024-04-24_16.59.04/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217280) / elasticsearch_and_cassandra_mnesia / 86d829ca054f9b6faa004d33d31e2ebae2cfde82
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217280/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217280/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40e8e15ca0a455.2024-04-24_17.09.03/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217349) / elasticsearch_and_cassandra_mnesia / 15952505f7aa7d15be79216f349081d62a418386
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217349/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217349/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4078b684953a0c.2024-04-24_17.26.13/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217382) / elasticsearch_and_cassandra_mnesia / 1bb61a9709b3fe78f6162f907385e66ebc27a845
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217382/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217382/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%4084154ee9e232.2024-04-25_06.50.30/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217411) / elasticsearch_and_cassandra_mnesia / 2eeac6d2054067398e02058bc333599aea4bfe83
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217411/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217411/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40606522a0441d.2024-04-25_07.09.33/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217449) / elasticsearch_and_cassandra_mnesia / b30bf698a0fd7773339c33922a08c0613007e543
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217449/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217449/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%405967b964b9b2.2024-04-25_07.35.59/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/217523) / elasticsearch_and_cassandra_mnesia / 05f03eb4fe7be54a646568cbb011e4bb9b6373da
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4273/217523/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4273/217523/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40d4e2178032bc.2024-04-25_07.59.49/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by jacekwegr — APPROVED** [review]
Looks good! 👍Thanks for fixing the package scripts!

**Pull request merged**
