### PR TITLE
Fixing flaky tests

### PR DESCRIPTION
**Pull request by JanuszJakubiec**
Adding a function to assert the connection result. Allowing to return {error, connection_closed} in tests where the error was expected.

The proposed solution, of running the tests sequentially didn't solve the problem. Therefore it was proposed to add the error {error, connection_closed} as an acceptable result of tests where the SSL certificate wasn't valid.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215660) / elasticsearch_and_cassandra_mnesia / d6263524675b0622a5f64ae74fbb4ed1e773872f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4267/215660/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4267/215660/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40bfa8fdf17f3e.2024-04-16_10.12.49/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215693) / elasticsearch_and_cassandra_mnesia / 22cf3aae670e5bbdd1404b9ca53f94826f6efa9e
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4267/215693/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4267/215693/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%40f35968e9091d.2024-04-16_10.55.41/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by chrzaszcz — COMMENTED** [review]
Looks good as a temporary solution 👍 
How about squashing the two commits together?

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_26](https://circleci.com/gh/esl/MongooseIM/215726) / elasticsearch_and_cassandra_mnesia / 915cbd35ac43f26421eddf9691ad7330594103d8
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4267/215726/elasticsearch_and_cassandra_mnesia.26.2.2-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4267/215726/elasticsearch_and_cassandra_mnesia.26.2.2-amd64/big/ct_run.test%409f4f9ff33f14.2024-04-16_11.59.38/index.html)
**OK: 437** / Failed: 0 / **User-skipped: 43** / Auto-skipped: 0

**Review by chrzaszcz — APPROVED** [review]
👌

**Pull request merged**
