### PR TITLE
Merge master into cets

### PR DESCRIPTION
**Pull request by arcusfelis**
This PR addresses "Sync with upstream".

Proposed changes include:
* Resolve conflict in ejabberd_app.
* Update CETS version.

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/184181) / small_tests / f62752f02470e6957355528289158e92f5fcb3ef
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4078/184181/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4078/184181/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-04_15.18.06/lib.mongooseim.logs/run.2023-08-04_15.18.06/suite.log.html)

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/184223) / elasticsearch_and_cassandra_mnesia / feec9670c3040e2022585f3ffa316333d38bd0c1
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4078/184223/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4078/184223/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4004f6f42bed33.2023-08-04_15.33.48/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[elasticsearch_and_cassandra_25](https://circleci.com/gh/esl/MongooseIM/184259) / elasticsearch_and_cassandra_mnesia / df35aee8d6afbb81f444f57d0e36f102380e3860
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4078/184259/elasticsearch_and_cassandra_mnesia.25.3-amd64)/ [big](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4078/184259/elasticsearch_and_cassandra_mnesia.25.3-amd64/big/ct_run.test%4022ab1429e3b7.2023-08-04_16.36.58/index.html)
**OK: 369** / Failed: 0 / **User-skipped: 38** / Auto-skipped: 0

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/184285) / small_tests / 083ea91b96d7a2815cdc03b40e2e0cceb054155c
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/4078/184285/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/4078/184285/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-08-04_20.55.03/lib.mongooseim.logs/run.2023-08-04_20.55.03/suite.log.html)

**Review by NelsonVides — APPROVED** [review]
LGTM. But also the extra fixes in the last commits would be good to have them in master already. Anyway if this is merging to master soon then it's fine for me.

**Review by chrzaszcz — COMMENTED** [review]
Looks good 👍

**Pull request merged**
