### PR TITLE
Fix indicators links to point to the latest release

### PR DESCRIPTION
**Pull request by pawlooss1**
All status badges now point to the `rel-6.0` branch. They can be previewed here https://github.com/esl/MongooseIM/tree/fix-readme-project-status.

DG: 
added 2 minor updates:
* checrry-picked c48e2ef8f
* added missing `app.` to codecov url

### CODE REVIEW

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/167605) / small_tests / 90fde47d2a34843706efd858322fab8e202069ec
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3975/167605/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3975/167605/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-03_10.12.51/lib.mongooseim.logs/run.2023-03-03_10.12.52/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/167634) / small_tests / 6f90fca850d9ac108a3cab84f7b4bcafde8cb73f
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3975/167634/small_tests.24.3.4) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3975/167634/small_tests.24.3.4/small/ct_run.mongooseim@localhost.2023-03-03_10.18.51/lib.mongooseim.logs/run.2023-03-03_10.18.51/suite.log.html)

**Comment by mongoose-im** [comment]
[small_tests_24](https://circleci.com/gh/esl/MongooseIM/172077) / small_tests / 23aa98dab64cf4b0bc771dc88b9ffda9804f8403
Reports [root](http://esl.github.io/circleci-mim-results/s3_reports.html?prefix=PR/3975/172077/small_tests.24.3.4.9-amd64) / [small](https://circleci-mim-results.s3.eu-central-1.amazonaws.com/PR/3975/172077/small_tests.24.3.4.9-amd64/small/ct_run.mongooseim@localhost.2023-04-01_12.18.34/lib.mongooseim.logs/run.2023-04-01_12.18.35/suite.log.html)

**Review by arcusfelis — APPROVED** [review]
ok

**Pull request merged**
